== The Linux File System

It is important to have a basic understanding of the fundamentals of the Linux file system: where your files are kept, where software is installed, where the danger zones are, and so on. For more information, please refer to the Linux https://wiki.debian.org/FilesystemHierarchyStandard[Filesystem Hierarchy Standard].

=== Home

When you log into a Raspberry Pi and open a terminal window, or you boot to the command line instead of the graphical user interface, you start in your home folder; this is located at `/home/pi`, assuming your username is `pi`.

This is where the user's own files are kept. The contents of the user's desktop is in a directory here called `Desktop`, along with other files and folders.

To navigate to your home folder on the command line, simply type `cd` and press `Enter`. This is the equivalent of typing `cd /home/pi`, where `pi` is your username. You can also use the tilde key (`~`), for example `cd ~`, which can be used to relatively link back to your home folder. For instance, `cd ~/Desktop/` is the same as `cd /home/pi/Desktop`.

Navigate to `/home/` and run `ls`, and you'll see the home folders of each of the users on the system.

Note that if logged in as the root user, typing `cd` or `cd ~` will take you to the xref:using_linux.adoc#root-and-sudo[root] user's home directory; unlike normal users, this is located at `/root/` not `/home/root/`. 

