== Linux Users

User management in Raspberry Pi OS is done on the command line. The default user is `pi`, and the password is `raspberry`. You can add users and change each user's password.

=== Changing your Password

Once you're logged in as the `pi` user, it is highly advisable to use the `passwd` command to change the default password to improve your Raspberry Pi's security.

Enter `passwd` on the command line and press `Enter`. You'll be prompted to enter your current password to authenticate, and then asked for a new password. Press `Enter` on completion and you'll be asked to confirm it. Note that no characters will be displayed while entering your password. Once you've correctly confirmed your password, you'll be shown a success message (`passwd: password updated successfully`), and the new password will apply immediately.

If your user has `sudo` permissions, you can change another user's password with `passwd` followed by the user's username. For example, `sudo passwd bob` will allow you to set the user ``bob``'s password, and then some additional optional values for the user such as their name. Just press `Enter` to skip each of these options.

==== Remove a User's Password

You can remove the password for the user `bob` with `sudo passwd bob -d`. Without a password the user will not be able to login to a Terminal. 

NOTE: This is useful for users that need to exist for system reasons, but you don't want it to be possible to login to the account for security reasons.

=== Creating a New User

You can create additional users on your Raspberry Pi OS installation with the `adduser` command.

Enter `sudo adduser bob` and you'll be prompted for a password for the new user `bob`. Leave this blank if you don't want a password.

==== Your Home Folder

When you create a new user, they will have a home folder in `/home/`. The `pi` user's home folder is at `/home/pi/`.

===== The `skel` Command

Upon creating a new user, the contents of `/etc/skel/` will be copied to the new user's home folder. You can add or modify dot-files such as the `.bashrc` in `/etc/skel/` to your requirements, and this version will be applied to new users.

=== Deleting a User

You can delete a user on your system with the command `userdel`. Apply the `-r` flag to remove their home folder too:

[,bash]
----
sudo userdel -r bob
----
