== Raspberry Pi 4 Bootloader Configuration

=== Editing the Configuration

Before editing the bootloader configuration, xref:os.adoc#updating-and-upgrading-raspberry-pi-os[update your system] to get the latest version of the `rpi-eeprom` package.

To view the current EEPROM configuration: +
`rpi-eeprom-config`

To edit it and apply the updates to latest EEPROM release: +
`sudo -E rpi-eeprom-config --edit`

Please see the xref:raspberry-pi.adoc#raspberry-pi-4-boot-eeprom[boot EEPROM] page for more information about the EEPROM update process.

=== Configuration Properties

This section describes all the configuration items available in the bootloader. The syntax is the same as xref:config_txt.adoc[config.txt] but the properties are specific to the bootloader. xref:config_txt.adoc#conditional-filters[Conditional filters] are also supported except for EDID.

[[BOOT_UART]]
==== BOOT_UART

If `1` then enable UART debug output on GPIO 14 and 15. Configure the receiving debug terminal at 115200bps, 8 bits, no parity bits, 1 stop bit.

Default: `0`

[[WAKE_ON_GPIO]]
==== WAKE_ON_GPIO

If `1` then `sudo halt` will run in a lower power mode until either GPIO3 or GLOBAL_EN are shorted to ground.

Default: `1`

[[POWER_OFF_ON_HALT]]
==== POWER_OFF_ON_HALT

If `1` and `WAKE_ON_GPIO=0` then `sudo halt` will switch off all PMIC outputs. This is lowest possible power state for halt but may cause problems with some HATs because 5V will still be on. `GLOBAL_EN` must be shorted to ground to boot.

Raspberry Pi 400 has a dedicated power button which operates even if the processor is switched off. This behaviour is enabled by default, however, `WAKE_ON_GPIO=2` may be set to use an external GPIO power button instead of the dedicated power button.

Default: `0`

[[BOOT_ORDER]]
==== BOOT_ORDER

The `BOOT_ORDER` setting allows flexible configuration for the priority of different boot modes. It is represented as a 32-bit unsigned integer where each nibble represents a boot-mode. The boot modes are attempted in lowest significant nibble to highest significant nibble order.


[discrete]
====== `BOOT_ORDER` fields

The BOOT_ORDER property defines the sequence for the different boot modes. It is read right to left and up to 8 digits may be defined.

|===
| Value | Mode | Description

| 0x0
| SD CARD DETECT
| Try SD then wait for card-detect to indicate that the card has changed - deprecated now that 0xf (RESTART) is available.

| 0x1
| SD CARD
| SD card (or eMMC on Compute Module 4).

| 0x2
| NETWORK
| Network boot - See xref:remote-access.adoc#network-boot-your-raspberry-pi[Network boot server tutorial]

| 0x3
| RPIBOOT
| RPIBOOT - See https://github.com/raspberrypi/usbboot[usbboot]

| 0x4
| USB-MSD
| USB mass storage boot - See xref:raspberry-pi.adoc#usb-mass-storage-boot[USB mass storage boot]

| 0x5
| BCM-USB-MSD
| USB 2.0 boot from USB Type C socket (CM4: USB type A socket on CM4IO board).

| 0x6
| NVME
| CM4 only: boot from an NVMe SSD connected to the PCIe interface. See xref:raspberry-pi.adoc#nvme-ssd-boot[NVMe boot] for more details.

| 0x7
| HTTP
| HTTP boot over ethernet. See xref:raspberry-pi.adoc#http-boot[HTTP boot] for more details.

| 0xe
| STOP
| Stop and display error pattern. A power cycle is required to exit this state.

| 0xf
| RESTART
| Restart from the first boot-mode in the BOOT_ORDER field i.e. loop
|===

`RPIBOOT` is intended for use with Compute Module 4 to load a custom debug image (e.g. a Linux RAM-disk) instead of the normal boot. This should be the last boot option because it does not currently support timeouts or retries.

[discrete]
====== `BOOT_ORDER` examples

|===
| BOOT_ORDER | Description

| 0xf41
| Try SD first, followed by USB-MSD then repeat (default if BOOT_ORDER is empty)

| 0xf14
| Try USB first, followed by SD then repeat

| 0xf21
| Try SD first, followed by NETWORK then repeat
|===

[[MAX_RESTARTS]]
==== MAX_RESTARTS

If the RESTART (`0xf`) boot-mode is encountered more than MAX_RESTARTS times then a watchdog reset is triggered. This isn't recommended for general use but may be useful for test or remote systems where a full reset is needed to resolve issues with hardware or network interfaces.

Default: `-1` (infinite)

[[SD_BOOT_MAX_RETRIES]]
==== SD_BOOT_MAX_RETRIES

The number of times that SD boot will be retried after failure before moving to the next boot-mode defined by `BOOT_ORDER`. +
`-1` means infinite retries.

Default: `0`

[[NET_BOOT_MAX_RETRIES]]
==== NET_BOOT_MAX_RETRIES

The number of times that network boot will be retried after failure before moving to the next boot-mode defined by `BOOT_ORDER`. +
`-1` means infinite retries.

Default: `0`

[[DHCP_TIMEOUT]]
==== DHCP_TIMEOUT

The timeout in milliseconds for the entire DHCP sequence before failing the current iteration.

Minimum: `5000` +
Default: `45000`

[[DHCP_REQ_TIMEOUT]]
==== DHCP_REQ_TIMEOUT

The timeout in milliseconds before retrying DHCP DISCOVER or DHCP REQ.

Minimum: `500` +
Default: `4000`

[[TFTP_FILE_TIMEOUT]]
==== TFTP_FILE_TIMEOUT

The timeout in milliseconds for an individual file download via TFTP.

Minimum: `5000` +
Default: `30000`

[[TFTP_IP]]
==== TFTP_IP

Optional dotted decimal ip address (e.g. `192.168.1.99`) for the TFTP server which overrides the server-ip from the DHCP request. +
This may be useful on home networks because tftpd-hpa can be used instead of dnsmasq where broadband router is the DHCP server.

Default: ""

[[TFTP_PREFIX]]
==== TFTP_PREFIX

In order to support unique TFTP boot directories for each Raspberry Pi the bootloader prefixes the filenames with a device specific directory. If neither start4.elf nor start.elf are found in the prefixed directory then the prefix is cleared.
On earlier models the serial number is used as the prefix, however, on Raspberry Pi 4 the MAC address is no longer generated from the serial number making it difficult to automatically create tftpboot directories on the server by inspecting DHCPDISCOVER packets. To support this the TFTP_PREFIX may be customized to either be the MAC address, a fixed value or the serial number (default).

|===
| Value | Description

| 0
| Use the serial number e.g. `9ffefdef/`

| 1
| Use the string specified by TFTP_PREFIX_STR

| 2
| Use the MAC address e.g. `dc-a6-32-01-36-c2/`
|===

Default: 0

[[TFTP_PREFIX_STR]]
==== TFTP_PREFIX_STR

Specify the custom directory prefix string used when `TFTP_PREFIX` is set to 1. For example:- `TFTP_PREFIX_STR=tftp_test/`

Default: "" +
Max length: 32 characters

[[PXE_OPTION43]]
==== PXE_OPTION43

Overrides the PXE Option43 match string with a different string. It's normally better to apply customisations to the DHCP server than change the client behaviour but this option is provided in case that's not possible.

Default: `Raspberry Pi Boot`

[[DHCP_OPTION97]]
==== DHCP_OPTION97

In earlier releases the client GUID (Option97) was just the serial number repeated 4 times. By default, the new GUID format is
the concatenation of the fourcc for `RPi4` (0x34695052 - little endian), the board revision (e.g. 0x00c03111) (4-bytes), the least significant 4 bytes of the mac address and the 4-byte serial number.
This is intended to be unique but also provide structured information to the DHCP server, allowing Raspberry Pi 4 computers to be identified without relying upon the Ethernet MAC OUID.

Specify DHCP_OPTION97=0 to revert the old behaviour or a non-zero hex-value to specify a custom 4-byte prefix.

Default: `0x34695052`

[[MAC_ADDRESS]]
==== MAC_ADDRESS

Overrides the Raspberry Pi Ethernet MAC address with the given value. e.g. `dc:a6:32:01:36:c2`

Default: ""

[[MAC_ADDRESS_OTP]]
==== MAC_ADDRESS_OTP
Overrides the Raspberry Pi Ethernet MAC address with a value stored in the xref:raspberry-pi.adoc#write-and-read-customer-otp-values[Customer OTP] registers.

For example, to use a MAC address stored in rows 0 and 1 of the `Customer OTP`.
----
MAC_ADDRESS_OTP=0,1
----

The first value (row 0 in the example) contains the OUI and the most significant 8 bits of the MAC address. The second value (row 1 in the example) stores the remaining 16-bits of the MAC address.
This is the same format as used for the Raspberry Pi MAC address programmed at manufacture.

Any two customer rows may be selected and combined in either order. 

The `Customer OTP` rows are OTP registers 36 to 43 in the `vcgencmd otp_dump` output so if the first two rows are programmed as follows then `MAC_ADDRESS_OTP=0,1` would give a MAC address of `e4:5f:01:20:24:7e`.

----
36:247e0000
37:e45f0120
----

Default: ""

==== Static IP address configuration

If TFTP_IP and the following options are set then DHCP is skipped and the static IP configuration is applied. If the TFTP server is on the same subnet as the client then GATEWAY may be omitted.

[[CLIENT_IP]]
===== CLIENT_IP

The IP address of the client e.g. `192.168.0.32`

Default: ""

[[SUBNET]]
===== SUBNET

The subnet address mask e.g. `255.255.255.0`

Default: ""

[[GATEWAY]]
===== GATEWAY

The gateway address to use if the TFTP server is on a different subnet e.g. `192.168.0.1`

Default: ""

[[DISABLE_HDMI]]
==== DISABLE_HDMI

The xref:raspberry-pi.adoc#boot-diagnostics-on-the-raspberry-pi-4[HDMI boot diagnostics] display is disabled if `DISABLE_HDMI=1`. Other non-zero values are reserved for future use.

Default: `0`

[[HDMI_DELAY]]
==== HDMI_DELAY

Skip rendering of the HDMI diagnostics display for up to N seconds (default 5) unless a fatal error occurs. The default behaviour is designed to avoid the bootloader diagnostics screen from briefly appearing during a normal SD / USB boot.

Default: `5`

[[ENABLE_SELF_UPDATE]]
==== ENABLE_SELF_UPDATE

Enables the bootloader to update itself from a TFTP or USB mass storage device (MSD) boot filesystem.

If self update is enabled then the bootloader will look for the update files (.sig/.upd) in the boot file system. If the update image differs from the current image then the update is applied and system is reset. Otherwise, if the EEPROM images are byte-for-byte identical then boot continues as normal.

Notes:-

* Self-update is not enabled in SD boot; the ROM can already load recovery.bin from the SD card.
* Bootloader releases prior to 2021 do not support `self-update`.
* For network boot make sure that the TFTP `boot` directory can be mounted via NFS and that `rpi-eeprom-update` can write to it.

Default: `1`

[[FREEZE_VERSION]]
==== FREEZE_VERSION

Previously this property was only checked by the `rpi-eeprom-update` script. However, now that self-update is enabled the bootloader will also check this property. If set to 1, this overrides `ENABLE_SELF_UPDATE` to stop automatic updates. To disable `FREEZE_VERSION` you will have to use an SD card boot with recovery.bin.

*Custom EEPROM update scripts must also check this flag.*

Default: `0`

[[HTTP_HOST]]
==== HTTP_HOST

If network install or HTTP boot is initiated, `boot.img` and `boot.sig` are downloaded from this server.

Invalid host names will be ignored. They should only contain lower case alphanumeric characters and `-` or `.`.
If `HTTP_HOST` is set then HTTPS is disabled and plain HTTP used instead.
You can specify an IP address to avoid the need for a DNS lookup.
Don`t include the HTTP scheme or any forward slashes in the hostname.

Default: `fw-download-alias1.raspberrypi.com`

[[HTTP_PORT]]
==== HTTP_PORT

You can use this property to change the port used for network install and HTTP boot. HTTPS is enabled when using the default host `fw-download-alias1.raspberrypi.com`. If `HTTP_HOST` is changed then HTTPS is disabled and plain HTTP will be used instead.

When HTTPS is disabled, plain HTTP will still be used even if `HTTP_PORT` is changed to `443`.

Default: `443` if HTTPS is enabled otherwise `80`

[[HTTP_PATH]]
==== HTTP_PATH

The path used for network install and HTTP boot.

The case of the path *is* significant.
Use forward (Linux) slashes for the path separator.
Leading and trailing forward slashes are not required.

If `HTTP_HOST` is not set, `HTTP_PATH` is ignored and the URL will be `\https://fw-download-alias1.raspberrypi.com:443/net_install/boot.img`. If `HTTP_HOST` is set the URL will be `\http://<HTTP_HOST>:<HTTP_PORT>/<HTTP_PATH>/boot.img`

Default: `net_install`

[[IMAGER_REPO_URL]]
==== IMAGER_REPO_URL

The embedded Raspberry Pi Imager application is configured with a json file downloaded at startup.

You can change the URL of the json file used by the embedded Raspberry Pi Imager application to get it to offer your own images.
You can test this with the standard https://www.raspberrypi.com/software/[Raspberry Pi Imager] application by passing the URL via the `--repo` argument.

Default: `\http://downloads.raspberrypi.org/os_list_imagingutility_v3.json`

[[NET_INSTALL_ENABLED]]
==== NET_INSTALL_ENABLED

When network install is enabled, the bootloader displays the network install screen on boot if it detects a keyboard.

To enable network install, add `NET_INSTALL_ENABLED=1`, or to disable network install add `NET_INSTALL_ENABLED=0`.

This setting is ignored and network install is disabled if `DISABLE_HDMI=1` is set.

In order to detect the keyboard, network install must initialise the USB controller and enumerate devices. This increases boot time by approximately 1 second so it may be advantageous to disable network install in some embedded applications.

Default: `1` on Raspberry Pi 4 and Raspberry Pi 400, and `0` on Compute Module 4.

[[NET_INSTALL_KEYBOARD_WAIT]]
==== NET_INSTALL_KEYBOARD_WAIT

If network install is enabled, the bootloader attempts to detect a keyboard and the `SHIFT` key to initiate network install. You can change the length of this wait in milliseconds with this property.

Setting this to `0` disables the keyboard wait, although network install can still be initiated if no boot files are found and USB boot-mode `4` is in `BOOT_ORDER`.

NOTE: Testing suggests keyboard and SHIFT detection takes at least 750ms.

Default: `900`

[[NETCONSOLE]]
==== NETCONSOLE - advanced logging

`NETCONSOLE` duplicates debug messages to the network interface. The IP addresses and ports are defined by the `NETCONSOLE` string.

NOTE: NETCONSOLE blocks until the ethernet link is established or a timeout occurs. The timeout value is `DHCP_TIMEOUT` although DHCP is not attempted unless network boot is requested.

===== Format

See https://wiki.archlinux.org/index.php/Netconsole

----
src_port@src_ip/dev_name,dst_port@dst_ip/dst_mac
E.g. 6665@169.254.1.1/,6666@/
----

In order to simplify parsing, the bootloader requires every field separator to be present. The source ip address must be specified but the following fields may be left blank and assigned default values.

* src_port - 6665
* dev_name - "" (the device name is always ignored)
* dst_port - 6666
* dst_ip - 255.255.255.255
* dst_mac - 00:00:00:00:00

One way to view the data is to connect the test Raspberry Pi 4 to another Raspberry Pi running WireShark and select "`udp.srcport == 6665`" as a filter and select `+Analyze -> Follow -> UDP stream+` to view as an ASCII log.

`NETCONSOLE` should not be enabled by default because it may cause network problems. It can be enabled on demand via a GPIO filter e.g.

----
# Enable debug if GPIO 7 is pulled low
[gpio7=0]
NETCONSOLE=6665@169.254.1.1/,6666@/
----

Default: ""  (not enabled) +
Max length: 32 characters

[[PARTITION]]
==== PARTITION

The `PARTITION` option may be used to specify the boot partition number, if it has not explicitly been set by the `reboot` command (e.g. `sudo reboot N`) or by `boot_partition=N` in `autoboot.txt`.
This could be used to boot from a rescue partition if the user presses a button.
----
# Boot from partition 2 if GPIO 7 is pulled low
[gpio7=0]
PARTITION=2
----

Default: 0

[[USB_MSD_EXCLUDE_VID_PID]]
==== USB_MSD_EXCLUDE_VID_PID

A list of up to 4 VID/PID pairs specifying devices which the bootloader should ignore. If this matches a HUB then the HUB won't be enumerated, causing all downstream devices to be excluded.
This is intended to allow problematic (e.g. very slow to enumerate) devices to be ignored during boot enumeration. This is specific to the bootloader and is not passed to the OS.

The format is a comma-separated list of hexadecimal values with the VID as most significant nibble. Spaces are not allowed.
E.g. `034700a0,a4231234`

Default: ""

[[USB_MSD_DISCOVER_TIMEOUT]]
==== USB_MSD_DISCOVER_TIMEOUT

If no USB mass storage devices are found within this timeout then USB-MSD is stopped and the next boot-mode is selected

Minimum: `5000` (5 seconds) +
Default: `20000` (20 seconds) +

[[USB_MSD_LUN_TIMEOUT]]
==== USB_MSD_LUN_TIMEOUT

How long to wait in milliseconds before advancing to the next LUN e.g. a multi-slot SD-CARD reader. This is still being tweaked but may help speed up boot if old/slow devices are connected as well as a fast USB-MSD device containing the OS.

Minimum: `100` +
Default: `2000` (2 seconds)

[[USB_MSD_PWR_OFF_TIME]]
==== USB_MSD_PWR_OFF_TIME

During USB mass storage boot, power to the USB ports is switched off for a short time to ensure the correct operation of USB mass storage devices. Most devices work correctly using the default setting: change this only if you have problems booting from a particular device. Setting `USB_MSD_PWR_OFF_TIME=0` will prevent power to the USB ports being switched off during USB mass storage boot.

Minimum: `250` +
Maximum: `5000` +
Default: `1000` (1 second)

[[USB_MSD_STARTUP_DELAY]]
==== USB_MSD_STARTUP_DELAY

If defined, delays USB enumeration for the given timeout after the USB host controller has initialised. If a USB hard disk drive takes a long time to initialise and triggers USB timeouts then this delay can be used to give the driver additional time to initialise. It may also be necessary to increase the overall USB timeout (`USB_MSD_DISCOVER_TIMEOUT`).

Minimum: `0` +
Maximum: `30000` (30 seconds) +
Default: `0`

[[VL805]]
==== VL805
Compute Module 4 only.

If the `VL805` property is set to `1` then the bootloader will search for a VL805 PCIe XHCI controller and attempt to initialise it with VL805 firmware embedded in the bootloader EEPROM. This enables industrial designs to use VL805 XHCI controllers without providing a dedicated SPI EEPROM for the VL805 firmware.

* On Compute Module 4 the bootloader never writes to the dedicated VL805 SPI EEPROM. This option just configures the controller to load the firmware from SDRAM.
* Do not use this option if the VL805 XHCI controller has a dedicated EEPROM. It will fail to initialise because the VL805 ROM will attempt to use a dedicated SPI EEPROM if fitted.
* The embedded VL805 firmware assumes the same USB configuration as Raspberry Pi 4B (2 USB 3.0 ports and 4 USB 2.0 ports). There is no support for loading alternate VL805 firmware images, a dedicated VL805 SPI EEPROM should be used instead for such configurations.

Default: `0`

[[XHCI_DEBUG]]
==== XHCI_DEBUG

This property is a bit-field which controls the verbosity of USB debug messages for mass storage boot-mode. Enabling all of these messages generates a huge amount of log data which will slow down booting and may even cause boot to fail. For verbose logs it's best to use `NETCONSOLE`.

|===
| Value | Log

| 0x1
| USB descriptors

| 0x2
| Mass storage mode state machine

| 0x4
| Mass storage mode state machine - verbose

| 0x8
| All USB requests

| 0x10
| Device and hub state machines

| 0x20
| All xHCI TRBs (VERY VERBOSE)

| 0x40
| All xHCI events (VERY VERBOSE)
|===

To combine values, add them together. For example:

----
# Enable mass storage and USB descriptor logging
XHCI_DEBUG=0x3
----

Default: `0x0` (no USB debug messages enabled)

[[config_txt]]
==== config.txt section

After reading `config.txt` the GPU firmware `start4.elf` reads the bootloader EEPROM config and checks for a section called `[config.txt]`. If the `[config.txt]` section exists then the contents from the start of this section to the end of the file is appended in memory, to the contents of the `config.txt` file read from the boot partition.  This can be used to automatically apply settings to every operating system, for example, dtoverlays.

WARNING: If an invalid configuration which causes boot to fail is specified then the bootloader EEPROM will have to be re-flashed.

=== Configuration Properties in `config.txt`

[[boot_ramdisk]]
==== boot_ramdisk
If this property is set to `1` then the bootloader will attempt load a ramdisk file called `boot.img` containing the boot xref:configuration.adoc#boot-folder-contents[boot file-system]. Subsequent files (e.g. `start4.elf`) are read from the ramdisk instead of the original boot file-system.

The primary purpose of `boot_ramdisk` is to support `secure-boot`, however, unsigned `boot.img` files can also be useful to Network Boot or `RPIBOOT` configurations.

* The maximum size for a ramdisk file is 96MB.
* `boot.img` files are raw disk `.img` files. The recommended format is a plain FAT32 partition with no MBR.
* The memory for the ramdisk filesystem is released before the operating system is started.
* If xref:raspberry-pi.adoc#fail-safe-os-updates-tryboot[TRYBOOT] is selected then the bootloader will search for `tryboot.img` instead of `boot.img`.
* See also xref:config_txt.adoc#autoboot-txt[autoboot.txt]

For more information about `secure-boot` and creating `boot.img` files please see https://github.com/raspberrypi/usbboot/blob/master/Readme.md[USBBOOT]

Default: `0`

[[boot_load_flags]]
==== boot_load_flags

Experimental property for custom firmware (bare metal).

Bit 0 (0x1) indicates that the .elf file is custom firmware. This disables any compatibility checks (e.g. is USB MSD boot supported) and resets PCIe before starting the executable.

Default: `0x0`

[[uart_2ndstage]]
==== uart_2ndstage

If `uart_2ndstage` is `1` then enable debug logging to the UART. This option also automatically enables UART logging in `start.elf`. This is also described on the xref:config_txt.adoc#boot-options[Boot options] page.

The `BOOT_UART` property also enables bootloader UART logging but does not enable UART logging in `start.elf` unless `uart_2ndstage=1` is also set.

Default: `0`

[[erase_eeprom]]
==== erase_eeprom

If `erase_eeprom` is set to `1` then `recovery.bin` will erase the entire SPI EEPROM instead of flashing the bootloader image. This property has no effect during a normal boot.

Default: `0`

[[eeprom_write_protect]]
==== eeprom_write_protect

Configures the EEPROM `Write Status Register`. This can be set to either mark the entire EEPROM as write-protected or clear write-protection.

This option must be used in conjunction with the EEPROM `/WP` pin which controls updates to the EEPROM `Write Status Register`.  Pulling `/WP` low (CM4 `EEPROM_nEP` or Pi4B `TP5`) does NOT write-protect the EEPROM unless the `Write Status Register` has also been configured.

See the https://www.winbond.com/resource-files/w25x40cl_f%2020140325.pdf[Winbond W25x40cl datasheet] for further details.

`eeprom_write_protect` settings in `config.txt` for `recovery.bin`.

|===
| Value | Description

| 1
| Configures the write protect regions to cover the entire EEPROM.

| 0
| Clears the write protect regions.

| -1
| Do nothing.
|===

NOTE: `flashrom` does not support clearing of the write-protect regions and will fail to update the EEPROM if write-protect regions are defined.

Default: `-1`

[[bootloader_update]]
==== bootloader_update

This option may be set to 0 to block self-update without requiring the EEPROM configuration to be updated. This is sometimes useful when updating multiple Raspberry Pis via network boot because this option can be controlled per Raspberry Pi (e.g. via a serial number filter in `config.txt`).

Default: `1`

=== Secure Boot configuration properties in `config.txt`
The following `config.txt` properties are used to program the `secure-boot` OTP settings. These changes are irreversible and can only be programmed via `RPIBOOT` when flashing the bootloader EEPROM image.  This ensures that `secure-boot` cannot be set remotely or by accidentally inserting a stale SD card image.

For more information about enabling `secure-boot` please see the https://github.com/raspberrypi/usbboot/blob/master/Readme.md#secure-boot[secure-boot readme] and the https://github.com/raspberrypi/usbboot/blob/master/secure-boot-example/README.md[secure-boot tutorial] in the https://github.com/raspberrypi/usbboot[USBBOOT] repo.

[[program_pubkey]]
==== program_pubkey
If this property is set to `1` then `recovery.bin` will write the hash of the public key in the EEPROM image to OTP.  Once set, the bootloader will reject EEPROM images signed with different RSA keys or unsigned images.

Default: `0`

[[revoke_devkey]]
==== revoke_devkey
If this property is set to `1` then `recovery.bin` will write a value to OTP that prevents the ROM from loading old versions of the second stage bootloader which do not support `secure-boot`. This prevents `secure-boot` from being turned off by reverting to an older release of the bootloader.

Default: `0`

[[program_rpiboot_gpio]]
==== program_rpiboot_gpio
Since there is no dedicated `nRPIBOOT` jumper on Raspberry Pi 4B or Raspberry Pi 400, an alternative GPIO must be used to select `RPIBOOT` mode by pulling the GPIO low. Only one GPIO may be selected and the available options are `2, 4, 5, 7, 8`. This property does not depend on `secure-boot` but please verify that this GPIO configuration does not conflict with any HATs which might pull the GPIO low during boot.

Since for safety this property can only be programmed via `RPIBOOT`, the bootloader EEPROM must first be cleared using `erase_eeprom`. This causes the BCM2711 ROM to failover to `RPIBOOT` mode, which then allows this option to be set.

Default: ``

[[program_jtag_lock]]
==== program_jtag_lock
If this property is set to `1` then `recovery.bin` will program an OTP value that prevents VideoCore JTAG from being used. This option requires that `program_pubkey` and `revoke_devkey` are also set. This option can prevent failure-analysis and should only be set after the device has been fully tested.

Default: `0`

[[bootloader_update_stable]]
=== Updating to the LATEST / STABLE bootloader

The DEFAULT version of the bootloader is only updated for CRITICAL fixes and major releases. The LATEST / STABLE bootloader is updated more often to include the latest fixes and improvements.

Advanced users can switch to the LATEST / STABLE bootloader to get the latest functionality.
Open a command prompt and start `raspi-config`.

----
sudo raspi-config
----

Navigate to `Advanced Options` and then `Bootloader Version`. Select `Latest` and choose `Yes` to confirm. Select `Finish` and confirm you want to reboot. After the reboot, open a command prompt again and update your system.

----
sudo apt update
sudo apt install rpi-eeprom  # Update rpi-eeprom to the latest version
----

If you run `rpi-eeprom-update`, you should see that a more recent version of the bootloader is available and it's the `stable` release.

----
*** UPDATE AVAILABLE ***
BOOTLOADER: update available
   CURRENT: Tue 25 Jan 14:30:41 UTC 2022 (1643121041)
    LATEST: Thu 10 Mar 11:57:12 UTC 2022 (1646913432)
   RELEASE: stable (/lib/firmware/raspberrypi/bootloader/stable)
            Use raspi-config to change the release.
----

Now you can update your bootloader.

----
sudo rpi-eeprom-update -a
sudo reboot
----

If you run `rpi-eeprom-update` again after your Raspberry Pi has rebooted, you should now see that the `CURRENT` date has updated to indicate that you are using the latest version of the bootloader.

----
BOOTLOADER: up to date
   CURRENT: Thu 10 Mar 11:57:12 UTC 2022 (1646913432)
    LATEST: Thu 10 Mar 11:57:12 UTC 2022 (1646913432)
   RELEASE: stable (/lib/firmware/raspberrypi/bootloader/stable)
            Use raspi-config to change the release.
----
