== HTTP boot

The network install feature uses HTTP over Ethernet to boot the Raspberry Pi into embedded xref:getting-started.adoc#raspberry-pi-imager[Raspberry Pi Imager].

In addition to network install, you can explicitly boot your device with files downloaded via HTTP with xref:raspberry-pi.adoc#BOOT_ORDER[boot-mode] `7`. You can still use this even if xref:raspberry-pi.adoc#NET_INSTALL_ENABLED[network install on boot is disabled].

You could, for example, add this to your `BOOT_ORDER` as a fall-back boot method, or put it behind a GPIO conditional to initiate HTTP boot from your own server when a GPIO pin is pulled low.

For example, if you added the following to your EEPROM config and GPIO 8 (which has a default state of 1 or HIGH) were to be pulled low, the files `\http://downloads.raspberrypi.org:80/net_install/boot.img` and `\http://downloads.raspberrypi.org:80/net_install/boot.sig` would be downloaded. If network install on boot were enabled, it would use the same URL. If GPIO 8 were not pulled low the behaviour would be unchanged.
```
[gpio8=0]
BOOT_ORDER=0xf7
HTTP_HOST=downloads.raspberrypi.org
NET_INSTALL_ENABLED=0
```

HTTP in the `BOOT_ORDER` will be ignored if secure boot is enabled and xref:raspberry-pi.adoc#HTTP_HOST[HTTP_HOST] is not set.

=== Requirements

To use HTTP boot, xref:raspberry-pi.adoc#bootloader_update_stable[update the bootloader] to a bootloader dated 10th March 2022 or later. HTTP boot only works over Ethernet, so you need to connect your Raspberry Pi to your network via an Ethernet cable, e.g. to a socket on the back of your router.

=== Keys

All HTTP downloads must be signed. The bootloader includes a public key for the files on the default host `fw-download-alias1.raspberrypi.com`. This key will be used to verify the network install image, _unless_ you set xref:raspberry-pi.adoc#HTTP_HOST[HTTP_HOST] _and_ include a public key in the EEPROM. This allows you to host the Raspberry Pi network install images on your own server.

WARNING: Using your own network install image will require you to sign the image and add your public key to the EEPROM. If you then apply a public EEPROM update, your key will be lost and will need to be re-added.

https://github.com/raspberrypi/usbboot/blob/master/Readme.md[`USBBOOT`] has all the tools needed to program public keys. 

----
# Add your PUBLIC key to the eeprom. boot.conf contains your modifications
rpi-eeprom-config -c boot.conf -p mypubkey.pem -o pieeprom.upd pieeprom.original.bin

# Generate signature for your eeprom
rpi-eeprom-digest -i pieeprom.upd -o pieeprom.sig

# Sign the network install image with your PRIVATE key
# Put boot.img and boot.sig on your web server
rpi-eeprom-digest -i boot.img -o boot.sig -k myprivkey.pem
----

=== Certificates

For security the Network install feature uses HTTPS to download the image from the Raspberry Pi website. It uses our own CA root included in the bootloader so it can verify it's talking to the correct host.

Since the 5th April 2024, 2712 devices have had the ability to add their own custom CA certificate to the eeprom to securely download images from their own web sites. To achieve this, the DER encoded certificate is added with the new `--cacertder` option in the `rpi-eeprom-config` tool.

To ensure that the certificate is not modified, a hash of the certificate must be placed in the eeprom config settings and a key used to guard against tampering.

----
# Generate a DER encoded certificate
openssl x509 -in your_ca_root_cert.pem -out cert.der -outform DER

# generate the hash of the certificate
sha256sum cert.der
701bd97f67b0f5483a9734e6e5cf72f9a123407b346088638f597878563193fc  cert.der
----

Update boot.conf to include the hash of the certificate

----
[all]
BOOT_UART=1
POWER_OFF_ON_HALT=0
BOOT_ORDER=0xf461

[gpio8=0]
BOOT_ORDER=0xf7
NET_INSTALL_ENABLED=0
HTTP_HOST=yourserver.org
HTTP_PATH=path/to/files
HTTP_CACERT_HASH=701bd97f67b0f5483a9734e6e5cf72f9a123407b346088638f597878563193fc
----

NOTE: If `HTTP_CACERT_HASH` is specified it assumes that you want to use HTTPS and changes to use port 443 for the download.

----
# Add everything to the eeprom
../tools/rpi-eeprom-config -c boot.conf -p public_key.pem -o pieeprom.bin --cacertder cert.der pieeprom.original.bin
../tools/rpi-eeprom-digest -k private_key.pem -i pieeprom.bin -o pieeprom.sig
----

On boot it should use HTTPS instead of HTTP.

----
Loading boot.img ...
HTTP: GET request for https://yourserver.org:443/path/to/files/boot.sig
HTTP: GET request for https://yourserver.org:443/path/to/files/boot.img
----

=== Secure boot

If secure boot is enabled, then the Raspberry Pi can only run code signed by the customer's private key. So if you want to use network install or HTTP boot mode with secure boot, you must sign `boot.img` and generate `boot.sig` with your own key and host these files somewhere for download. The public key in the EEPROM will be used to verify the image.

If secure boot is enabled and xref:raspberry-pi.adoc#HTTP_HOST[HTTP_HOST] is not set, then network install and HTTP boot will be disabled.

For more information about secure boot see https://github.com/raspberrypi/usbboot/blob/master/secure-boot-recovery/README.md[`USBBOOT`].
