== NVMe SSD boot

NVMe (Non-Volatile Memory express) is a standard for external storage access over a PCIe bus. You can connect NVMe drives via the PCIe slot on a Compute Module 4 (CM4) IO board or Raspberry Pi 5. With some additional configuration, you can boot from an NVMe drive.

=== Prerequisites

==== Hardware

* NVMe M.2 SSD
* an adapter to convert from PCIe to an M.2 standard.
** For Raspberry Pi 5, we recommend the xref:../accessories/m2-hat-plus.adoc[M.2 HAT+], which converts from the Raspberry Pi's *PCIe FFC* slot to an M Key interface.
** For the CM4, search for a "PCI-E 3.0 ×1 lane to M.2 NGFF M-Key SSD NVMe PCI Express adapter card"

To check that your NVMe drive is connected correctly, boot your Raspberry Pi from another storage device (such as an SD card) and run `ls -l /dev/nvme*`. Example output is shown below.

----
crw------- 1 root root 245, 0 Mar  9 14:58 /dev/nvme0
brw-rw---- 1 root disk 259, 0 Mar  9 14:58 /dev/nvme0n1
----

==== Software

Run the following command to see what firmware you're running:

[source,console]
----
$ sudo rpi-eeprom-update
----

For Raspberry Pi 5, you need firmware released December 6, 2023 or later.

For CM4, NVMe boot support was introduced in July 2021. You need a version of the following software released since that date:

* the bootloader
* VideoCore firmware
* the Raspberry Pi OS Linux kernel

The latest Raspberry Pi OS release has everything you need. Use  xref:getting-started.adoc#raspberry-pi-imager[Raspberry Pi Imager] to install a Raspberry Pi OS image onto your drive.

=== Edit EEPROM boot order

For Raspberry Pi 5, you need to boot Raspberry Pi OS to edit the boot order. You can boot your Raspberry Pi from an SD card or USB drive for this step. The EEPROM configuration persists even when you change the boot device, since the EEPROM configuration is stored on the board itself.

Use the Raspberry Pi Configuration CLI to update the bootloader:

[source,console]
----
$ sudo raspi-config
----

Under `Advanced Options` > `Bootloader Version`, choose `Latest`. Then, exit `raspi-config` with `Finish` or the *Escape* key.

Run the following command to update your firmware to the latest version:

[source,console]
----
$ sudo rpi-eeprom-update -a
----

Then, reboot with `sudo reboot`. Your Raspberry Pi 5 should boot from NVMe.

For CM4, use `rpiboot` to update the bootloader. You can find instructions for building `rpiboot` and configuring the IO board to switch the ROM to usbboot mode in the https://github.com/raspberrypi/usbboot[USB boot GitHub repository].

For versions of CM4 with an eMMC, make sure you have set NVMe first in the boot order. Remember to add the NVMe boot mode `6` to `BOOT_ORDER` in `recovery/boot.conf`.

CM4 Lite automatically boots from NVMe when the SD card slot is empty.

=== NVMe `BOOT_ORDER`

The `BOOT_ORDER` setting in EEPROM configuration controls boot behaviour.
For NVMe boot, use boot mode `6`. For more information, see xref:raspberry-pi.adoc#raspberry-pi-bootloader-configuration[Raspberry Pi bootloader configuration].

=== Example

Below is an example of UART output when the bootloader detects the NVMe drive:

----
Boot mode: SD (01) order f64
Boot mode: USB-MSD (04) order f6
Boot mode: NVME (06) order f
VID 0x144d MN Samsung SSD 970 EVO Plus 250GB
NVME on
----

It will then find a FAT partition and load `start4.elf`:

----
Read start4.elf bytes  2937840 hnd 0x00050287 hash ''
----

It will then load the kernel and boot the OS:

----
MESS:00:00:07.096119:0: brfs: File read: /mfs/sd/kernel8.img
MESS:00:00:07.098682:0: Loading 'kernel8.img' to 0x80000 size 0x1441a00
MESS:00:00:07.146055:0:[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd083]
----

In Linux the SSD appears as `/dev/nvme0` and the "namespace" as `/dev/nvme0n1`. There will be two partitions `/dev/nvme0n1p1` (FAT) and `/dev/nvme0n1p2` (EXT4). Use `lsblk` to check the partition assignments:

----
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
nvme0n1     259:0    0 232.9G  0 disk
├─nvme0n1p1 259:1    0   256M  0 part /boot/firmware
└─nvme0n1p2 259:2    0 232.6G  0 part /
----

=== Troubleshooting

If the boot process fails, please file an issue on the https://github.com/raspberrypi/rpi-eeprom[rpi-eeprom GitHub repository], being sure to attach a copy of the console and anything displayed on the screen during boot.
