== USB Mass Storage Boot

NOTE: Available on Raspberry Pi 2B v1.2, 3A+, 3B, 3B+, 4B, 400 and Zero 2 W, and Raspberry Pi Compute Module 3, 3+ and 4 only.

This page explains how to boot your Raspberry Pi from a USB mass storage device such as a flash drive or a USB hard disk. When attaching USB devices, particularly hard disks and SSDs, be mindful of their power requirements. If you wish to attach more than one SSD or hard disk to the Raspberry Pi, this normally requires external power - either a powered hard disk enclosure, or a powered USB hub. Note that models prior to the Raspberry Pi 4B have known issues which prevent booting with some USB devices.

[[pi4]]
=== Raspberry Pi 4B and Raspberry Pi 400

The bootloader in Raspberry Pi 400 and newer Raspberry Pi 4B boards support USB boot by default, although the `BOOT_ORDER` bootloader configuration may need to be modified. On earlier Raspberry Pi 4B boards, or to select alternate boot modes, the bootloader must be updated.

See:-

* Instructions for changing the boot mode via the xref:raspberry-pi.adoc#imager[Raspberry Pi Imager].
* Instructions for changing the boot mode via the xref:raspberry-pi.adoc#raspi-config[raspi-config].
* The xref:raspberry-pi.adoc#raspberry-pi-4-bootloader-configuration[bootloader configuration] page for other boot configuration options.

[[cm4]]
=== Compute Module 4

Please see the xref:compute-module.adoc#flashing-the-compute-module-emmc[Flashing the Compute Module eMMC] for bootloader update instructions.

=== Raspberry Pi 3B+

The Raspberry Pi 3B+ supports USB mass storage boot out of the box.

=== Raspberry Pi 2B, 3A+, 3B, CM3, CM3+, Zero 2 W

On the Raspberry Pi 2B v1.2, 3A+, 3B, Zero 2 W, and Compute Module 3, 3+ you must first enable xref:raspberry-pi.adoc#usb-host-boot-mode[USB host boot mode]. This is to allow USB mass storage boot, and xref:raspberry-pi.adoc#network-booting[network boot]. Note that network boot is not supported on the Raspberry Pi 3A+ or Zero 2 W.

To enable USB host boot mode, the Raspberry Pi needs to be booted from an SD card with a special option to set the USB host boot mode bit in the one-time programmable (OTP) memory. Once this bit has been set, the SD card is no longer required. 

IMPORTANT: Any change you make to the OTP is permanent and cannot be undone.

NOTE: On the Raspberry Pi 3A+, setting the OTP bit to enable USB host boot mode will permanently prevent that Raspberry Pi from booting in USB device mode.

You can use any SD card running Raspberry Pi OS to program the OTP bit.

Enable USB host boot mode with this code:

[,bash]
----
echo program_usb_boot_mode=1 | sudo tee -a /boot/config.txt
----

This adds `program_usb_boot_mode=1` to the end of `/boot/config.txt`.

Note that although the option is named `program_usb_boot_mode`, it only enables USB _host_ boot mode. USB _device_ boot mode is only available on certain models of Raspberry Pi - see xref:raspberry-pi.adoc#usb-device-boot-mode[USB device boot mode].

The next step is to reboot the Raspberry Pi with `sudo reboot` and check that the OTP has been programmed with:

[,bash]
----
vcgencmd otp_dump | grep 17:
17:3020000a
----

Check that the output `0x3020000a` is shown. If it is not, then the OTP bit has not been successfully programmed. In this case, go through the programming procedure again. If the bit is still not set, this may indicate a fault in the Raspberry Pi hardware itself.

If you wish, you can remove the `program_usb_boot_mode` line from `config.txt`, so that if you put the SD card into another Raspberry Pi, it won't program USB host boot mode. Make sure there is no blank line at the end of `config.txt`.

You can now boot from a USB mass storage device in the same way as booting from an SD card - see the following section for further information.

=== Booting from USB Mass Storage

The xref:getting-started.adoc#installing-the-operating-system[procedure] is the same as for SD cards - simply image the USB storage device with the operating system image.

After preparing the storage device, connect the drive to the Raspberry Pi and power up the Raspberry Pi, being aware of the extra USB power requirements of the external drive.
After five to ten seconds, the Raspberry Pi should begin booting and show the rainbow splash screen on an attached display. Make sure that you do not have an SD card inserted in the Raspberry Pi, since if you do, it will boot from that first.

See the xref:raspberry-pi.adoc#raspberry-pi-boot-modes[bootmodes documentation] for the boot sequence and alternative boot modes (network, USB device, GPIO or SD boot).

=== Known Issues 

IMPORTANT: These do *not* apply to Raspberry Pi 4 Model B.

* The default timeout for checking bootable USB devices is 2 seconds. Some flash drives and hard disks power up too slowly. It is possible to extend this timeout to five seconds (add a new file `timeout` to the SD card), but note that some devices take even longer to respond.
* Some flash drives have a very specific protocol requirement that is not handled by the bootcode and may thus be incompatible.

=== Special `bootcode.bin`-only Boot Mode

IMPORTANT: This does *not* apply to Raspberry Pi 4 Model B.

If you are unable to use a particular USB device to boot your Raspberry Pi, an alternative for the Raspberry Pi 2B v1.2, 3A+, 3B and 3B+ is to use the special xref:raspberry-pi.adoc#raspberry-pi-boot-modes[bootcode.bin-only] boot mode. The Raspberry Pi will still boot from the SD card, but `bootcode.bin` is the only file read from it.

=== Hardware Compatibility

Before attempting to boot from a USB mass storage device it is advisable to verify that the device works correctly under Linux. Boot using an SD card and plug in the USB mass storage device. This should appears as a removable drive. This is especially important with USB SATA adapters which may be supported by the bootloader in mass storage mode but fail if Linux selects https://en.wikipedia.org/wiki/USB_Attached_SCSI[USB Attached SCSI - UAS] mode.  See this https://forums.raspberrypi.com/viewtopic.php?t=245931[forum thread] about UAS and how to add https://www.kernel.org/doc/html/v5.0/admin-guide/kernel-parameters.html[usb-storage.quirks] to workaround this issue.

Spinning hard disk drives nearly always require a powered USB hub. Even if it appears to work, you are likely to encounter intermittent failures without a powered USB HUB.

=== Multiple Bootable Drives

When searching for a bootable partition, the bootloader scans all USB mass storage devices in parallel and will select the first to respond. If the boot partition does not contain a suitable `start.elf` file, the next available device is selected.  There is no method for specifying the boot device according to the USB topology because this would slow down boot and adds unnecessary and hard to support configuration complexity.

NOTE: The `config.txt` file xref:config_txt.adoc#conditional-filters[conditional filters] can be used to select alternate firmware in complex device configurations.
