[[gpio]]
== General Purpose I/O (GPIO)

General Purpose I/O (GPIO) pins can be configured as either general-purpose input, general-purpose output, or as one of up to six special alternate settings, the functions of which are pin-dependent.

There are three GPIO banks on BCM2835. Each of the three banks has its own VDD input pin. On Raspberry Pi, all GPIO banks are supplied from 3.3V. 

WARNING: Connection of a GPIO to a voltage higher than 3.3V will likely destroy the GPIO block within the SoC.

A selection of pins from Bank 0 is available on the P1 header on Raspberry Pi.

=== GPIO Pads

The GPIO connections on the BCM2835 package are sometimes referred to in the peripherals data sheet as "pads" -- a semiconductor design term meaning 'chip connection to outside world'.

The pads are configurable CMOS push-pull output drivers/input buffers. Register-based control settings are available for:

* Internal pull-up / pull-down enable/disable
* Output xref:raspberry-pi.adoc#gpio-pads-control[drive strength]
* Input Schmitt-trigger filtering

==== Power-on states

All GPIO pins revert to general-purpose inputs on power-on reset. The default pull states are also applied, which are detailed in the alternate function table in the ARM peripherals datasheet. Most GPIOs have a default pull applied.

=== Interrupts

Each GPIO pin, when configured as a general-purpose input, can be configured as an interrupt source to the ARM. Several interrupt generation sources are configurable:

* Level-sensitive (high/low)
* Rising/falling edge
* Asynchronous rising/falling edge

Level interrupts maintain the interrupt status until the level has been cleared by system software (e.g. by servicing the attached peripheral generating the interrupt).

The normal rising/falling edge detection has a small amount of synchronisation built into the detection. At the system clock frequency, the pin is sampled with the criteria for generation of an interrupt being a stable transition within a three-cycle window, i.e. a record of '1 0 0' or '0 1 1'. Asynchronous detection bypasses this synchronisation to enable the detection of very narrow events.

=== Alternative Functions

Almost all of the GPIO pins have alternative functions. Peripheral blocks internal to the SoC can be selected to appear on one or more of a set of GPIO pins, for example the I2C buses can be configured to at least 3 separate locations. xref:raspberry-pi.adoc#gpio-pads-control[Pad control], such as drive strength or Schmitt filtering, still applies when the pin is configured as an alternate function.

=== Voltage Specifications

The table below gives the various voltage specifications for the GPIO pins for BCM2835, BCM2836, BCM2837 and RP3A0-based products (e.g. Raspbery Pi Zero or Raspberry Pi 3+). For information about Compute Modules you should see the xref:compute-module.adoc#datasheets-and-schematics[relevant datasheets].

|===
| Symbol | Parameter | Conditions &emsp; | Min | Typical | Max | Unit

| V~IL~
| Input Low Voltage
| -
| -
| -
| 0.9
| V

| V~IH~
| Input high voltage^a^
| -
| 1.6
| -
| -
| V

| I~IL~
| Input leakage current
| TA = +85◦C
| -
| -
| 5
| µA

| C~IN~
| Input capacitance
| -
| -
| 5
| -
| pF

| V~OL~
| Output low voltage^b^
| IOL = -2mA
| -
| -
| 0.14
| V

| V~OH~
| Output high voltage^b^
| IOH = 2mA
| 3.0
| -
| -
| V

| I~OL~
| Output low current^c^
| VO = 0.4V
| 18
| -
| -
| mA

| I~OH~
| Output high current^c^
| VO = 2.3V
| 17
| -
| -
| mA

| R~PU~
| Pullup resistor
| -
| 50
| -
| 65
| kΩ

| R~PD~
| Pulldown resistor
| -
| 50
| -
| 65
| kΩ
|===

^a^ Hysteresis enabled +
^b^ Default drive strength (8mA) +
^c^ Maximum drive strength (16mA)

The table below gives the various voltage specifications for the GPIO pins for BCM2711-based products (e.g. Raspberry Pi 4 and Raspberry Pi 400). For information about Compute Modules you should see the xref:compute-module.adoc#datasheets-and-schematics[relevant datasheets].

|===
| Symbol | Parameter | Conditions &emsp; | Min | Typical | Max | Unit

| V~IL~
| Input Low Voltage
| -
| -
| -
| 0.8
| V

| V~IH~
| Input high voltage^a^
| -
| 2.0
| -
| -
| V

| I~IL~
| Input leakage current
| TA = +85◦C
| -
| -
| 10
| µA

| V~OL~
| Output low voltage^b^
| IOL = -4mA
| -
| -
| 0.4
| V

| V~OH~
| Output high voltage^b^
| IOH = 4mA
| 2.6
| -
| -
| V

| I~OL~
| Output low current^c^
| VO = 0.4V
| 7
| -
| -
| mA

| I~OH~
| Output high current^c^
| VO = 2.6V
| 7
| -
| -
| mA

| R~PU~
| Pullup resistor
| -
| 33
| -
| 73
| kΩ

| R~PD~
| Pulldown resistor
| -
| 33
| -
| 73
| kΩ
|===

^a^ Hysteresis enabled +
^b^ Default drive strength (4mA) +
^c^ Maximum drive strength (8mA)
