== Peripheral Addresses

If there is no kernel driver available, and a program needs to access a peripheral address directly with mmap, it needs to know where in the virtual memory map the peripheral bus segment has been placed. This varies according to which model of Raspberry Pi is being used, so there are three helper functions in https://github.com/raspberrypi/userland/blob/3fd8527eefd8790b4e8393458efc5f94eb21a615/host_applications/linux/libs/bcm_host/bcm_host.c[bcm_host.c] to help provide platform independence.

NOTE: You should use these functions rather than hardcoded values, as this will ensure future compatibility.

----
unsigned bcm_host_get_peripheral_address()
----

This returns the ARM-side physical address where peripherals are mapped.

----
unsigned bcm_host_get_peripheral_size()
----

This returns the size of the peripheral's space.

----
unsigned bcm_host_get_sdram_address()
----

This returns the bus address of the SDRAM.

Here are the current values as of this writing, in table form:

|===
| SoC | Peripheral Address | Peripheral Size | SDRAM Address | Source

| BCM2835
| 0x20000000
| 0x01000000
| 0x40000000
| https://github.com/raspberrypi/linux/blob/7f465f823c2ecbade5877b8bbcb2093a8060cb0e/arch/arm/boot/dts/bcm2835.dtsi#L21[bcm2835.dtsi]

| BCM2836
| 0x3f000000
| 0x01000000
| 0xC0000000
| https://github.com/raspberrypi/linux/blob/7f465f823c2ecbade5877b8bbcb2093a8060cb0e/arch/arm/boot/dts/bcm2836.dtsi#L10[bcm2836.dtsi]

| BCM2837
| 0x3f000000
| 0x01000000
| 0xC0000000
| https://github.com/raspberrypi/linux/blob/7f465f823c2ecbade5877b8bbcb2093a8060cb0e/arch/arm/boot/dts/bcm2837.dtsi#L9[bcm2837.dtsi]

| BCM2711
| 0xfe000000
| 0x01800000
| 0xc0000000
| https://github.com/raspberrypi/linux/blob/7f465f823c2ecbade5877b8bbcb2093a8060cb0e/arch/arm/boot/dts/bcm2711.dtsi#L41[bcm2711.dtsi]
|===

[discrete]
=== Building a C program using these functions

The include file and library are installed by default on a Raspberry Pi OS system. Just add the following line to your C program:

[source,C]
----
#include <bcm_host.h>
----

Example:

[source,C]
----
#include <stdio.h>
#include <bcm_host.h>

int main(void) {
    printf("bcm_host_get_peripheral_address -> 0x%08x\n", bcm_host_get_peripheral_address());
    printf("bcm_host_get_peripheral_size -> 0x%08x\n", bcm_host_get_peripheral_size());
    printf("bcm_host_get_sdram_address -> 0x%08x\n", bcm_host_get_sdram_address());

    return 0;
}
----

Link with:

----
-lbcm_host
----

So a simple command line compile might be:

[,bash]
----
cc myfile.c -I/opt/vc/include -L/opt/vc/lib -lbcm_host -o myfile
----
