== Power Supply

The power supply requirements differ by Raspberry Pi model. All models require a 5.1V supply, but the current required generally increases according to model. All models up to the Raspberry Pi 3 require a micro USB power connector, whilst the Raspberry Pi 4 and Raspberry Pi 400 use a USB-C connector.

Exactly how much current (mA) the Raspberry Pi requires is dependent on what you connect to it. The following table gives various current requirements.

|===
| Product | Recommended PSU current capacity | Maximum total USB peripheral current draw | Typical bare-board active current consumption

| Raspberry Pi 1 Model A
| 700mA
| 500mA
| 200mA

| Raspberry Pi 1 Model B
| 1.2A
| 500mA
| 500mA

| Raspberry Pi 1 Model A+
| 700mA
| 500mA
| 180mA

| Raspberry Pi 1 Model B+
| 1.8A
| 1.2A
| 330mA

| Raspberry Pi 2 Model B
| 1.8A
| 1.2A
| 350mA

| Raspberry Pi 3 Model B
| 2.5A
| 1.2A
| 400mA

| Raspberry Pi 3 Model A+
| 2.5A
| Limited by PSU, board, and connector ratings only.
| 350mA

| Raspberry Pi 3 Model B+
| 2.5A
| 1.2A
| 500mA

| Raspberry Pi 4 Model B
| 3.0A
| 1.2A
| 600mA

| Raspberry Pi 400
| 3.0A
| 1.2A
| 800mA

| Raspberry Pi Zero
| 1.2A
| Limited by PSU, board, and connector ratings only
| 100mA

| Raspberry Pi Zero W
| 1.2A
| Limited by PSU, board, and connector ratings only.
| 150mA

| Raspberry Pi Zero 2 W
| 2A
| Limited by PSU, board, and connector ratings only.
| 350mA
|===

Raspberry Pi have developed their own power supplies for use with all models. These are reliable, use heavy gauge wires and are reasonably priced.

For Raspberry Pi 0-3, we recommend our https://www.raspberrypi.com/products/micro-usb-power-supply/[2.5A micro USB Supply]. For Raspberry Pi 4 and Raspberry Pi 400, we recommend our https://www.raspberrypi.com/products/type-c-power-supply/[3A USB-C Supply].

If you need to connect a USB device that will take the power requirements above the values specified in the table above, then you must connect it using an externally-powered USB hub. 

=== Typical Power Requirements

The specific power requirements of each model are shown below.

|===
| Product | Recommended PSU current capacity | Maximum total USB peripheral current draw | Typical bare-board active current consumption 

|Raspberry Pi 1 Model A | 700mA | 500mA | 200mA 
| Raspberry Pi 1 Model B |1.2A | 500mA | 500mA 
| Raspberry Pi 1 Model A+ | 700mA | 500mA | 180mA
| Raspberry Pi 1 Model B+ | 1.8A | 1.2A | 330mA 
| Raspberry Pi 2 Model B | 1.8A | 1.2A | 350mA 
| Raspberry Pi 3 Model B | 2.5A | 1.2A | 400mA 
| Raspberry Pi 3 Model A+ | 2.5A | Limited by PSU, board, and connector ratings only. | 350mA 
| Raspberry Pi 3 Model B+ | 2.5A | 1.2A | 500mA 
| Raspberry Pi 4 Model B | 3.0A | 1.2A | 600mA 
| Raspberry Pi 400       | 3.0A | 1.2A | 800mA 
| Raspberry Pi Zero | 1.2A | Limited by PSU, board, and connector ratings only | 100mA 
| Raspberry Pi Zero W | 1.2A | Limited by PSU, board, and connector ratings only.| 150mA 
| Raspberry Pi Zero 2 W | 2A | Limited by PSU, board, and connector ratings only | 350mA
|===

From the Raspberry Pi B+ onwards, 1.2A is supplied to downstream USB peripherals. This allows the vast majority of USB devices to be connected directly to these models, assuming the upstream power supply has sufficient available current.

Very high-current devices, or devices which can draw a surge current such as certain modems and USB hard disks, will still require an external powered USB hub. The power requirements of the Raspberry Pi increase as you make use of the various interfaces on the Raspberry Pi. The GPIO pins can draw 50mA safely (note that that means 50mA distributed across all the pins: an individual GPIO pin can only safely draw 16mA), the HDMI port uses 50mA, the Camera Module requires 250mA, and keyboards and mice can take as little as 100mA or as much as 1000mA! Check the power rating of the devices you plan to connect to the Raspberry Pi and purchase a power supply accordingly. If you're not sure, we would advise you to buy a powered USB hub.

This is the typical amount of power (in Ampere) drawn by different Raspberry Pi models during standard processes:

|===
| | | Raspberry Pi 1B+ | Raspberry Pi 2B | Raspberry Pi 3B | Raspberry Pi Zero | Raspberry Pi 4B 
| Boot | Max |0.26 | 0.40| 0.75| 0.20 | 0.85 
| | Avg | 0.22 | 0.22 | 0.35 | 0.15 | 0.7 
| Idle |Avg | 0.20 | 0.22 | 0.30 | 0.10 | 0.6 
| Video playback (H.264) | Max | 0.30 | 0.36 |0.55 |0.23 | 0.85 
| | Avg | 0.22 | 0.28 | 0.33 | 0.16 | 0.78 
| Stress | Max | 0.35 | 0.82 | 1.34 | 0.35 | 1.25 
| | Avg | 0.32 | 0.75 | 0.85 | 0.23 | 1.2 
| Halt current | | | | 0.10 | 0.055 | 0.023 
|===

NOTE: For these measurements we used a standard Raspberry Pi OS image (current as of 26 Feb 2016, or June 2019 for the Raspberry Pi 4), at room temperature, with the Raspberry Pi connected to a HDMI monitor, USB keyboard, and USB mouse. The Raspberry Pi 3 Model B was connected to a wireless LAN access point, the Raspberry Pi 4 was connected to Ethernet. All these power measurements are approximate and do not take into account power consumption from additional USB devices; power consumption can easily exceed these measurements if multiple additional USB devices or a HAT are connected to the Raspberry Pi.

=== Power Supply Warnings

On all models of Raspberry Pi since the Raspberry Pi B+ (2014) except the Zero range, there is low-voltage detection circuitry that will detect if the supply voltage drops below 4.63V (+/- 5%). This will result in a xref:configuration.adoc#firmware-warning-icons[warning icon] being displayed on all attached displays and an entry being added to the kernel log.

If you are seeing warnings, you should improve the power supply and/or cable, as low power can cause problems with corruption of SD cards, or erratic behaviour of the Raspberry Pi itself; for example, unexplained crashes.

Voltages can drop for a variety of reasons, for example if the power supply itself is inadequate, the power supply cable is made of too thin wires, or you have plugged in high demand USB devices.

=== Back-powering

The USB specification requires that USB devices must not supply current to upstream devices. If a USB device does supply current to an upstream device then this is called back-powering. Often this happens when a badly-made powered USB hub is connected, and will result in the powered USB hub supplying power to the host Raspberry Pi. This is not recommended since the power being supplied to the Raspberry Pi via the hub will bypass the protection circuitry built into the Raspberry Pi, leaving it vulnerable to damage in the event of a power surge.
