== Product compliance and safety

All Raspberry Pi products have undergone extensive compliance testing, for more information see the https://pip.raspberrypi.com[Product Information Portal]

=== Flammability Rating

The PCBs used in Raspberry Pi devices adhere to UL94-V0. 

NOTE: This applies to the PCBs *only*.

=== The Raspberry Pi Compliance Support

The Compliance Support programme is designed to eliminate the burden of navigating compliance issues and make it easier for companies to bring new products to consumers. It provides access to the same test engineers who worked on our Raspberry Pis during their compliance testing, connecting the user to a dedicated team at https://www.ul-certification.com/[UL] who assess and test the user's product, facilitated by their in-depth knowledge of Raspberry Pi.

Find out more about the https://www.raspberrypi.com/for-industry/integrator-programme/[Raspberry Pi Compliance Support Programme].

=== Powered by Raspberry Pi

The Powered by Raspberry Pi progamme provides a process for companies wanting to use a form of the Raspberry Pi logo, and covers products with Raspberry Pi computers or silicon inside, and services provided by a Raspberry Pi. If you wish to start the process to apply you can do so https://www.raspberrypi.com/trademark-rules/powered-raspberry-pi/[online].

=== Approved Design Partners

Our list of https://www.raspberrypi.com/for-industry/design-partners/[approved design partners] provide a  set of consultancies that we work closely with and support so they can provide paid for design services across hardware, software, and mechanical.

[.whitepaper, title="Fleet management - A brief introduction", subtitle="", link=https://pip.raspberrypi.com/categories/685-whitepapers-app-notes/documents/RP-003609-WP/Fleet-management-A-brief-introduction.pdf]
****
The sheer range of applications that the Raspberry Pi devices are suitable for means any one company may have hundreds, thousands, or even tens of thousands of devices in their portfolio. All these devices need to be maintained and, as numbers increase, manual checking becomes extremely inefficient. This is where fleet management software comes into play.

Raspberry Pi do not provide any sort of fleet management software, this is an area where there is a plethora of existing suppliers. This whitepaper attempts to show what these suppliers can do, and also provides a brief introduction to some that Raspberry Pi know work with Raspberry Pi devices.

Please note that these are NOT recommendations; Raspberry Pi have not done any deep investigations into any of these products, simply ensured that Raspberry Pi devices are supported. It is down to the individual to ensure that any product or service matches their use case. Please also note that any suppliers listed are not the only suppliers of services that may be appropriate, i.e. the list is not exhaustive.
****