== Install tools

To use the Debug Probe, install the following tools.

=== Install OpenOCD

You need to install OpenOCD.

To install OpenOCD, run the following command in a terminal:

[source,console]
----
$ sudo apt install openocd
----

To run OpenOCD, use the `openocd` command in your terminal.

==== Install OpenOCD on macOS

First, install the https://brew.sh/[Homebrew] package manager:

[source,console]
----
$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
----

To install OpenOCD on macOS, run the following commands:

[source,console]
----
$ brew install openocd
----

To run OpenOCD, use the `openocd` command in your terminal.

=== Install GDB

We also need to install the GNU debugger (GDB).

==== Linux

Install `gdb-multiarch`:

[source,console]
----
$ sudo apt install gdb-multiarch
----

==== macOS

Run the following command to install `gdb`:

[source,console]
----
$ brew install gdb
----

You can safely ignore the request for "special privileges" messages on installation.

IMPORTANT: GDB does not support `gdb` Arm-based Macs. Instead, either https://gist.github.com/m0sys/711d0ec5e52102c6ba44451caf38bd38[install `gdb` from source] or use `lldb` instead of `gdb`. There is https://inbox.sourceware.org/gdb/3185c3b8-8a91-4beb-a5d5-9db6afb93713@Spark/[no official support] from the developers for running GDB on Arm-based Macs. Support for GDB can be found on the https://inbox.sourceware.org/gdb/[GDB mailing list] on Sourceware.org. `lldb` is installed as part of the Xcode Command Line Tools.

==== MS Windows

GDB is available as part of our https://github.com/raspberrypi/pico-setup-windows/releases/latest[Pico setup for Windows installer]. It is also included in the https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads[Arm GNU Toolchain Downloads].

Alternatively information about manual installation can be found in Chapter 9 and Appendix A of our https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf[Getting Started with Raspberry Pi Pico] book. 

NOTE: Manual installation of GDB on Windows is not recommended.
