== Install tools

To use the Debug Probe, install the following tools.

=== Install OpenOCD

You need to install OpenOCD.

To install OpenOCD, run the following command in a terminal:

[source,console]
----
$ sudo apt install openocd
----

To run OpenOCD, use the `openocd` command in your terminal.

==== Install OpenOCD on macOS

First, install the https://brew.sh/[Homebrew] package manager:

[source,console]
----
$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
----

To install OpenOCD on macOS, run the following commands:

[source,console]
----
$ brew install openocd
----

To run OpenOCD, use the `openocd` command in your terminal.

=== Install GDB

We also need to install the GNU debugger (GDB).

==== Linux

Install `gdb-multiarch`:

[source,console]
----
$ sudo apt install gdb-multiarch
----

==== macOS

Run the following command to install `gdb`:

[source,console]
----
$ brew install arm-none-eabi-gdb
----

You can safely ignore the request for "special privileges" messages on installation.

==== MS Windows

GDB is available as part of our https://github.com/raspberrypi/pico-setup-windows/releases/latest[Pico setup for Windows installer]. It is also included in the https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads[Arm GNU Toolchain Downloads].

Alternatively information about manual installation can be found in Chapter 9 and Appendix A of our https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf[Getting Started with Raspberry Pi Pico] book. 

NOTE: Manual installation of GDB on Windows is not recommended.
