[[building]]
== Building the Kernel

The default compilers and linkers that come with an OS are configured to build executables to run on that OS - they are native tools - but that doesn't have to be the case. A cross-compiler is configured to build code for a target other than the one running the build process, and using it is called cross-compilation.

Cross-compilation of the Raspberry Pi kernel is useful for two reasons:

* it allows a 64-bit kernel to be built using a 32-bit OS, and vice versa, and
* even a modest laptop can cross-compile a Raspberry Pi kernel significantly faster than the Raspberry Pi itself.

The instructions below are divided into native builds and cross-compilation; choose the section appropriate for your situation - although there are many common steps between the two, there are also some important differences.

=== Building the Kernel Locally

On a Raspberry Pi, first install the latest version of https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-32-bit[Raspberry Pi OS]. Then boot your Raspberry Pi, log in, and ensure you're connected to the internet to give you access to the sources.

First install Git and the build dependencies:

[,bash]
----
sudo apt install git bc bison flex libssl-dev make
----

Next get the sources, which will take some time:

[,bash]
----
git clone --depth=1 https://github.com/raspberrypi/linux
----

[[choosing_sources]]
==== Choosing Sources

The `git clone` command above will download the current active branch (the one we are building Raspberry Pi OS images from) without any history. Omitting the `--depth=1` will download the entire repository, including the full history of all branches, but this takes much longer and occupies much more storage.

To download a different branch (again with no history), use the `--branch` option:

[,bash]
----
git clone --depth=1 --branch <branch> https://github.com/raspberrypi/linux
----

where `<branch>` is the name of the branch that you wish to download.

Refer to the https://github.com/raspberrypi/linux[original GitHub repository] for information about the available branches.

==== Kernel Configuration

Configure the kernel; as well as the default configuration, you may wish to xref:linux_kernel.adoc#configuring-the-kernel[configure your kernel in more detail] or xref:linux_kernel.adoc#patching-the-kernel[apply patches from another source], to add or remove required functionality.

[[default_configuration]]
===== Apply the Default Configuration

First, prepare the default configuration by running the following commands, depending on your Raspberry Pi model:

For Raspberry Pi 1, Zero and Zero W, and Raspberry Pi Compute Module 1 default (32-bit only) build configuration

[,bash]
----
cd linux
KERNEL=kernel
make bcmrpi_defconfig
----

For Raspberry Pi 2, 3, 3+ and Zero 2 W, and Raspberry Pi Compute Modules 3 and 3+ default 32-bit build configuration

[,bash]
----
cd linux
KERNEL=kernel7
make bcm2709_defconfig
----

For Raspberry Pi 4 and 400, and Raspberry Pi Compute Module 4 default 32-bit build configuration

[,bash]
----
cd linux
KERNEL=kernel7l
make bcm2711_defconfig
----

For Raspberry Pi 3, 3+, 4, 400 and Zero 2 W, and Raspberry Pi Compute Modules 3, 3+ and 4 default 64-bit build configuration
[,bash]
----
cd linux
KERNEL=kernel8
make bcm2711_defconfig
----

===== Customising the Kernel Version Using `LOCALVERSION`

In addition to your kernel configuration changes, you may wish to adjust the `LOCALVERSION` to ensure your new kernel does not receive the same version string as the upstream kernel. This both clarifies you are running your own kernel in the output of `uname` and ensures existing modules in `/lib/modules` are not overwritten.

To do so, change the following line in `.config`:

----
CONFIG_LOCALVERSION="-v7l-MY_CUSTOM_KERNEL"
----

You can also change that setting graphically as shown in xref:linux_kernel.adoc#configuring-the-kernel[the kernel configuration instructions]. It is located in "General setup" \=> "Local version - append to kernel release".

==== Building the Kernel

Build and install the kernel, modules, and Device Tree blobs; this step can take a *long* time depending on the Raspberry Pi model in use.  For the 32-bit kernel:

[,bash]
----
make -j4 zImage modules dtbs
sudo make modules_install
sudo cp arch/arm/boot/dts/*.dtb /boot/
sudo cp arch/arm/boot/dts/overlays/*.dtb* /boot/overlays/
sudo cp arch/arm/boot/dts/overlays/README /boot/overlays/
sudo cp arch/arm/boot/zImage /boot/$KERNEL.img
----

For the 64-bit kernel:

[,bash]
----
make -j4 Image.gz modules dtbs
sudo make modules_install
sudo cp arch/arm64/boot/dts/broadcom/*.dtb /boot/
sudo cp arch/arm64/boot/dts/overlays/*.dtb* /boot/overlays/
sudo cp arch/arm64/boot/dts/overlays/README /boot/overlays/
sudo cp arch/arm64/boot/Image.gz /boot/$KERNEL.img
----

NOTE: On a Raspberry Pi 2/3/4, the `-j4` flag splits the work between all four cores, speeding up compilation significantly.

If you now reboot, your Raspberry Pi should be running your freshly-compiled kernel!

=== Cross-Compiling the Kernel

First, you will need a suitable Linux cross-compilation host. We tend to use Ubuntu; since Raspberry Pi OS is also a Debian distribution, it means many aspects are similar, such as the command lines.

You can either do this using VirtualBox (or VMWare) on Windows, or install it directly onto your computer. For reference, you can follow instructions online http://www.wikihow.com/Install-Ubuntu-on-VirtualBox[at Wikihow].

==== Install Required Dependencies and Toolchain

To build the sources for cross-compilation, make sure you have the dependencies needed on your machine by executing:

[,bash]
----
sudo apt install git bc bison flex libssl-dev make libc6-dev libncurses5-dev
----

If you find you need other things, please submit a pull request to change the documentation.

===== Install the 32-bit Toolchain for a 32-bit Kernel

[,bash]
----
sudo apt install crossbuild-essential-armhf
----

===== Install the 64-bit Toolchain for a 64-bit Kernel

[,bash]
----
sudo apt install crossbuild-essential-arm64
----

==== Get the Kernel Sources

To download the minimal source tree for the current branch, run:

[,bash]
----
git clone --depth=1 https://github.com/raspberrypi/linux
----

See <<choosing_sources,*Choosing sources*>> above for instructions on how to choose a different branch.

==== Build sources

Enter the following commands to build the sources and Device Tree files:

===== 32-bit Configs

For Raspberry Pi 1, Zero and Zero W, and Raspberry Pi Compute Module 1:

[,bash]
----
cd linux
KERNEL=kernel
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcmrpi_defconfig
----

For Raspberry Pi 2, 3, 3+ and Zero 2 W, and Raspberry Pi Compute Modules 3 and 3+:

[,bash]
----
cd linux
KERNEL=kernel7
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcm2709_defconfig
----

For Raspberry Pi 4 and 400, and Raspberry Pi Compute Module 4:

[,bash]
----
cd linux
KERNEL=kernel7l
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcm2711_defconfig
----

===== 64-bit Configs

For Raspberry Pi 3, 3+, 4, 400 and Zero 2 W, and Raspberry Pi Compute Modules 3, 3+ and 4:

[,bash]
----
cd linux
KERNEL=kernel8
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bcm2711_defconfig
----

===== Build with Configs

NOTE: To speed up compilation on multiprocessor systems, and get some improvement on single processor ones, use `-j n`, where n is the number of processors * 1.5. You can use the `nproc` command to see how many processors you have. Alternatively, feel free to experiment and see what works!

====== For all 32-bit Builds

[,bash]
----
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- zImage modules dtbs
----

====== For all 64-bit Builds

NOTE: Note the difference between Image target between 32 and 64-bit.

[,bash]
----
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- Image modules dtbs
----

==== Install Directly onto the SD Card

Having built the kernel, you need to copy it onto your Raspberry Pi and install the modules; this is best done directly using an SD card reader.

First, use `lsblk` before and after plugging in your SD card to identify it. You should end up with something a lot like this:

----
sdb
   sdb1
   sdb2
----

with `sdb1` being the `FAT` filesystem (boot) partition, and `sdb2` being the `ext4` filesystem (root) partition.

Mount these first, adjusting the partition letter as necessary:

[,bash]
----
mkdir mnt
mkdir mnt/fat32
mkdir mnt/ext4
sudo mount /dev/sdb1 mnt/fat32
sudo mount /dev/sdb2 mnt/ext4
----

NOTE: You should adjust the drive letter appropriately for your setup, e.g. if your SD card appears as `/dev/sdc` instead of `/dev/sdb`.

Next, install the kernel modules onto the SD card:

===== For 32-bit

[,bash]
----
sudo env PATH=$PATH make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- INSTALL_MOD_PATH=mnt/ext4 modules_install
----

===== For 64-bit

[,bash]
----
sudo env PATH=$PATH make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- INSTALL_MOD_PATH=mnt/ext4 modules_install
----

Finally, copy the kernel and Device Tree blobs onto the SD card, making sure to back up your old kernel:

===== For 32-bit

[,bash]
----
sudo cp mnt/fat32/$KERNEL.img mnt/fat32/$KERNEL-backup.img
sudo cp arch/arm/boot/zImage mnt/fat32/$KERNEL.img
sudo cp arch/arm/boot/dts/*.dtb mnt/fat32/
sudo cp arch/arm/boot/dts/overlays/*.dtb* mnt/fat32/overlays/
sudo cp arch/arm/boot/dts/overlays/README mnt/fat32/overlays/
sudo umount mnt/fat32
sudo umount mnt/ext4
----

===== For 64-bit

[,bash]
----
sudo cp mnt/fat32/$KERNEL.img mnt/fat32/$KERNEL-backup.img
sudo cp arch/arm64/boot/Image mnt/fat32/$KERNEL.img
sudo cp arch/arm64/boot/dts/broadcom/*.dtb mnt/fat32/
sudo cp arch/arm64/boot/dts/overlays/*.dtb* mnt/fat32/overlays/
sudo cp arch/arm64/boot/dts/overlays/README mnt/fat32/overlays/
sudo umount mnt/fat32
sudo umount mnt/ext4
----

Another option is to copy the kernel into the same place, but with a different filename - for instance, `kernel-myconfig.img` - rather than overwriting the `kernel.img` file. You can then edit the `config.txt` file to select the kernel that the Raspberry Pi will boot:

----
kernel=kernel-myconfig.img
----

This has the advantage of keeping your custom kernel separate from the stock kernel image managed by the system and any automatic update tools, and allowing you to easily revert to a stock kernel in the event that your kernel cannot boot.

Finally, plug the card into the Raspberry Pi and boot it!
