[[building]]
== Build the kernel

The default compilers and linkers distributed with an OS are configured to build executables to run on that OS. **Cross-compilation** is the process of building code for a target other than the one running the build process.

Cross-compilation of the Raspberry Pi kernel allows you to build a 64-bit kernel from a 32-bit OS, and vice versa. Alternatively, you can cross-compile a 32-bit or 64-bit Raspberry Pi kernel from a device other than a Raspberry Pi.

[NOTE]
====
The 32-bit distribution of Raspberry Pi OS on a Raspberry Pi 4B, 5, 400, Compute Module 4, or Compute Module 4S uses a 32-bit userland, but a _64-bit kernel_. To build a 32-bit kernel, set `ARCH=arm`. To boot a 32-bit kernel, set `arm_64bit=0` in `config.txt`.
====

The instructions below are divided into native builds and cross-compilation. Choose the section appropriate for your situation; although the two processes share many steps, there are also some important differences.

=== Native builds

On a Raspberry Pi, install the latest version of xref:os.adoc[Raspberry Pi OS]. Boot your Raspberry Pi, log in, and connect to the Internet.

First, install Git and the build dependencies:

[source,console]
----
$ sudo apt install git bc bison flex libssl-dev make
----

==== Download kernel source

Next, download the source code for the latest Raspberry Pi kernel:

[source,console]
----
$ git clone --depth=1 https://github.com/raspberrypi/linux
----

This can take several minutes.

[TIP]
====
The `git clone` command above downloads the current active branch, which we build Raspberry Pi OS images from, without any history. Omit `--depth=1` to download the entire repository, including the full history of all branches. This takes much longer and occupies much more storage.

To download a different branch with no history, add the `--branch` option to the command above, replacing `<branch>` with the name of the branch you wish to download:

[source,console]
----
$ git clone --depth=1 --branch <branch> https://github.com/raspberrypi/linux
----

For a full list of available branches, see the https://github.com/raspberrypi/linux[the Raspberry Pi kernel repository].
====

==== Apply configuration

[TIP]
====
This section describes how to apply the default configuration when you build a kernel. You can also configure your kernel in the following ways:

* xref:linux_kernel.adoc#configure-the-kernel[enable and disable kernel features]
* xref:linux_kernel.adoc#patch-the-kernel[apply patches from another source]
====

To prepare the default configuration, run the appropriate commands from the table below for your Raspberry Pi model.

[cols="1,2a,6a"]
|===
| Architecture | Model | Command

.14+^.^| 32-bit
| Raspberry Pi 1
.4+.^|
[source,console]
----
$ cd linux
$ KERNEL=kernel
$ make bcmrpi_defconfig
----
| Raspberry Pi Zero
| Raspberry Pi Zero W
| Raspberry Pi Compute Module 1


| Raspberry Pi 2
.6+.^|
[source,console]
----
$ cd linux
$ KERNEL=kernel7
$ make bcm2709_defconfig
----
| Raspberry Pi 3
| Raspberry Pi 3+
| Raspberry Pi Zero 2 W
| Raspberry Pi Compute Module 3
| Raspberry Pi Compute Module 3+


| Raspberry Pi 4
.4+.^|
[source,console]
----
$ cd linux
$ KERNEL=kernel7l
$ make bcm2711_defconfig
----
| Raspberry Pi 400
| Raspberry Pi Compute Module 4S
| Raspberry Pi Compute Module 4


.10+^.^| 64-bit
| Raspberry Pi 3
.9+.^|
[source,console]
----
$ cd linux
$ KERNEL=kernel8
$ make bcm2711_defconfig
----
| Raspberry Pi 3+
| Raspberry Pi 4
| Raspberry Pi 400
| Raspberry Pi Zero 2 W
| Raspberry Pi Compute Module 3
| Raspberry Pi Compute Module 3+
| Raspberry Pi Compute Module 4S
| Raspberry Pi Compute Module 4


| Raspberry Pi 5
.1+.^|
[source,console]
----
$ cd linux
$ KERNEL=kernel_2712
$ make bcm2712_defconfig
----
|===

===== Customise the kernel version using `LOCALVERSION`

Adjust `LOCALVERSION` to clarify that you are running your own kernel in the output of `uname` and prevent the kernel from overwriting existing modules in `/lib/modules`.

To adjust `LOCALVERSION`, change the following line in `.config`:

[source,ini]
----
CONFIG_LOCALVERSION="-v7l-MY_CUSTOM_KERNEL"
----

You can also change this setting graphically with `menuconfig` at *General setup* > *Local version - append to kernel release*. For more information about `menuconfig`, see xref:linux_kernel.adoc#configure-the-kernel[the kernel configuration instructions].

==== Build and install the kernel natively

Next, build and install the kernel, modules, and Device Tree blobs into the boot partition of your Raspberry Pi. This step can take a long time depending on the Raspberry Pi model you are using.

TIP: If you don't want to install the freshly-compiled kernel onto the Raspberry Pi where you run this command, copy the compiled kernel to the boot partition of a separate boot media instead of `/boot/firmware/`.

To build and install the 64-bit kernel, run the following commands:

[source,console]
----
$ make -j4 Image.gz modules dtbs
$ sudo make modules_install
$ sudo cp arch/arm64/boot/dts/broadcom/*.dtb /boot/firmware/
$ sudo cp arch/arm64/boot/dts/overlays/*.dtb* /boot/firmware/overlays/
$ sudo cp arch/arm64/boot/dts/overlays/README /boot/firmware/overlays/
$ sudo cp arch/arm64/boot/Image.gz /boot/firmware/$KERNEL.img
----

To build the 32-bit kernel:

. Run the following commands to build the modules and Device tree blobs:
+
[source,console]
----
$ make -j4 zImage modules dtbs
$ sudo make modules_install
----

. Depending on your kernel version, run the following command:
  * For kernels up to version 6.4:
+
[source,console]
----
$ sudo cp arch/arm/boot/dts/*.dtb /boot/firmware/
----
* For kernels version 6.5 and above:
+
[source,console]
----
$ sudo cp arch/arm/boot/dts/broadcom/*.dtb /boot/firmware/
----
. Finally, copy over the overlays, README, and image:
+
[source,console]
----
$ sudo cp arch/arm/boot/dts/overlays/*.dtb* /boot/firmware/overlays/
$ sudo cp arch/arm/boot/dts/overlays/README /boot/firmware/overlays/
$ sudo cp arch/arm/boot/zImage /boot/firmware/$KERNEL.img
----

TIP: On multi-core Raspberry Pi models, the `-j <n>` option distributes work between cores. This can speed up compilation significantly. Run `nproc` to see how many processors you have; we recommend passing a number 1.5x your number of processors.

Run the following command to reboot your Raspberry Pi and run your freshly-compiled kernel:

[source,console]
----
$ sudo reboot
----

=== Cross-compiled builds

First, you will need a suitable Linux cross-compilation host. We tend to use Ubuntu; since Raspberry Pi OS is also a Debian distribution, compilation commands are similar.

==== Install required dependencies and toolchain

To build the sources for cross-compilation, install the required dependencies onto your device. Run the following command to install most dependencies:

[source,console]
----
$ sudo apt install git bc bison flex libssl-dev make libc6-dev libncurses5-dev
----

Then, install the proper toolchain for the kernel architecture you wish to build:

* To install the 64-bit toolchain to build a 64-bit kernel, run the following command:
+
[source,console]
----
$ sudo apt install crossbuild-essential-arm64
----

* To install the 32-bit toolchain to build a 32-bit kernel, run the following command:
+
[source,console]
----
$ sudo apt install crossbuild-essential-armhf
----

==== Download kernel source

Next, download the source code for the latest Raspberry Pi kernel:

[source,console]
----
$ git clone --depth=1 https://github.com/raspberrypi/linux
----

This can take several minutes.

[TIP]
====
The `git clone` command above downloads the current active branch, which we build Raspberry Pi OS images from, without any history. Omit `--depth=1` to download the entire repository, including the full history of all branches. This takes much longer and occupies much more storage.

To download a different branch with no history, add the `--branch` option to the command above, replacing `<branch>` with the name of the branch you wish to download:

[source,console]
----
$ git clone --depth=1 --branch <branch> https://github.com/raspberrypi/linux
----

For a full list of available branches, see the https://github.com/raspberrypi/linux[the Raspberry Pi kernel repository].
====

==== Build sources

Enter the following commands to build the sources and Device Tree files:

[cols="1,2a,6a"]
|===
| Target Architecture | Model | Command

.14+^.^| 32-bit

| Raspberry Pi 1
.4+.^| [source,console]
----
$ cd linux
$ KERNEL=kernel
$ make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcmrpi_defconfig
----
| Raspberry Pi Zero
| Raspberry Pi Zero W
| Raspberry Pi Compute Module 1

| Raspberry Pi 2
.6+.^|
[source,console]
----
$ cd linux
$ KERNEL=kernel7
$ make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcm2709_defconfig
----
| Raspberry Pi 3
| Raspberry Pi 3+
| Raspberry Pi Zero 2 W
| Raspberry Pi Compute Module 3
| Raspberry Pi 3+:

| Raspberry Pi 4
.4+.^|
[source,console]
----
$ cd linux
$ KERNEL=kernel7l
$ make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcm2711_defconfig
----
| Raspberry Pi 400
| Raspberry Pi Compute Module 4
| Raspberry Pi Compute Module 4S


.8+^.^| 64-bit
| Raspberry Pi 3
.8+.^| [source,console]
----
$ cd linux
$ KERNEL=kernel8
$ make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bcm2711_defconfig
----
| Raspberry Pi 3+
| Raspberry Pi 4
| Raspberry Pi 400
| Raspberry Pi Zero 2 W
| Raspberry Pi Compute Modules 3
| Raspberry Pi Compute Module 4
| Raspberry Pi Compute Module 4S

| Raspberry Pi 5
.1+.^|
[source,console]
----
$ cd linux
$ KERNEL=kernel_2712
$ make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bcm2712_defconfig
----
|===

==== Build with modules and Device Tree

For 64-bit kernels, pass the image modules and DTB files like so:

[source,console]
----
$ make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- Image modules dtbs
----

For 32-bit kernels, pass the image modules and DTB files like so, prefixing each image module with `z`:

[source,console]
----
$ make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- zImage modules dtbs
----

==== Install the kernel

Having built the kernel, you need to copy it onto your Raspberry Pi boot media (likely an SD card or SSD) and install the modules.

First, run `lsblk`. Then, connect your boot media. Run `lsblk` again; the new device represents your boot media. You should see output similar to the following:

----
sdb
   sdb1
   sdb2
----

If `sdb` represents your boot media, `sdb1` represents the the `FAT32`-formatted **boot partition** and `sdb2` represents the (likely `ext4`-formatted) **root partition**.

First, mount these partitions as `/mnt/boot` and `/mnt/root`, adjusting the partition letter to match the location of your boot media:

[source,console]
----
$ mkdir mnt
$ mkdir mnt/boot
$ mkdir mnt/root
$ sudo mount /dev/sdb1 mnt/boot
$ sudo mount /dev/sdb2 mnt/root
----

Next, install the kernel modules onto the boot media:

* For 64-bit kernels:
+
[source,console]
----
$ sudo env PATH=$PATH make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- INSTALL_MOD_PATH=mnt/root modules_install
----

* For 32-bit kernels:
+
[source,console]
----
$ sudo env PATH=$PATH make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- INSTALL_MOD_PATH=mnt/root modules_install
----

Next, build and install the kernel, modules, and Device Tree blobs into the boot partition, backing up your original kernel.

* To build and install the 64-bit kernel image, overlays, README, and unmount the partitions, run the following commands:
+
[source,console]
----
$ sudo cp mnt/boot/$KERNEL.img mnt/boot/$KERNEL-backup.img
$ sudo cp arch/arm64/boot/Image mnt/boot/$KERNEL.img
$ sudo cp arch/arm64/boot/dts/broadcom/*.dtb mnt/boot/
$ sudo cp arch/arm64/boot/dts/overlays/*.dtb* mnt/boot/overlays/
$ sudo cp arch/arm64/boot/dts/overlays/README mnt/boot/overlays/
$ sudo umount mnt/boot
$ sudo umount mnt/root
----

* To build the 32-bit kernel:
+
. Run the following commands to build the modules and Device tree blobs:
+
[source,console]
----
$ sudo cp mnt/boot/$KERNEL.img mnt/boot/$KERNEL-backup.img
$ sudo cp arch/arm/boot/zImage mnt/boot/$KERNEL.img
----

. Depending on your kernel version, run the following command:
  * For kernels up to version 6.4:
+
[source,console]
----
$ sudo cp arch/arm/boot/dts/*.dtb mnt/boot/
----
* For kernels version 6.5 and above:
+
[source,console]
----
$ sudo cp arch/arm/boot/dts/broadcom/*.dtb mnt/boot/
----
. Finally, copy over the overlays, README, and image, and unmount the partitions:
+
[source,console]
----
$ sudo cp arch/arm/boot/dts/overlays/*.dtb* mnt/boot/overlays/
$ sudo cp arch/arm/boot/dts/overlays/README mnt/boot/overlays/
$ sudo umount mnt/boot
$ sudo umount mnt/root
----

TIP: On multi-core Raspberry Pi models, the `-j <n>` option distributes work between cores. This can speed up compilation significantly. Run `nproc` to see how many processors you have; we recommend passing a number 1.5x your number of processors.

[TIP]
====
Alternatively, copy the kernel with a different filename (e.g. `kernel-myconfig.img`) instead of overwriting the `kernel.img` file. Then, edit `config.txt` in the boot partition to select your kernel:

[source,ini]
----
kernel=kernel-myconfig.img
----

This has the advantage of keeping your custom kernel separate from the stock kernel image managed by the system. With this arrangement, you can quickly revert to a stock kernel in the event that your kernel cannot boot.
====

Connect the boot media to your Raspberry Pi and connect it to power to run your freshly-compiled kernel:

[source,console]
----
$ sudo reboot
----
