== Kernel headers

To compile a kernel module, you need the Linux kernel headers. These provide the function and structure definitions required to compile code that interfaces with the kernel.

If you cloned the entire kernel from GitHub, the headers are already included in the source tree. If you don't need all the extra files, you can instead install only the kernel headers with `apt`.

TIP: When a new kernel is released, you need the headers that match that kernel version. It can take several weeks to update the `apt` package to reflect the latest kernel version. For the latest header versions, xref:linux_kernel.adoc#building[clone the kernel].

If you use a 64-bit version of Raspberry Pi OS, run the following command to install the kernel headers:

[source,console]
----
$ sudo apt install linux-headers-rpi-v8
----

If you use a 32-bit version of Raspberry Pi OS, run the following command to install the kernel headers:

[source,console]
----
$ sudo apt install linux-headers-rpi-{v6,v7,v7l}
----

If you choose to build your own kernel, add the `deb-pkg` target to the build command.

NOTE: Raspberry Pi doesn't test or support using the  `deb-pkg` target. If you choose this approach, proceed with caution.

[source,console]
----
$ make -j6 Image.gz modules dtbs deb-pkg
----

This command generates three `.deb` files in the parent directory of the kernel source. If the kernel is cross-compiled, copy the `linux-headers-{version}.deb` file to your board, then run the following command to install:

[source,console]
----
$ sudo dpkg -i linux-headers-*.deb
----

NOTE: Installation can take several minutes. There is no progress indicator.
