== Patching the kernel

When xref:linux_kernel.adoc#building[building] your custom kernel you may wish to apply patches, or collections of patches (patchsets), to the Linux kernel.

Patchsets are often provided with newer hardware as a temporary measure, before the patches are applied to the upstream (mainline) Linux kernel and then propagated down to the Raspberry Pi kernel sources. However, patchsets for other purposes exist, for instance to enable a fully preemptible kernel for real-time usage.

=== Version identification

It's important to check what version of the kernel you have when downloading and applying patches. In a kernel source directory, running `head Makefile -n 3` will show you the version the sources relate to:

[source]
----
VERSION = 6
PATCHLEVEL = 1
SUBLEVEL = 38
----

In this instance, the sources are for a 6.1.38 kernel. You can see what version you're running on your system with the `uname -r` command.

=== Applying patches

How you apply patches depends on the format in which the patches are made available. Most patches are a single file, and are applied with the `patch` utility. To download and patch our example kernel version with the real-time kernel patches:

[,bash]
----
 wget https://www.kernel.org/pub/linux/kernel/projects/rt/6.1/patch-6.1.38-rt13-rc1.patch.gz
 gunzip patch-6.1.38-rt13-rc1.patch.gz
 cat patch-6.1.38-rt13-rc1.patch | patch -p1
----

In our example we simply download the file, uncompress it, and then pass it to the `patch` utility using the `cat` tool and a Unix pipe.

Some patchsets come as mailbox-format patchsets, arranged as a folder of patch files. We can use Git to apply these patches to our kernel, but first we must configure Git to let it know who we are when we make these changes:

[,bash]
----
 git config --global user.name "Your name"
 git config --global user.email "your email in here"
----

Once we've done this we can apply the patches:

[,bash]
----
 git am -3 /path/to/patches/*
----

If in doubt, consult with the distributor of the patches, who should tell you how to apply them. Some patchsets will require a specific commit to patch against; follow the details provided by the patch distributor.
