== BCM2712

Broadcom BCM2712 is the 16nm application processor used in Raspberry Pi 5, 500, 500+, and Compute Module 5. It is the successor to the BCM2711 device used in Raspberry Pi 4, and shares many common architectural features with other devices in the BCM27xx family, used on earlier Raspberry Pi products.

Built around a quad-core Arm Cortex-A76 CPU cluster, clocked at up to 2.4 GHz, with 512 kB per-core L2 caches and a 2 MB shared L3 cache, it integrates an improved 12-core VideoCore VII GPU; a hardware video scaler and HDMI controller capable of driving dual 4Kp60 displays; and a Raspberry Pi-developed HEVC decoder and Image Signal Processor. A 32-bit LPDDR4X memory interface provides up to 17 GB/s of memory bandwidth, while ×1 and ×4 PCI Express interfaces support high-bandwidth external peripherals; on Raspberry Pi 5 the latter is used to connect to the Raspberry Pi RP1 south bridge, which provides the bulk of the external-facing I/O functionality on the platform.

Headline features include:

* Quad-core Arm Cortex-A76 @ 2.4 GHz
** Armv8-A ISA
** 64 kByte I and D caches
** 512 kB L2 per core, 2 MB shared L3
* New Raspberry Pi-developed ISP
** 1 gigapixel/sec
* Improved HVS and display pipeline
** Dual 4Kp60 support
* VideoCore V3D VII
** ~2-2.5× faster (more hardware, 960 MHz versus 500 MHz on Pi 4)
** OpenGL ES 3.1, Vulkan 1.3
* 4Kp60 HEVC hardware decode
** Other CODECs run in software
** H264 1080p24 decode ~10–20% of CPU
** H264 1080p60 decode ~50–60% of CPU
** H264 1080p30 encode (from ISP) ~30–40% CPU

In aggregate, the new features present in BCM2712 deliver a performance uplift of 2-3× over Raspberry Pi 4 for common CPU or I/O-intensive use cases.

=== Vulnerabilities and mitigations

The Cortex-A76 CPU used in the BCM2712 SoC has known vulnerabilities that are all mitigated in Raspberry Pi OS.

To determine the full list of vulnerabilities and the mitigations, you can use the following command line which will list all those in place.

```bash
$ lscpu | grep Vulnerability | grep -v "Not affected"
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; CSV2, BHB
```

WARNING: The list above was correct as of April 2025 but may have been superseded. You should use `lscpu` on your Raspberry Pi to get up to date information. This is especially important when using a third-party operating system, as these may not include all the latest mitigations in their Linux kernel builds. The Arm processors used by Raspberry Pi Ltd do not use microcode, so all mitigations are at the kernel level.

The vulnerability information reported by `lscpu` is based on the currently executing kernel's detection scheme. It may not accurately reflect the true vulnerability status of the hardware, especially if the OS lacks recent kernel updates. Further vulnerability information on the CPU vendor advisories can be obtained from https://developer.arm.com/Arm%20Security%20Center/Speculative%20Processor%20Vulnerability referencing the Vendor ID and Model name reported by `lscpu`.
