[[introduction]]

Raspberry Pi OS is the official operating system (OS) for Raspberry Pi computers and is free. We recommend Raspberry Pi OS for most Raspberry Pi use cases.

Raspberry Pi OS is based on the *Debian* Linux distribution and supports over 69,000 Debian packages. Raspberry Pi follows a staggered version of the https://wiki.debian.org/DebianReleases[Debian release cycle]. Releases happen roughly once every two years. The latest version of Raspberry Pi OS is based on https://www.raspberrypi.com/news/trixie-the-new-version-of-raspberry-pi-os/[Debian Trixie]. The previous version was based on https://www.raspberrypi.com/news/bookworm-the-new-version-of-raspberry-pi-os/[Debian Bookworm].

== OS installation

Raspberry Pi OS is installed using Raspberry Pi Imager, available for Windows, Mac, and Linux. For instructions, see xref:../computers/getting-started.adoc#imager-install[Install using Imager]. You can also download a disk image (ready-to-use file) of Raspberry Pi OS directly from http://raspberrypi.com/software/operating-systems[our website] and then write it to an SD card to start using your Raspberry Pi.

If you're running a previous version of *Raspberry Pi OS* and want to use the latest major version, don't perform an in-place update (updating the current system without reinstalling). Instead, start again by installing a new image of Raspberry Pi OS. For instructions, see xref:../computers/getting-started.adoc#imager-install[Install using Imager].

WARNING: Back up any important files from your old OS that you don't want to lose. Installing a new OS overwrites everything on the SD card.

=== Editions
Raspberry Pi OS comes in three editions:

* *Raspberry Pi OS* (desktop with basic software) is the recommended edition offered in Raspberry Pi Imager. It provides a graphical desktop environment and includes applications such as Chromium and Firefox web browsers, VLC media player, and the Thonny Python environment.
* *Raspberry Pi OS Full* (desktop with basic software and recommended applications), provides the same graphical desktop environment and applications as the default *Raspberry Pi OS* edition, but also includes the LibreOffice suite, KiCad, a Scratch programming environment, and many other applications.
* *Raspberry Pi OS Lite* (a command-line-only version without a graphical desktop). This edition is useful for headless servers, embedded systems, or older Raspberry Pi models, such as the original Raspberry Pi, Raspberry Pi 2, and Raspberry Pi Zero.

=== Architecture
Raspberry Pi OS is available in both 64-bit and 32-bit versions. Choose the version that best matches your Raspberry Pi's hardware:

* The *64-bit* version is designed for newer Raspberry Pi models that have 64-bit processors, like Raspberry Pi 3, 4, and 5. It can run both 64-bit and 32-bit software, but can also handle more memory (RAM) and is faster for tasks that require more computing power.
* The *32-bit* version is designed for older Raspberry Pi models that have 32-bit processors, like the original Raspberry Pi, Raspberry Pi 2, and Raspberry Pi Zero. It uses less memory and might be more compatible with older software and hardware.