== Installing Images on Mac OS

xref:getting-started.adoc#using-raspberry-pi-imager[Raspberry Pi Imager] is the recommended option for most users to write images to SD cards. However, if you do not want to use the Imager you can still copy an operating system to the card from the command line.

[discrete]
==== Finding the SD Card

Insert the SD card in the slot, or connect the SD card reader with the SD card inside, and type `diskutil list` at the command line. You should see something like this,

[source,bash]
----
  /dev/disk0 (internal):
      #:                       TYPE NAME                    SIZE       IDENTIFIER
      0:                       GUID_partition_scheme        500.3 GB   disk0
      1:                       EFI EFI                      314.6 MB   disk0s1
      2:                       Apple_APFS Container disk1   500.0 GB   disk0s2

  /dev/disk1 (synthesized):
      #:                       TYPE NAME                    SIZE       IDENTIFIER
      0:                       APFS Container Scheme -      +500.0 GB   disk1
                               Physical Store disk0s2
      1:                       APFS Volume Macintosh HD     89.6 GB    disk1s1
      2:                       APFS Volume Preboot          47.3 MB    disk1s2
      3:                       APFS Volume Recovery         510.4 MB   disk1s3
      4:                       APFS Volume VM               3.6 GB     disk1s4

  /dev/disk2 (external, physical):
      #:                       TYPE NAME                    SIZE       IDENTIFIER
      0:                       FDisk_partition_scheme       *15.9 GB    disk2
      1:                       Windows_FAT_32 boot          268.4 MB   disk2s1
      2:                       Linux                        15.7 GB    disk2s2
----

Here the SD Card is `/dev/disk2` however your disk and partition list may vary.

[discrete]
==== Copying the Image

WARNING: Using the `dd` command line tool can overwrite your Mac's operating system if you specify the wrong disk device. If you're not sure about what to do, we recommend you use the https://www.raspberrypi.com/software/[Raspberry Pi Imager] tool.

Before copying the image you should unmount the SD Card.

[source,bash]
----
diskutil unmountDisk /dev/diskN
----

You can then copy the image,

[source,bash]
----
sudo dd bs=1m if=path_of_your_image.img of=/dev/rdiskN; sync
----

replacing `N` with the disk number.

NOTE: You should use `rdisk` (which stands for 'raw disk') instead of `disk`, this speeds up the copying.

This can take a few minutes, depending on the image file size. You can check the progress by pressing `Ctrl+T`. After the `dd` command finishes, you can eject the card:

[source,bash]
----
sudo diskutil eject /dev/rdiskN
----

[discrete]
==== Troubleshooting

* If the command reports `dd: /dev/rdiskN: Resource busy`, you need to unmount the volume first `sudo diskutil unmountDisk /dev/diskN`.

* If the command reports `dd: bs: illegal numeric value`, change the block size `bs=1m` to `bs=1M`.

* If the command reports `dd: /dev/rdiskN: Operation not permitted`, go to `System Preferences` \-> `Security & Privacy` \-> `Privacy` \-> `Files and Folders` \-> `Give Removable Volumes access to Terminal`.

* If the command reports `dd: /dev/rdiskN: Permission denied`, the partition table of the SD card is being protected against being overwritten by mac OS. 
+
Erase the SD card's partition table using this command:
+
[source,bash]
----
sudo diskutil partitionDisk /dev/diskN 1 MBR "Free Space" "%noformat%" 100%
----
+
That command will also set the permissions on the device to allow writing. 
