=== Getting Started

==== Using the camera for the first time

When running a Raspberry Pi OS based on _Bullseye_ or later, the 5 basic `libcamera-apps` are already installed. In this case, official Raspberry Pi cameras will also be detected and enabled automatically.

You can check that everything is working by entering:

[,bash]
----
libcamera-hello
----

You should see a camera preview window for about 5 seconds.

Normally there is nothing further to do, but if you do need to alter the configuration of your Raspberry Pi, please consult the next section.

NOTE: Pi 3 and older devices may not by default be using the correct display driver. Refer to the `/boot/config.txt` file and ensure that either `dtoverlay=vc4-fkms-v3d` or `dtoverlay=vc4-kms-v3d` is currently active. Please reboot if you needed to change this.

==== If you do need to alter the configuration

You may need to alter the camera configuration in your `/boot/config.txt` file if:

* You are using a 3rd party camera (the manufacturer's instructions should explain the changes you need to make).

* You are using an official Raspberry Pi camera but wish to use a non-standard driver/overlay.

* You are using an older version (_Buster_ or earlier) of the operating system (in which case we would recommend upgrading first if this is possible).

TIP: You can find out what operating system version you have by entering `cat /etc/os-release` and checking (among others) the `VERSION` field. Note that _Buster_ is version 10 and _Bullseye_ is version 11.

If you do need to add your own `dtoverlay`, the following are currently recognised.

|===
| Camera Module | In `/boot/config.txt`

| V1 camera (OV5647)
| `dtoverlay=ov5647`

| V2 camera (IMX219)
| `dtoverlay=imx219`

| HQ camera (IMX477)
| `dtoverlay=imx477`

| IMX290 and IMX327
| `dtoverlay=imx290,clock-frequency=74250000` or `dtoverlay=imx290,clock-frequency=37125000` (both modules share the imx290 kernel driver; please refer to instructions from the module vendor for the correct frequency)

| IMX378
| `dtoverlay=imx378`

| OV9281
| `dtoverlay=ov9281`
|===

Please also delete the entry

`camera_auto_detect=1`

if present (or change the `1` to `0`).

If you need to edit this file then the Pi will need to be rebooted.
