== Overview of Raspberry Pi Audio
 
With our audio boards, you will be able to bring high quality audio to your existing Hi-Fi or Raspberry Pi based equipment and projects. We offer four different HAT (Hardware Attached on Top) options that will fit any Raspberry Pi using the 40-pin GPIO header.

Each board has a specific purpose and set of features. The highest audio quality playback is available from our DAC PRO, DAC{plus} and DigiAMP{plus} boards which support up to Full HD Audio (192kHz), while the Codec Zero supports up to HD Audio (96kHz) and includes a built-in microphone, making it ideal for smaller projects.

=== Features at a glance
[cols="2,1,1,1,1,1,1,1,1,1"]
|===
| | *Line Out* | *Balanced Out* | *Stereo Speakers* | *Mono Speaker* | *Headphones* | *Aux In* | *Aux Out* | *Ext Mic* | *Built-in Mic*

| DAC Pro ^| ✓ ^| ✓ | | ^| ✓ | | | | 
| DAC{plus} ^| ✓ | | | ^| ✓ | | | | 
| DigiAmp{plus} | | ^| ✓ | | | | | | 
| Codec Zero | | | ^| ✓ | ^| ✓ ^| ✓ ^| ✓ ^| ✓ 
|===

Line Out:: A double Phono/RCA connector - Normally red and white in colour. This output is a variable
analogue signal (0..2V RMS) and can connect to your existing Hi-Fi (pre-amp or amplifier) or can be used
to drive active speakers (with their own amplifier built in).
Balanced Out:: An XLR connector - Normally a 3 pin male connector. This is used in a studio set-up and some
high-end Hi-Fi systems. It can also be used to drive active “monitor” speakers as used at discos or on
stage directed towards the DJ or performers. 
Stereo Speakers:: 2 sets of screw terminals for 2 x 25W speakers. These are for normal Hi-Fi speakers such as bookshelf or floor
standing. These are known as passive speakers.
Mono Speaker:: Screw terminal for single 1.2W speaker, as found in a transistor radio or similar.
Headphones:: 3.5mm jack socket delivering stereo audio for a set of normal headphones. Our headphone amplifiers on the DAC boards can drive up to 80/90ohm impedance headphones. The headphone output of the Codec+ is also aux out.
Aux In:: A double Phono/RCA connector or 3.5mm socket. Accepts analogue audio in up to 1V RMS. This can be used to record audio from a variable analogue source such as a mobile phone, MP3 player or similar.
Aux Out:: A double Phono/RCA connector or 3.5mm socket. Delivers analogue audio out up to 1V RMS. This can be used to feed audio into an amplifier at a reduced volume compared to Line Out.
Mic In:: A 3.5mm socket for use with an external Electret microphone. The built-in MEMS microphone on the Codec Zero is automatically disabled when the External Mic In connector is used.
