== Overview of Raspberry Pi Audio
 
Introducing our range of boards designed to bring high quality audio to your existing Hi-Fi or Raspberry Pi based equipment and projects.

With 4 different boards to choose from all our audio boards will fit any Raspberry Pi utilising a 40-pin GPIO header.

Each board has a specific purpose and set of features. The highest audio quality playback is from our DAC PRO, DAC{plus} and DigiAMP{plus} boards which support up to Full HD Audio (192kHz) whilst the Codec Zero supports up to HD Audio (96kHz) and includes a built-in microphone - perfect for those smaller projects.

=== Features at a glance

|===
| {set:cellbgcolor:#FFFFFF} | {set:cellbgcolor:#cd2355} *Line Out (RCA)* | *Balanced Out (XLR)* | *Stereo Speakers* | *Mono Speaker* | *Headphones* | *Aux In 1vRMS* | *Aux Out 1vRMS* | *Ext Mic* | *Built-in Mic*

| {set:cellbgcolor:#cd2355} DAC Pro | {set:cellbgcolor:#FFFFFF} ✓ | ✓ | | | ✓ | | | | 
| {set:cellbgcolor:#cd2355} DAC{plus} | {set:cellbgcolor:#FFFFFF} ✓ | | | | ✓ | | | | 
| {set:cellbgcolor:#cd2355} DigiAmp{plus} | {set:cellbgcolor:#FFFFFF} | | ✓ | | | | | | 
| {set:cellbgcolor:#cd2355} Codec Zero | {set:cellbgcolor:#FFFFFF} | | | ✓ | | ✓ | ✓ | ✓ | ✓ 
|===

Line Out:: A double Phono/RCA connector - Normally red and white in colour. This output is a variable
analogue signal (0..2vRMS) and can connect to your existing Hi-Fi (pre-amp or amplifier) or can be used
to drive active speakers (with their own amplifier built in).
Balanced Out:: An XLR connector - Normally a 3 pin male connector. This is used in studio and some
high-end Hi-Fi systems. It can also be used to drive active “monitor” speakers as used at discos or on
stage directed towards the DJ or performers. 
STEREO Speakers:: 2 sets of screw terminals for 2 x 25W speakers. These are for normal Hi-Fi speakers such as bookshelf or floor
standing. These are known as passive speakers.
MONO Speaker:: Screw terminal for single 1.2W speaker, as found in a transistor radio or similar.
Headphones:: 3.5mm jack socket delivering stereo audio for a set of normal headphones. Our headphone amplifiers on the DAC boards can drive up to 80/90ohm impedance headphones. The headphone output of the Codec+ is also aux out.
Aux In:: A double Phono/RCA connector or 3.5mm socket. Accepts analogue audio in up to 1vRMS. This can be used to record audio from a variable analogue source such as a mobile phone, MP3 player or similar.
Aux Out:: A double Phono/RCA connector or 3.5mm socket. Delivers analogue audio out up to 1vRMS. This can be used to feed audio into an amplifier at a reduced volume compared to Line Out.
Mic In:: A 3.5mm socket for use with an external Electret microphone. As the Codec Zero has a built in MEMS microphone this is disabled when the external Mic In is used.
