== Samba (SMB/CIFS)

Samba is an implementation of the SMB/CIFS networking protocol that is used by Microsoft Windows devices to provide shared access to files, printers, and serial ports.

You can use Samba to mount a folder shared from a Windows machine so it appears on your Raspberry Pi, or to share a folder from your Raspberry Pi so it can be accessed by your Windows machine.

=== Installing Samba Support

By default, Raspberry Pi OS does not include CIFS/Samba support, but this can be added. The following commands will install all the required components for using Samba as a server or a client.

[,bash]
----
sudo apt update
sudo apt install samba samba-common-bin smbclient cifs-utils
----

=== Mount a Folder Shared from Windows

First, you need to share a folder on your Windows device. This is quite a convoluted process!

==== Turn on sharing

. Open the Networking and Sharing Centre by right-clicking on the system tray and selecting it
. Click on *Change advanced sharing settings*
. Select *Turn on network discovery*
. Select *Turn on file and printer sharing*
. Save changes

==== Share the folder

You can share any folder you want, but for this example, simply create a folder called `share`.

. Create the folder `share` on your desktop.
. Right-click on the new folder, and select *Properties*.
. Click on the *Sharing* tab, and then the *Advanced Sharing* button
. Select *Share this folder*; by default, the share name is the name of the folder
. Click on the *Permissions* button
. For this example, select *Everyone* and *Full Control* (you can limit access to specific users if required); click *OK* when done, then *OK* again to leave the *Advanced Sharing* page
. Click on the *Security* tab, as we now need to configure the same permissions
. Select the same settings as the *Permissions* tab, adding the chosen user if necessary
. Click *OK*

The folder should now be shared.

==== Windows 10 Sharing Wizard

On Windows 10 there is a Sharing Wizard that helps with some of these steps.

. Run the Computer Management application from the Start Bar
. Select *Shared Folders*, then *Shares*
. Right-click and select *New Share*, which will start up the Sharing Wizard; click *Next*
. Select the folder you wish to share, and click *Next*
. Click *Next* to use all the sharing defaults
. Select *Custom* and set the required permissions, and click *OK*, then *Finish*

==== Mount the folder on the Raspberry Pi

*Mounting* in Linux is the process of attaching a folder to a location, so firstly we need that location.

[,bash]
----
mkdir windowshare
----

Now, we need to mount the remote folder to that location. The remote folder is the host name or IP address of the Windows PC, and the share name used when sharing it. We also need to provide the Windows username that will be used to access the remote machine.

[,bash]
----
sudo mount.cifs //<hostname or IP address>/share /home/pi/windowshare -o user=<name>
----

You should now be able to view the content of the Windows share on your Raspberry Pi.

[,bash]
----
cd windowshare
ls
----

==== "Host is down" error

This error is caused by a combination of two things: A SMB protocol version mismatch, and the CIFS client on Linux returning a misleading error message. In order to fix this a version entry needs to be added to the mount command. By default Raspberry Pi OS will only use versions 2.1 and above, which are compatible with Windows 7 and later. Older devices, including some NAS, may require version 1.0:

----
sudo mount.cifs //IP/share /mnt/point -o user=<uname>,vers=1.0
----

You may need to try different versions to match up with the server version. Possible values are:

|===
| Version | Description

| 1.0
| Classic CIFS/SMBv1 protocol

| 2.0
| The SMBv2.002 protocol. Windows Vista Service Pack 1, and Windows Server 2008

| 2.1
| The SMBv2.1 protocol. Microsoft Windows 7 and Windows Server 2008R2

| 3.0
| The SMBv3.0 protocol.  Microsoft Windows 8 and Windows Server 2012

| 3.02
| The SMBv3.0.2 protocol. Microsoft Windows 8.1 and Windows Server 2012R2

| 3.11
| The SMBv3.1.1 protocol. Microsoft Windows 10 and Windows Server 2016

| 3
| The SMBv3.0 protocol version and above
|===

=== Sharing a Folder from your Raspberry Pi

Firstly, create a folder to share. This example creates a folder called `shared` in the `home` folder of the current user, and  assumes the current user is `pi`.

[,bash]
----
cd ~
mkdir shared
chmod 0740 shared
----

Now we need to tell Samba that there is a `pi` user when accessing that folder. When asked, enter the password of the `pi` user - this can be the default password, but that is well known and should be changed for better security.

[,bash]
----
sudo smbpasswd -a pi
----

Now we need to tell Samba to share this folder, using the Samba configuration file.

[,bash]
----
sudo nano /etc/samba/smb.conf
----

At the end of the file, add the following to share the folder, giving the remote user read/write permissions:

----
[share]
    path = /home/pi/shared
    read only = no
    public = yes
    writable = yes
----

In the same file, find the `workgroup` line, and if necessary, change it to the name of the workgroup of your local Windows network.

[,bash]
----
workgroup = <your workgroup name here>
----

That should be enough to share the folder. On your Windows device, when you browse the network, the folder should appear and you should be able to connect to it.
