== Secure Shell from Linux or Mac OS

You can use SSH to connect to your Raspberry Pi from a Linux desktop, another Raspberry Pi, or from an Apple Mac without installing additional software.

Open a terminal window on your computer replacing `<IP>` with the IP address of the Raspberry Pi you're trying to connect to,

----
ssh pi@<IP>
----

When the connection works you will see a security/authenticity warning. Type `yes` to continue. You will only see this warning the first time you connect.

NOTE: If you receive a `connection timed out` error it is likely that you have entered the wrong IP address for the Raspberry Pi.

WARNING: In the event your Raspberry Pi has taken the IP address of a device to which your computer has connected before (even if this was on another network), you may be given a warning and asked to clear the record from your list of known devices. Following this instruction and trying the `ssh` command again should be successful.

Next you will be prompted for the password for the `pi` login: the default password on Raspberry Pi OS is `raspberry`. 

For security reasons it is highly recommended to change the default password on the Raspberry Pi (also, you can not login through ssh if the password is blank). You should now be able to see the Raspberry Pi prompt, which will be identical to the one found on the Raspberry Pi itself.

If you have set up another user on the Raspberry Pi, you can connect to it in the same way, replacing the username with your own, e.g. `eben@192.168.1.5`

----
pi@raspberrypi ~ $
----

You are now connected to the Raspberry Pi remotely, and can execute commands.

[discrete]
=== Forwarding X11

You can also forward your X session over SSH, to allow the use of graphical applications, by using the `-Y` flag:

[,bash]
----
ssh -Y pi@192.168.1.5
----

NOTE: X11 is no longer installed by default https://support.apple.com/en-gb/HT201341[on macOS], so you will have to https://www.xquartz.org/[download] and install it.

Now you are on the command line as before, but you have the ability to open up graphical windows. For example, typing:

[,bash]
----
geany &
----

will open up the Geany editor in a window on your local desktop.

