== Secure Shell from Linux or Mac OS

You can use SSH to connect to your Raspberry Pi from a Linux desktop, another Raspberry Pi, or from an Apple Mac without installing additional software.

From 2022 om you can no longer login with pi. See this yrl: https://www.raspberrypi.com/news/raspberry-pi-bullseye-update-april-2022/

You need to add a user with a file on the boot image first. 

Open a terminal window on your computer replacing `<IP>` with the IP address of the Raspberry Pi you're trying to connect to, and use the username you made before and placed on the boot image

----
ssh xxxxx@<IP>
----

When the connection works you will see a security/authenticity warning. Type `yes` to continue. You will only see this warning the first time you connect.

NOTE: If you receive a `connection timed out` error it is likely that you have entered the wrong IP address for the Raspberry Pi.

WARNING: In the event your Raspberry Pi has taken the IP address of a device to which your computer has connected before (even if this was on another network), you may be given a warning and asked to clear the record from your list of known devices. Following this instruction and trying the `ssh` command again should be successful.

Next you will be prompted for the password for the `xxxxx` login: the default password on Raspberry Pi OS is no longer `raspberry`, but the password you privided. 



You are now connected to the Raspberry Pi remotely, and can execute commands.

[discrete]
=== Forwarding X11

You can also forward your X session over SSH, to allow the use of graphical applications, by using the `-Y` flag:

[,bash]
----
ssh -Y pi@192.168.1.5
----

NOTE: X11 is no longer installed by default https://support.apple.com/en-gb/HT201341[on macOS], so you will have to https://www.xquartz.org/[download] and install it.

Now you are on the command line as before, but you have the ability to open up graphical windows. For example, typing:

[,bash]
----
geany &
----

will open up the Geany editor in a window on your local desktop.

