[[ssh]]
== Setting up an SSH Server

You can access the command line of a Raspberry Pi remotely from another computer or device on the same network using the Secure Shell (SSH) protocol.

You will only have access to the command line, not the full desktop environment. For a full remote desktop, see xref:remote-access.adoc#vnc[VNC].

=== Set up your Local Network

Make sure your Raspberry Pi is properly set up and connected. If you are using wireless networking, this can be enabled via the desktop user interface, or using from the command line. If you are not using wireless connectivity, plug your Raspberry Pi directly into the router.

NOTE: You will need to note down the IP address of your Raspberry Pi in order to connect to it later. Using the `ifconfig` command will display information about the current network status, including the IP address, or you can use `hostname -I` to display the IP addresses associated with the device.

=== Enabling the Server

Raspberry Pi OS has the SSH server disabled by default. It can be enabled manually from the desktop:

. Launch `Raspberry Pi Configuration` from the `Preferences` menu
. Navigate to the `Interfaces` tab
. Select `Enabled` next to `SSH`
. Click `OK`

Alternatively you can enable it from the terminal using the xref:configuration.adoc#raspi-config[raspi-config] application,

. Enter `sudo raspi-config` in a terminal window
. Select `Interfacing Options`
. Navigate to and select `SSH`
. Choose `Yes`
. Select `Ok`
. Choose `Finish`

NOTE: For headless setup, SSH can be enabled by placing a file named `ssh`, without any extension, onto the boot partition of the SD Card. When the Raspberry Pi boots, it looks for the `ssh` file. If it is found, SSH is enabled and the file is deleted. The content of the file does not matter; it could contain text, or nothing at all.

NOTE: For headless setup in addition to the `ssh` file you need a `userconf.txt` file, which contains a string `username:encryptedpassword`. Please refer to the section on xref:configuration.adoc#configuring-a-user[configuring a user] in the discussions around headless setup of a Raspberry Pi.

WARNING: When enabling SSH on a Raspberry Pi that may be connected to the internet, you should ensure that your password is not easily brute forced.
