== Secure Shell from Linux or Mac OS

You can use SSH to connect to your Raspberry Pi from a Linux desktop, another Raspberry Pi, or from an Apple Mac without installing additional software.

Open a terminal window on your computer replacing `<USERNAME>` with the user name you wish to log into on the Raspberry Pi and `<IP>` with the IP address of the Raspberry Pi you're trying to connect to,

----
ssh <USERNAME>@<IP>
----

For example, if the username is `pi` and the IP address of the Raspberry Pi is `192.168.1.5`, the command would be:

----
ssh pi@192.168.1.5
----

When the connection works you will see a security/authenticity warning. Type `yes` to continue. You will only see this warning the first time you connect.

NOTE: If you receive a `connection timed out` error it is likely that you have entered the wrong IP address for the Raspberry Pi.

NOTE: If you have not logged onto the Raspberry Pi before, with a montior and keyboard plugged in follow xref:getting-started.adoc#configuration-on-first-boot[the first-boot wizard]. If the Raspberry Pi cannot be accessed with a keyboard and a monitor, please refer to xref:configuration.adoc#headless[Setting up a Headless Raspberry Pi]

WARNING: In the event your Raspberry Pi has taken the IP address of a device to which your computer has connected before (even if this was on another network), you may be given a warning and asked to clear the record from your list of known devices. Following this instruction and trying the `ssh` command again should be successful.

Next you will be prompted for the password for the user login. The password is not visible while being typed, press enter to submit.

You should now be able to see the Raspberry Pi prompt, which will be identical to the one found on the Raspberry Pi itself.

If you have set up another user on the Raspberry Pi, you can connect to it in the same way, replacing the username with your own, e.g. `eben@192.168.1.5`

----
pi@raspberrypi ~ $
----

You are now connected to the Raspberry Pi remotely, and can execute commands.

[discrete]
=== Forwarding X11

You can also forward your X session over SSH, to allow the use of graphical applications, by using the `-Y` flag:

[,bash]
----
ssh -Y pi@192.168.1.5
----

NOTE: X11 is no longer installed by default https://support.apple.com/en-gb/HT201341[on macOS], so you will have to https://www.xquartz.org/[download] and install it.

Now you are on the command line as before, but you have the ability to open up graphical windows. For example, typing:

[,bash]
----
geany &
----

will open up the Geany editor in a window on your local desktop.

