== Configure SSH without a password

To remotely access your Raspberry Pi without providing a password each time you connect, use an SSH keypair.

=== Preconfigure a boot image with Raspberry Pi Imager

When configuring a boot image with Raspberry Pi Imager, you can preconfigure SSH keys. Imager supports preconfiguring your boot image with an SSH keey. You can use a new SSH keypair or an existing SSH key.

Follow the xref:getting-started.adoc#raspberry-pi-imager[Install using Imager] guide to configure your boot image. During the OS Customisation step, navigate to the Services tab and select the *Enable SSH* checkbox. Select the *Allow public-key authentication only* radio button.

If you already have an SSH public key stored in `~/.ssh/id_rsa.pub`, Imager will automatically use that public key to prefill the text box. If Imager doesn't find an SSH public key, you can click the *RUN SSH-KEYGEN* button to generate a new keypair.

=== Manually configure an SSH key

If you already have an installation of Raspberry Pi OS, you can update your existing configuration to use SSH key authentication.

==== Set up SSH on your Raspberry Pi

First, xref:remote-access.adoc#ssh[Set up an SSH server] on your Raspberry Pi.

==== Check for existing SSH public keys

Next, check for an existing SSH public key on the computer you use to remotely connect to the Raspberry Pi:

[source,console]
----
$ ls ~/.ssh
----

If you see files named `id_ed25519.pub`, `id_rsa.pub`, or `id_dsa.pub`, you already have an SSH key. Skip SSH keypair generation and proceed to xref:remote-access.adoc#add-ssh-key-identity[add the SSH key to your list of SSH identities].

==== Generate new SSH keypair

To generate a new SSH keypair, enter the following command:

[source,console]
----
$ ssh-keygen
----

When asked where to save the key, press *Enter* to use the default location, `~/.ssh/id_rsa`.


When asked for an optional keyphrase, press *Enter* to use no keyphrase.

Run the following command to check the contents of the `.ssh` directory:

[source,console]
----
$ ls ~/.ssh
----

You should see the files `id_rsa` and `id_rsa.pub`:

----
authorized_keys  id_rsa  id_rsa.pub  known_hosts
----

The `id_rsa` file contains your private key. Keep this secure on the computer you use to remotely connect to the Raspberry Pi.

The `id_rsa.pub` file contains your public key. You will share this key with your Raspberry Pi. When you connect with the Raspberry Pi remotely, it will use this key to verify your identity.

[[add-ssh-key-identity]]
==== Add the SSH key to your list of SSH identities

Start the SSH agent:

[source,console]
----
$ eval "$(ssh-agent -s)"
----

Next, add your key identities to the authentication agent `ssh-agent` then execute the following command:

[source,console]
----
ssh-add ~/.ssh/id_rsa
----

[[copy-your-public-key-to-your-raspberry-pi]]
==== Copy the public key to your Raspberry Pi

On the computer you use to remotely connect to the Raspberry Pi, use the following command to securely copy your public key to the Raspberry Pi:

[source,console]
----
ssh-copy-id <username>@<ip address>
----

When prompted, enter your password.

Then, connect to your machine via SSH. You should now be able to connect without entering a password.
