== Drag-and-Drop MicroPython

You can program your Pico by connecting it to a computer via USB, then dragging and dropping a file onto it so we've put together a downloadable UF2 file to let you install MicroPython more easily.

video::images/MicroPython.webm[width="80%"]

Download the correct MicroPython UF2 file for your board:

* https://micropython.org/download/rp2-pico/rp2-pico-latest.uf2[Pico] 

* https://micropython.org/download/rp2-pico-w/rp2-pico-w-latest.uf2[Pico W]

* https://micropython.org/download/RPI_PICO2/RPI_PICO2-latest.uf2[Pico 2]

* https://micropython.org/download/RPI_PICO2_W/RPI_PICO2_W-latest.uf2[Pico 2 W]

For more information about using Wi-Fi and Bluetooth on Raspberry Pi Pico W-series devices with C/{cpp} or MicroPython, see https://datasheets.raspberrypi.com/picow/connecting-to-the-internet-with-pico-w.pdf[Connecting to the Internet with Raspberry Pi Pico W-series].

For more information about https://github.com/bluekitchen/btstack#supported-protocols-and-profiles[supported Bluetooth protocols and profiles], see the Blue Kitchen https://github.com/bluekitchen/btstack[BTStack] Github repository.

NOTE: MicroPython distributions for other RP2040- and RP2350-based boards are available on the https://micropython.org/download/[MicroPython download page].

To program your device, follow these steps:

. Push and hold the BOOTSEL button while connecting your Pico with a USB cable to a computer. Release the BOOTSEL button once your Pico appears as a Mass Storage Device called RPI-RP2.

. Drag and drop the MicroPython UF2 file onto the RPI-RP2 volume. Your Pico will reboot. You are now running MicroPython.

. Access the REPL via USB Serial.

The https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-python-sdk.pdf[Raspberry Pi Pico-series Python SDK] book contains step-by-step instructions for connecting to your Pico and programming it in MicroPython using both the command line and the https://thonny.org/[Thonny] IDE.
