== Troubleshooting

=== Known issues

* Screen sharing only supports sharing a single, primary display of your Raspberry Pi. When a Raspberry Pi is connected to multiple HDMI screens, Connect sometimes shares the contents of the secondary screen. You can work around this by right-clicking the desktop and changing the location of the taskbar in **Desktop Preferences...**.

* Connect does not support on-screen keyboards. For full functionality, use a physical keyboard.

* Connect requires a browser that implements https://caniuse.com/?search=es2020[ECMAScript 2020] (ES11) as it makes use of https://caniuse.com/?feats=mdn-javascript_operators_optional_chaining,mdn-javascript_operators_nullish_coalescing,mdn-javascript_builtins_globalthis,es6-module-dynamic-import,bigint,mdn-javascript_builtins_promise_allsettled,mdn-javascript_builtins_string_matchall,mdn-javascript_statements_export_namespace,mdn-javascript_operators_import_meta[features] unavailable in older browsers.

* Browsers intercept certain keys and key combinations. As a result, you can't type these keys into your Connect window. Screen sharing includes a toolbar to simulate some of the most popular intercepted keys.

* To upgrade from version 1 to version 2, you must first upgrade the package you currently have installed before switching between `rpi-connect` and `rpi-connect-lite`. This ensures that Connect's services properly migrate to the version 2 format. If you currently have `rpi-connect` installed, run the following command:
+
[source,console]
----
$ sudo apt install --only-upgrade rpi-connect
----
+
Alternatively, if you currently have `rpi-connect-lite` installed, run the following command:
+
[source,console]
----
$ sudo apt install --only-upgrade rpi-connect-lite
----
+
You should see output similar to the following during the upgrade, indicating that Connect's services have migrated to the version 2 format:
+
[source,console]
----
Replacing globally-enabled rpi-connect services with user-enabled ones...
----

=== Common issues

==== Screen sharing not available

If Connect states that screen sharing is unavailable, it cannot connect to the dedicated Connect WayVNC service.

To find out more about the cause of the issue, run the following commands to check the status of the Connect WayVNC service:

[source,console]
----
$ systemctl --user status rpi-connect-wayvnc.service
$ journalctl --user --follow --unit rpi-connect-wayvnc.service
----

If the service fails to start or doesn't exist, ensure that your environment meets the following criteria:

. You use `rpi-connect` version 1.1.0 or later.
. You do not use `rpi-connect-lite`, which lacks screen sharing support.
. You use a Wayland compositor such as wayfire or labwc, not X. You can control this setting via ``raspi-config``'s Advanced Options.
. You use a desktop environment supported by WayVNC, e.g. Raspberry Pi Desktop. For instance, using KDE switches your Wayland compositor to kwin, which is unsupported.
. You have an active graphical desktop session running as the same user as the one you signed into. For most, this means enabling "Desktop Autologin" via ``raspi-config``'s System Options.

==== Can't connect after restarting or ending SSH session

Connect runs as a user-level service and is therefore only available if there is an active session for the user signed into the service. If you want remote shell access without also running another login session, xref:connect.adoc#enable-remote-shell-at-all-times[enable user-lingering] for your user, which will keep Connect running at all times.

For screen sharing, Connect can only share an existing graphical desktop session: it does not create entirely new sessions. There must already be a desktop session in progress. To start such a session automatically on boot, enable Desktop Autologin via ``raspi-config``'s System Options.

==== Networking and firewall issues

Connect avoids changing your network or firewall in order to establish a connection. However, if you have a restrictive network and experience trouble connecting, check the following:

. Can you access the Connect API, which Connect uses for authentication and connection negotiation between your Raspberry Pi and your browser? To check, load https://api.connect.raspberrypi.com/up?[https://api.connect.raspberrypi.com/up?] on your Raspberry Pi.
. Can you access the Connect STUN server, which Connect uses to obtain a peer-to-peer connection through local or public networks? To check, ping `stun.raspberrypi.com` on UDP port 3478.
. Can you access our TURN servers, which Connect uses to relay sessions when a peer-to-peer connection fails? To check, ping `turn1.raspberrypi.com`, `turn2.raspberrypi.com` and `turn3.raspberrypi.com` on TCP ports 3478 or 443, or UDP ports 3478, 443 and 49152 -> 65535.

=== View Connect status

To view the current status of the Connect service, run the following command:

[source,console]
----
$ rpi-connect status
----

You should see output similar to the following:

----
Signed in: yes
Screen sharing: allowed (0 sessions active)
Remote shell: allowed (0 sessions active)
----

The output of this command indicates whether or not you are currently signed in to Connect, as well as the remote services enabled on your Raspberry Pi.

If you see output including "Raspberry Pi Connect is not running, run rpi-connect on", run `rpi-connect on` to start Connect.

=== Enable enhanced logging

You can enable debug logging for both `rpi-connect` and its dedicated WayVNC server for a detailed account of local operations on your Raspberry Pi.

==== Enable enhanced logging in `rpi-connect`

Override the `rpi-connect` service definition with the following command:

[source,console]
----
$ systemctl --user edit rpi-connect.service
----

Enter the following lines of configuration between the comments:

[source,bash]
----
[Service]
ExecStart=
ExecStart=/usr/bin/rpi-connectd -socket %t/rpi-connect-wayvnc.sock -v
----

NOTE: You need **both** lines that begin with `ExecStart=`.

Finally, restart Connect with the following command:

[source,console]
----
$ rpi-connect restart
----

==== Enable enhanced logging in the dedicated `wayvnc` server

Override the `rpi-connect-wayvnc` service definition with the following command:

[source,console]
----
$ systemctl --user edit rpi-connect-wayvnc
----

Enter the following lines of configuration between the comments (including the `-Ldebug` flag):

[source,bash]
----
[Service]
ExecStart=
ExecStart=/usr/bin/rpi-connect-env /usr/bin/wayvnc --config /etc/rpi-connect/wayvnc.config --render-cursor --unix-socket --socket=%t/rpi-connect-wayvnc-ctl.sock -Ldebug %t/rpi-connect-wayvnc.sock
----

NOTE: You need **both** lines that begin with `ExecStart=`.

Finally, restart Connect with the following command:

[source,console]
----
$ rpi-connect restart
----

=== View Connect logs

To view logs for the Connect service and its dedicated WayVNC server, run the following command:

[source,console]
----
$ journalctl --user --follow --unit rpi-connect.service --unit rpi-connect-wayvnc.service
----
