== Troubleshooting

=== Known issues

* Screen sharing only supports sharing a single, primary display of your Raspberry Pi. When a Raspberry Pi is connected to multiple HDMI screens, Connect sometimes shares the contents of the secondary screen. You can work around this by right-clicking the desktop and changing the location of the taskbar in **Desktop Preferences...**.

* Connect does not support on-screen keyboards. For full functionality, use a physical keyboard.

* Connect requires a browser that implements https://caniuse.com/?search=es2020[ECMAScript 2020] (ES11) as it makes use of https://caniuse.com/?feats=mdn-javascript_operators_optional_chaining,mdn-javascript_operators_nullish_coalescing,mdn-javascript_builtins_globalthis,es6-module-dynamic-import,bigint,mdn-javascript_builtins_promise_allsettled,mdn-javascript_builtins_string_matchall,mdn-javascript_statements_export_namespace,mdn-javascript_operators_import_meta[features] unavailable in older browsers.

* Browsers intercept certain keys and key combinations. As a result, you can't type these keys into your Connect window. Screen sharing includes a toolbar to simulate some of the most popular intercepted keys.

=== View Connect status

To view the current status of the Connect service, run the following command:

[source,console]
----
$ rpi-connect status
----

The output of this command indicates whether or not you are currently signed in to Connect, as well as the remote services enabled on your Raspberry Pi.

=== Enable enhanced logging

You can enable debug logging for both `rpi-connect` and its dedicated WayVNC server for a detailed account of local operations on your Raspberry Pi.

==== Enable enhanced logging in `rpi-connect`

Open the `rpi-connect` configuration file for editing with the following command:

[source,console]
----
$ systemctl --user edit rpi-connect
----

Enter the following lines of configuration between the comments:

[source,bash]
----
[Service]
ExecStart=
ExecStart=/usr/bin/rpi-connectd -socket %t/rpi-connect-wayvnc.sock -v
----

NOTE: You need **both** lines that begin with `ExecStart=`.

Finally, restart the service with the following command:

[source,console]
----
$ systemctl --user restart rpi-connect
----

==== Enable enhanced logging in the dedicated `wayvnc` server

Open the configuration file for the dedicated WayVNC server associated with Connect:

[source,console]
----
$ systemctl --user edit rpi-connect-wayvnc
----

Enter the following lines of configuration between the comments:

[source,bash]
----
[Service]
ExecStart=
ExecStart=/usr/bin/rpi-connect-env /usr/bin/wayvnc --config /etc/rpi-connect/wayvnc.config --render-cursor --unix-socket --socket=%t/rpi-connect-wayvnc-ctl.sock -Ldebug %t/rpi-connect-wayvnc.sock
----

NOTE: You need **both** lines that begin with `ExecStart=`.

Finally, restart the service with the following command:

[source,console]
----
$ systemctl --user restart rpi-connect-wayvnc
----

=== View Connect logs

To view logs for the Connect service and its dedicated WayVNC server, run the following command:

[source,console]
----
$ journalctl --user --follow --unit rpi-connect --unit rpi-connect-wayvnc
----
