== Attaching the official 7-inch display

NOTE: These instructions are intended for advanced users. If anything is unclear, use the https://forums.raspberrypi.com/viewforum.php?f=98[Raspberry Pi Compute Module forums] for technical help.

Update your system software and firmware to the latest version before starting.
Compute Modules mostly use the same process, but sometimes physical differences force changes for a particular model.

=== Quickstart guide (display only)

INFO: The Raspberry Pi Zero camera cable cannot be used as an alternative to the RPI-DISPLAY adapter. The two cables have distinct wiring.

To connect a display to DISP1:

. Disconnect the Compute Module from power.
. Connect the display to the DISP1 port on the Compute Module IO board through the 22W to 15W display adapter.
. _(CM1, CM3, CM3+, and CM4S only)_: Connect the following GPIO pins with jumper cables:
  * `0` to `CD1_SDA`
  * `1` to `CD1_SCL`

. Reconnect the Compute Module to power.
. Add the following line to xref:../computers/config_txt.adoc#what-is-config-txt[`/boot/firmware/config.txt`]:
+
[source,bash]
----
dtoverlay=vc4-kms-dsi-7inch
----
. Reboot your Compute Module with `sudo reboot`. Your device should detect and begin displaying output to your display.

To connect a display to DISP0:

. Connect the display to the DISP0 port on the Compute Module IO board through the 22W to 15W display adapter.
. _(CM1, CM3, CM3+, and CM4S only)_: Connect the following GPIO pins with jumper cables:
  * `28` to `CD0_SDA`
  * `29` to `CD0_SCL`

. Reconnect the Compute Module to power.
. Add the following line to `/boot/firmware/config.txt`:
+
[source,bash]
----
dtoverlay=vc4-kms-dsi-7inch
----
. Reboot your Compute Module with `sudo reboot`. Your device should detect and begin displaying output to your display.

=== Disable touchscreen

The touchscreen requires no additional configuration. Connect it to your Compute Module, and both the touchscreen element and display should work once successfully detected.

To disable the touchscreen element, but still use the display, add the following line to `/boot/firmware/config.txt`:

[source]
----
disable_touchscreen=1
----

To entirely ignore the display when connected, add the following line to to `/boot/firmware/config.txt`:

[source]
----
ignore_lcd=1
----

=== Firmware configuration (legacy)

NOTE: This configuration only applies to the legacy FKMS driver used with `dt-blob.bin`. That driver has been replaced by xref:../accessories/display.adoc[KMS driver autodetection].

The firmware checks `dt-blob.bin` for the following `pin_number@` defines that control screens:

----
DISPLAY_I2C_PORT
DISPLAY_SDA
DISPLAY_SCL
DISPLAY_DSI_PORT
----

The I2C port, SDA and SCL values correspond to the pin number used for each kind of display. `DISPLAY_DSI_PORT` selects between DSI1 (the default) and DSI0.

Once all the required changes have been made to the `dts` file, compile it, then place it on the boot partition of the device (`/boot/firmware/`).

For more information, see xref:configuration.adoc#change-the-default-pin-configuration[Pin Configuration].

=== Further information

* https://datasheets.raspberrypi.com/cmio/dt-blob-disp1-only.dts[dt-blob-disp1-only.dts]
* https://datasheets.raspberrypi.com/cmio/dt-blob-disp1-cam1.dts[dt-blob-disp1-cam1.dts]
* https://datasheets.raspberrypi.com/cmio/dt-blob-disp1-cam2.dts[dt-blob-disp1-cam2.dts]
* https://datasheets.raspberrypi.com/cmio/dt-blob-disp0-only.dts[dt-blob-disp0-only.dts] (uses wiring as for CAM0)
