== Onboard Analogue Audio (3.5mm Jack)

The onboard audio output uses config options to change the way the analogue audio is driven, and whether some firmware features are enabled or not.

=== `audio_pwm_mode`

`audio_pwm_mode=1` selects legacy low-quality analogue audio from the 3.5mm AV jack.

`audio_pwm_mode=2` (the default) selects high quality analogue audio using an advanced modulation scheme. 

NOTE: This option uses more GPU compute resources and can interfere with some use cases.

=== `disable_audio_dither`

By default, a 1.0LSB dither is applied to the audio stream if it is routed to the analogue audio output. This can create audible background "hiss" in some situations, for example when the ALSA volume is set to a low level. Set `disable_audio_dither` to `1` to disable dither application.

=== `enable_audio_dither`

Audio dither (see disable_audio_dither above) is normally disabled when the audio samples are larger than 16 bits. Set this option to `1` to force the use of dithering for all bit depths.

=== `pwm_sample_bits`

The `pwm_sample_bits` command adjusts the bit depth of the analogue audio output. The default bit depth is `11`. Selecting bit depths below `8` will result in nonfunctional audio, as settings below `8` result in a PLL frequency too low to support. This is generally only useful as a demonstration of how bit depth affects quantisation noise.
