[[conditional-filters]]
== Conditional Filters

When a single SD Card (or card image) is being used with one Raspberry Pi and one monitor, it is easy to set `config.txt` as required for that specific combination and keep it that way, amending it only when something changes.

However, if one Raspberry Pi is swapped between different monitors, or if the SD card (or card image) is being swapped between multiple boards, a single set of settings may no longer be sufficient. Conditional filters allow you to define certain sections of the config file to be used only in specific cases, allowing a single `config.txt` to create different configurations when read by different hardware.

=== The `[all]` filter

The `[all]` filter is the most basic filter. It resets all previously set filters and allows any settings listed below it to be applied to all hardware. It is usually a good idea to add an `[all]` filter at the end of groups of filtered settings to avoid unintentionally combining filters (see below).

=== Model Filters

The conditional model filters are applied according to the following table.

|===
| Filter | Applicable model(s)

| [pi1]
| Model 1A, Model 1B, Model 1A+, Model 1B+, Compute Module 1

| [pi2]
| Model 2B (BCM2836- or BCM2837-based)

| [pi3]
| Model 3B, Model 3B+, Model 3A+, Compute Module 3, Compute Module 3+

| [pi3+]
| Model 3A+, Model 3B+

| [pi4]
| Model 4B, Pi 400, Compute Module 4, Compute Module 4S

| [pi400]
| Pi 400

| [cm4]
| Compute Module 4

| [cm4s]
| Compute Module 4S

| [pi0]
| Zero, Zero W, Zero 2 W

| [pi0w]
| Zero W

| [pi02]
| Zero 2 W

| [board-type=Type]
| Filter by `Type` number - see xref:raspberry-pi.adoc#raspberry-pi-revision-codes[Raspberry Pi Revision Codes] E.g `[board-type=0x14]` would match CM4.

|===

These are particularly useful for defining different `kernel`, `initramfs`, and `cmdline` settings, as the Raspberry Pi 1 and Raspberry Pi 2 require different kernels. They can also be useful to define different overclocking settings, as the Raspberry Pi 1 and Raspberry Pi 2 have different default speeds. For example, to define separate `initramfs` images for each:

----
 [pi1]
 initramfs initrd.img-3.18.7+ followkernel
 [pi2]
 initramfs initrd.img-3.18.7-v7+ followkernel
 [all]
----

Remember to use the `[all]` filter at the end, so that any subsequent settings aren't limited to Raspberry Pi 2 hardware only.

It is important to note that the Raspberry Pi Zero W will see the contents of `[pi0w]` AND `[pi0]`. Likewise, a Raspberry Pi 3B+ sees `[pi3+]` AND `[pi3]`, and a Raspberry Pi 400 sees `[pi400]` AND `[pi4]`. If you want a setting to apply only to Raspberry Pi Zero, Raspberry Pi 3B or Raspberry Pi 4B, you need to follow it (order is important) with a setting in the `[pi0w]`, `[pi3+]` or `[pi400]` section that reverts it.

=== The `[none]` filter

The `[none]` filter prevents any settings that follow from being applied to any hardware. Although there is nothing that you can't do without `[none]`, it can be a useful way to keep groups of unused settings in config.txt without having to comment out every line.

=== The `[tryboot]` filter

This filter succeeds if the `tryboot` reboot flag was set.

It is intended for use in xref:config_txt.adoc#autoboot-txt[autoboot.txt] to select a different `boot_partition` in `tryboot` mode for fail-safe OS updates.

=== The `[EDID=*]` filter

When switching between multiple monitors while using a single SD card in your Raspberry Pi, and where a blank config isn't sufficient to automatically select the desired resolution for each one, this allows specific settings to be chosen based on the monitors' EDID names.

To view the EDID name of an attached monitor, run the following command:

[source]
----
tvservice -n
----
 
This will print something like this:

[source]
----
device_name=VSC-TD2220
----
 
You can then specify settings that apply only to this monitor:

[source]
----
[EDID=VSC-TD2220]
hdmi_group=2
hdmi_mode=82
[all]
----

This forces 1920x1080 DVT mode for the specified monitor, without affecting any other monitors.

Note that these settings apply only at boot, so the monitor must be connected at boot time and the Raspberry Pi must be able to read its EDID information to find the correct name. Hotplugging a different monitor into the Raspberry Pi after boot will not select different settings.

On the Raspberry Pi 4, if both HDMI ports are in use, then the EDID will be checked against both of them, and subsequent configuration applied only to the first matching device. You can determine the EDID names for both ports by first running `tvservice -l` in a terminal window to list all attached devices and then using the returned numerical IDs in `tvservice -v <id> -n` to find the EDID name for a specific display ID.

=== The Serial Number Filter

Sometimes settings should only be applied to a single specific Raspberry Pi, even if you swap the SD card to a different one. Examples include licence keys and overclocking settings (although the licence keys already support SD card swapping in a different way). You can also use this to select different display settings, even if the EDID identification above is not possible, provided that you don't swap monitors between your Raspberry Pis. For example, if your monitor doesn't supply a usable EDID name, or if you are using composite output (for which EDID cannot be read).

To view the serial number of your Raspberry Pi, run the following command:

[source]
----
cat /proc/cpuinfo
----

The serial will be shown as a 16-digit hex value at the bottom. For example, if you see:

[source]
----
Serial          : 0000000012345678
----

then you can define settings that will only be applied to this specific Raspberry Pi:

[source]
----
[0x12345678]
# settings here are applied only to the Raspberry Pi with this serial
[all]
# settings here are applied to all hardware
----

=== The GPIO Filter

You can also filter depending on the state of a GPIO. For example

[source]
----
[gpio4=1]
# Settings here are applied if GPIO 4 is high

[gpio2=0]
# Settings here are applied if GPIO 2 is low

[all]
# settings here are applied to all hardware
----

=== The `[HDMI:*]` Filter

NOTE: This filter is for the Raspberry Pi 4 only.

The Raspberry Pi 4 has two HDMI ports, and for many `config.txt` commands related to HDMI, it is necessary to specify which HDMI port is being referred to. The HDMI conditional filters subsequent HDMI configurations to the specific port.

[source]
----
 [HDMI:0]
   hdmi_group=2
   hdmi_mode=45
 [HDMI:1]
   hdmi_group=2
   hdmi_mode=67
----

An alternative `variable:index` syntax is available on all port-specific HDMI commands. You could use the following, which is the same as the previous example:

[source]
----
 hdmi_group:0=2
 hdmi_mode:0=45
 hdmi_group:1=2
 hdmi_mode:1=67
----

=== Combining Conditional Filters

Filters of the same type replace each other, so `[pi2]` overrides `[pi1]`, because it is not possible for both to be true at once.

Filters of different types can be combined simply by listing them one after the other, for example:

[source]
----
 # settings here are applied to all hardware
 [EDID=VSC-TD2220]
 # settings here are applied only if monitor VSC-TD2220 is connected
 [pi2]
 # settings here are applied only if monitor VSC-TD2220 is connected *and* on a Raspberry Pi 2
 [all]
 # settings here are applied to all hardware
----
 
Use the `[all]` filter to reset all previous filters and avoid unintentionally combining different filter types.
