[[conditional-filters]]
== Conditional filters

When a single SD card (or card image) is being used with one Raspberry Pi and one monitor, it is easy to set `config.txt` as required for that specific combination and keep it that way, amending it only when something changes.

However, if one Raspberry Pi is swapped between different monitors, or if the SD card (or card image) is being swapped between multiple boards, a single set of settings may no longer be sufficient. Conditional filters allow you to define certain sections of the config file to be used only in specific cases, allowing a single `config.txt` to create different configurations when read by different hardware.

=== The `[all]` filter

The `[all]` filter is the most basic filter. It resets all previously set filters and allows any settings listed below it to be applied to all hardware. It is usually a good idea to add an `[all]` filter at the end of groups of filtered settings to avoid unintentionally combining filters (see below).

=== Model filters

The conditional model filters are applied according to the following table.

|===
| Filter | Applicable model(s)

| `[pi1]`
| Model 1A, Model 1B, Model 1A+, Model 1B+, Compute Module 1

| `[pi2]`
| Model 2B (BCM2836- or BCM2837-based)

| `[pi3]`
| Model 3B, Model 3B+, Model 3A+, Compute Module 3, Compute Module 3+

| `[pi3+]`
| Model 3A+, Model 3B+ (also sees `[pi3]` contents)

| `[pi4]`
| Model 4B, Pi 400, Compute Module 4, Compute Module 4S

| `[pi5]`
| Raspberry Pi 5

| `[pi400]`
| Pi 400 (also sees `[pi4]` contents)

| `[cm4]`
| Compute Module 4 (also sees `[pi4]` contents)

| `[cm4s]`
| Compute Module 4S (also sees `[pi4]` contents)

| `[pi0]`
| Zero, Zero W, Zero 2 W

| `[pi0w]`
| Zero W (also sees `[pi0]` contents)

| `[pi02]`
| Zero 2 W (also sees `[pi0w]` and `[pi0]` contents)

| `[board-type=Type]`
| Filter by `Type` number - see xref:raspberry-pi.adoc#raspberry-pi-revision-codes[Raspberry Pi Revision Codes] E.g `[board-type=0x14]` would match CM4.

|===

These are particularly useful for defining different `kernel`, `initramfs`, and `cmdline` settings, as the Raspberry Pi 1 and Raspberry Pi 2 require different kernels. They can also be useful to define different overclocking settings, as the Raspberry Pi 1 and Raspberry Pi 2 have different default speeds. For example, to define separate `initramfs` images for each:

----
 [pi1]
 initramfs initrd.img-3.18.7+ followkernel
 [pi2]
 initramfs initrd.img-3.18.7-v7+ followkernel
 [all]
----

Remember to use the `[all]` filter at the end, so that any subsequent settings aren't limited to Raspberry Pi 2 hardware only.

NOTE: Some models of Raspberry Pi (Zero W, Zero 2 W, Model 3B+, Pi 400, Compute Module 4 and Compute Module 4S) see the settings for multiple filters (as listed in the table above). This means that if you want a setting to apply only to (e.g.) a Model 4B without _also_ applying that setting to a Pi 400, then the setting in the `[pi4]` section would need to be reverted by an alternate setting in a following `[pi400]` section - the ordering of such sections is significant. Alternatively, you could use a `[board-type=0x11]` filter which has a one-to-one mapping to different hardware products.

=== The `[none]` filter

The `[none]` filter prevents any settings that follow from being applied to any hardware. Although there is nothing that you can't do without `[none]`, it can be a useful way to keep groups of unused settings in config.txt without having to comment out every line.

=== The `[tryboot]` filter

This filter succeeds if the `tryboot` reboot flag was set.

It is intended for use in xref:config_txt.adoc#autoboot-txt[autoboot.txt] to select a different `boot_partition` in `tryboot` mode for fail-safe OS updates.

=== The `[EDID=*]` filter

When switching between multiple monitors while using a single SD card in your Raspberry Pi, and where a blank config isn't sufficient to automatically select the desired resolution for each one, this allows specific settings to be chosen based on the monitors' EDID names.

To view the EDID name of an attached monitor, you need to follow a few steps. Run the following command to see which output devices you have on your Raspberry Pi:

[source]
----
ls -1 /sys/class/drm/card?-HDMI-A-?/edid
----

On a Raspberry Pi 4, this will print something like:

[source]
----
/sys/class/drm/card1-HDMI-A-1/edid
/sys/class/drm/card1-HDMI-A-2/edid
----

You then need to run `edid-decode` against each of these filenames, e.g.

[source]
----
edid-decode /sys/class/drm/card1-HDMI-A-1/edid
----

If there's no monitor connected to that particular output device, it'll tell you the EDID was empty; otherwise it will serve you *lots* of information about your monitor's capabilities. You need to look for the lines specifying the `Manufacturer` and the `Display Product Name`. The "EDID name" is then `<Manufacturer>-<Display Product Name>`, with any spaces in either string replaced by underscores. For example, if your `edid-decode` output included:

[source]
----
....
  Vendor & Product Identification:
    Manufacturer: DEL
....
    Display Product Name: 'DELL U2422H'
....
----

...then the EDID name for this monitor would be `DEL-DELL_U2422H`.

You can then use this as a conditional-filter to specify settings that only apply when this particular monitor is connected:

[source]
----
[EDID=DEL-DELL_U2422H]
cmdline=cmdline_U2422H.txt
[all]
----

These settings apply only at boot. The monitor must be connected at boot time, and the Raspberry Pi must be able to read its EDID information to find the correct name. Hotplugging a different monitor into the Raspberry Pi after boot will not select different settings.

On the Raspberry Pi 4, if both HDMI ports are in use, then the EDID filter will be checked against both of them, and configuration from all matching conditional filters will be applied.

NOTE: This setting is not available on Raspberry Pi 5.

=== The serial number filter

Sometimes settings should only be applied to a single specific Raspberry Pi, even if you swap the SD card to a different one. Examples include licence keys and overclocking settings (although the licence keys already support SD card swapping in a different way). You can also use this to select different display settings, even if the EDID identification above is not possible, provided that you don't swap monitors between your Raspberry Pis. For example, if your monitor doesn't supply a usable EDID name, or if you are using composite output (from which EDID cannot be read).

To view the serial number of your Raspberry Pi, run the following command:

[source]
----
cat /proc/cpuinfo
----

A 16-digit hex value will be displayed near the bottom of the output. Your Raspberry Pi's serial number is the last eight hex-digits. For example, if you see:

[source]
----
Serial          : 0000000012345678
----

...then you can define settings that will only be applied to this specific Raspberry Pi:

[source]
----
[0x12345678]
# settings here are applied only to the Raspberry Pi with this serial
[all]
# settings here are applied to all hardware
----

=== The GPIO filter

You can also filter depending on the state of a GPIO. For example:

[source]
----
[gpio4=1]
# Settings here are applied if GPIO 4 is high

[gpio2=0]
# Settings here are applied if GPIO 2 is low

[all]
# settings here are applied to all hardware
----

=== Combining conditional filters

Filters of the same type replace each other, so `[pi2]` overrides `[pi1]`, because it is not possible for both to be true at once.

Filters of different types can be combined simply by listing them one after the other, for example:

[source]
----
 # settings here are applied to all hardware
 [EDID=VSC-TD2220]
 # settings here are applied only if monitor VSC-TD2220 is connected
 [pi2]
 # settings here are applied only if monitor VSC-TD2220 is connected *and* on a Raspberry Pi 2
 [all]
 # settings here are applied to all hardware
----
 
Use the `[all]` filter to reset all previous filters and avoid unintentionally combining different filter types.
