== Video options

=== HDMI mode

In order to support dual 4k displays, the Raspberry Pi 4 has xref:config_txt.adoc#raspberry-pi-4-hdmi-pipeline[updated video hardware], which imposes minor restrictions on the modes supported.

The HDMI settings used to be configured by firmware via settings in `config.txt`; now the settings are configured by KMS via xref:configuration.adoc#hdmi-configuration[settings] in `cmdline.txt`.

=== Composite video mode

Composite video output can be found on each model of Raspberry Pi computer:

|===
| model | composite output

| Raspberry Pi 1 A and B
| RCA jack

| Raspberry Pi Zero
| Unpopulated `TV` header

| Raspberry Pi Zero 2 W 
| Test pads on underside of board

| Raspberry Pi 5
| J7 pad next to HDMI socket

| All other models
| 3.5mm AV jack
|===

NOTE: Composite video output is not available on Raspberry Pi 400.

==== `enable_tvout`

Set to `1` to enable composite video output, or `0` to disable. On Raspberry Pi 4 and 5, composite output is only available if you set this to `1`, which also disables HDMI output. Composite output is not available on the Raspberry Pi 400.

[%header,cols="1,1"]

|===
|Model
|Default

|Pi 4, 5 and 400
|0

|All other models
|1
|===

On all models except Raspberry Pi 4 and 5, HDMI output needs to be disabled in order for composite output to be enabled. HDMI output is disabled when no HDMI display is connected / detected. Set `enable_tvout=0` to prevent composite being enabled when HDMI is disabled.

To enable composite output (on all models of Raspberry Pi) you also need to append `,composite` to the end of the `dtoverlay=vc4-kms-v3d` line in xref:../computers/config_txt.adoc#what-is-config-txt[`/boot/firmware/config.txt`]:

----
dtoverlay=vc4-kms-v3d,composite
----

By default this will output composite NTSC video. To choose a different mode, you need to append

----
vc4.tv_norm=video_mode
----

to the single line in `/boot/firmware/cmdline.txt`, where `video_mode` is one of `NTSC`, `NTSC-J`, `NTSC-443`, `PAL`, `PAL-M`, `PAL-N`, `PAL60` or `SECAM`.

=== LCD displays and touchscreens

==== `ignore_lcd`

By default the Raspberry Pi Touch Display is used when it is detected on the I2C bus. `ignore_lcd=1` will skip this detection phase, and therefore the LCD display will not be used.

==== `disable_touchscreen`

Enable/disable the touchscreen.

`disable_touchscreen=1` will disable the touchscreen on the official Raspberry Pi Touch Display.

=== Generic display options

==== `disable_fw_kms_setup`

By default, the firmware parses the EDID of any HDMI attached display, picks an appropriate video mode, then passes the resolution and frame rate of the mode, along with overscan parameters, to the Linux kernel via settings on the kernel command line. In rare circumstances, this can have the effect of choosing a mode that is not in the EDID, and may be incompatible with the device. You can use `disable_fw_kms_setup=1` to disable the passing of these parameters and avoid this problem. The Linux video mode system (KMS) will then parse the EDID itself and pick an appropriate mode.

NOTE: On Raspberry Pi 5 this parameter defaults to `1`


