== Sense HAT hardware

The Sense HAT has an 8×8 RGB LED matrix and a five-button joystick, and includes the following sensors:

* Gyroscope
* Accelerometer
* Magnetometer
* Temperature
* Barometric pressure
* Humidity
* Colour and brightness

Schematics and mechanical drawings for the Sense HAT are available for download.

* https://datasheets.raspberrypi.com/sense-hat/sense-hat-schematics.pdf[Sense HAT schematics].
* https://datasheets.raspberrypi.com/sense-hat/sense-hat-mechanical-drawing.pdf[Sense HAT mechanical drawings].

=== LED matrix

The LED matrix is an RGB565 https://www.kernel.org/doc/Documentation/fb/framebuffer.txt[framebuffer] with the id "RPi-Sense FB". The appropriate device node can be written to as a standard file or mmap-ed. The included 'snake' example shows how to access the framebuffer.

=== Joystick

The joystick comes up as an input event device named "Raspberry Pi Sense HAT Joystick", mapped to the arrow keys and `Enter`. It should be supported by any library which is capable of handling inputs, or directly through the https://www.kernel.org/doc/Documentation/input/input.txt[evdev interface]. Suitable libraries include SDL, http://www.pygame.org/docs/[pygame] and https://python-evdev.readthedocs.org/en/latest/[python-evdev]. The included 'snake' example shows how to access the joystick directly.

== Hardware calibration

Install the necessary software and run the calibration program as follows:

[,bash]
----
$ sudo apt update
$ sudo apt install octave -y
$ cd
$ cp /usr/share/librtimulib-utils/RTEllipsoidFit ./ -a
$ cd RTEllipsoidFit
$ RTIMULibCal
----

You will then see this menu:

----
Options are:

  m - calibrate magnetometer with min/max
  e - calibrate magnetometer with ellipsoid (do min/max first)
  a - calibrate accelerometers
  x - exit

Enter option:
----

Press lowercase `m`. The following message will then show. Press any key to start.

----
    Magnetometer min/max calibration
    --------------------------------
    Waggle the IMU chip around, ensuring that all six axes
    (+x, -x, +y, -y and +z, -z) go through their extrema.
    When all extrema have been achieved, enter 's' to save, 'r' to reset
    or 'x' to abort and discard the data.

    Press any key to start...
----

After it starts, you will see something similar to this scrolling up the screen:

----
 Min x:  51.60  min y:  69.39  min z:  65.91
 Max x:  53.15  max y:  70.97  max z:  67.97
----

Focus on the two lines at the very bottom of the screen, as these are the most recently posted measurements from the program.

Now, pick up the Raspberry Pi and Sense HAT and move it around in every possible way you can think of. It helps if you unplug all non-essential cables to avoid clutter.

Try and get a complete circle in each of the pitch, roll and yaw axes. Take care not to accidentally eject the SD card while doing this. Spend a few minutes moving the Sense HAT, and stop when you find that the numbers are not changing anymore.

Now press lowercase `s` then lowercase `x` to exit the program. If you run the `ls` command now, you'll see a new `RTIMULib.ini` file has been created.

In addition to those steps, you can also do the ellipsoid fit by performing the steps above, but pressing `e` instead of `m`.

When you're done, copy the resulting `RTIMULib.ini` to /etc/ and remove the local copy in `~/.config/sense_hat/`:

[,bash]
----
$ rm ~/.config/sense_hat/RTIMULib.ini
$ sudo cp RTIMULib.ini /etc
----

== Reading and writing EEPROM data

Enable I2C0 and I2C1 by adding the following line to `/boot/config.txt`:

----
 dtparam=i2c_vc=on
 dtparam=i2c_arm=on
----

Enter the following command to reboot:

[,bash]
----
 sudo systemctl reboot
----

Download and build the flash tool:

[,bash]
----
$ git clone https://github.com/raspberrypi/hats.git
$ cd hats/eepromutils
$ make
----

NOTE: These steps may not work on Raspberry Pi 2 Model B Rev 1.0 and Raspberry Pi 3 Model B boards. The firmware will take control of I2C0, causing the ID pins to be configured as inputs.

=== Reading

EEPROM data can be read with the following command:

[,bash]
----
$ sudo ./eepflash.sh -f=sense_read.eep -t=24c32 -r
----

=== Writing

Download EEPROM settings and build the `.eep` binary:

[,bash]
----
$ wget https://github.com/raspberrypi/rpi-sense/raw/master/eeprom/eeprom_settings.txt -O sense_eeprom.txt
 ./eepmake sense_eeprom.txt sense.eep /boot/overlays/rpi-sense-overlay.dtb
----

Disable write protection:

[,bash]
----
$ i2cset -y -f 1 0x46 0xf3 1
----

Write the EEPROM data:

[,bash]
----
$ sudo ./eepflash.sh -f=sense.eep -t=24c32 -w
----

Re-enable write protection:

[,bash]
----
 i2cset -y -f 1 0x46 0xf3 0
----

WARNING: This operation will not damage your Raspberry Pi or Sense Hat, but if an error occurs, the HAT may no longer be automatically detected. The steps above are provided for debugging purposes only. 
