== Model Conversion

Sony provides tools that enable users to convert pre-existing TensorFlow or PyTorch models to run on the Raspberry Pi AI Camera. Additionally, users can also build and train entirely new models for the IMX500.

=== Install the IMX500 tools package

First, install the necessary tools:

[source,console]
----
$ sudo apt install imx500-tools
----

== Convert and package the model

Next, run the tools to convert and package the model.

The following command converts a model file stored in the `<model-folder>` directory into a converted, IMX500-compatible model stored in `<converted-model-folder>`:

[source,console]
----
$ imx500-convert.sh -i <model-folder> -o <converted-model-folder>
----


Then, run the following command to package the converted model stored in the `<converted-model-folder>` directory into a package stored in `<packaged-model-folder>`.

[source,console]
----
$ imx500-package.sh -i <converted-model-folder> -o <packaged-model-folder>
----

=== Prepare firmware for deployment

Finally, prepare the firmware for the Raspberry Pi AI Camera. This preparation swaps the Endian-ness of the byte ordering, then appends some sensor register information provided by the model conversion steps above into the firmware file.

Run the following commands to prepare the firmware into a file named `imx500_network.fpk`:

[source,console]
----
$ objcopy -I binary -O binary --reverse-bytes=4 /<packaged-model>/network.fpk network.fpk.REVERSED
$ ni_to_reg /<packaged-model>/network_info.txt > registers.bin
$ cat network.fpk.REVERSED registers.bin > imx500_network.fpk
----

You can then load the prepared `imx500_network.fpk` file onto your Raspberry Pi AI Camera using the helper functions described above.

For more information about the AI Camera and the tools used to work with it, visit the https://developer.sony.com/imx500/[Sony IMX500 developer website].
