:pp: {plus}{plus}
== Raspberry Pi Pico C/C{pp} SDK

Our official C SDK can be used from the command line, or from popular integrated development environments like Visual Studio Code, Eclipse, and CLion. To get started, download our C/C++ SDK and Examples, and take a look at our 'https://datasheets.raspberrypi.org/pico/getting-started-with-pico.pdf[getting started]' documentation to get going. Or for a quick setup see the next section.

* The SDK https://github.com/raspberrypi/pico-sdk[Github repository]

* The Examples https://github.com/raspberrypi/pico-examples[Github repository]

You can find documentation around the C/C{pp} SDK at;

https://datasheets.raspberrypi.org/pico/getting-started-with-pico.pdf[Getting started with Raspberry Pi Pico]:: C/C++ development with Raspberry Pi Pico and other RP2040-based microcontroller boards

https://datasheets.raspberrypi.org/pico/raspberry-pi-pico-c-sdk.pdf[Raspberry Pi Pico C/C{pp} SDK]:: Libraries and tools for C/C++ development on RP2040 microcontrollers

The API level Doxygen documentation for the Raspberry Pi Pico C/C{pp} SDK is also available https://rptl.io/pico-doxygen[as a micro-site].

[NOTE]
======
If you are building applications with the C/C++ SDK and targetting boards other than the Raspberry Pi Pico, you will need to pass `-DPICO_BOARD=boardname` to CMake. Here `boardname` is the name of your board, e.g. for the Adafruit Feather RP2040 you should pass `-DPICO_BOARD=adafruit_feather_rp2040`. See the https://github.com/raspberrypi/pico-sdk/tree/master/src/boards[`boards/` directory] in the Pico SDK, and the https://www.raspberrypi.org/forums/viewtopic.php?f=147&t=304393[forums], for more information.
======
