== Raspberry Pi Pico C/C++ SDK

Our official C SDK can be used from the command line, or from popular integrated development environments like Visual Studio Code, Eclipse, and CLion. To get started, download our C/{cpp} SDK and Examples, and take a look at our 'https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf[getting started]' documentation. Or for a quick setup see the next section.

You can find documentation around the C/{cpp} SDK at:

https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf[Getting started with Raspberry Pi Pico-series]:: C/{cpp} development with Raspberry Pi Pico, Pico 2, and other Raspberry Pi microcontroller-based boards

https://datasheets.raspberrypi.com/picow/connecting-to-the-internet-with-pico-w.pdf[Connecting to the Internet with Raspberry Pi Pico W]:: Getting Raspberry Pi Pico W online with C/{cpp} or MicroPython

https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-c-sdk.pdf[Raspberry Pi Pico-series C/{cpp} SDK]:: Libraries and tools for C/{cpp} development on Raspberry Pi microcontrollers

xref:../pico-sdk/index_doxygen.adoc[API level documentation]:: Documentation for the Raspberry Pi Pico C/{cpp} SDK

https://github.com/raspberrypi/pico-examples[The pico-examples repository]:: Example projects

SDK source code is open source, available via the https://github.com/raspberrypi/pico-sdk[pico-sdk Github repository].

[NOTE]
====
To build applications with the C/{cpp} SDK for a board _other than the Raspberry Pi Pico_, pass `-DPICO_BOARD=boardname` to CMake, where `boardname` is the name of your board. For example:

* to build an application for the Adafruit Feather RP2040, pass `-DPICO_BOARD=adafruit_feather_rp2040`
* to build an application for Pico W, pass `-DPICO_BOARD=pico_w` (in addition to -DWIFI_SSID="Your Network" -DWIFI_PASSWORD="Your Password", should you wish to connect to a wireless network)

For more information, see the https://github.com/raspberrypi/pico-sdk/tree/master/src/boards[`boards/` directory] in the Raspberry Pi Pico SDK and the https://forums.raspberrypi.com/viewtopic.php?f=147&t=304393[forums].
====
