== Troubleshooting the Display

[discrete]
=== Have you got a good power supply?

Having intermittent problems, or seeing a little rainbow square in the top right corner? It is likely that you need a better power supply.

We recommend our official 2.5A adapter because we know it works, but any good 2.5A supply should work.

[discrete]
=== Have you updated Raspberry Pi OS?

If not, many problems will be solved by making sure your software is xref:../computers/os.adoc#updating-and-upgrading-raspberry-pi-os[up-to date].

[discrete]
=== My touchscreen doesn't work, or works intermittently

* Make sure you've updated Raspberry Pi OS (see above for steps)
* Check the smaller ribbon cable is seated properly

If you want to make sure your Raspberry Pi has detected your touchscreen, try running:

[,bash]
----
dmesg | grep -i ft5x06
----

You should see a couple of lines that look like this:

[,text]
----
[   10.463038] edt_ft5x06 10-0038: supply iovcc not found, using dummy regulator
[   10.879193] input: generic ft5x06 (00) as /devices/platform/soc/fe205000.i2c/i2c-22/i2c-10/10-0038/input/input6
----

[discrete]
=== My screen is upside-down!

Depending on your display stand, you might find that the LCD display defaults to being upside-down. You can fix this by xref:../computers/configuration.adoc#rotating-your-display[rotating your display].

[discrete]
=== My display fades out to weird patterns when I shutdown/reboot my Raspberry Pi

Don't panic! This is perfectly normal.

[discrete]
=== My display is black

* Make sure you've updated Raspberry Pi OS (see above for steps)
* Check the ribbon cable between your Raspberry Pi and the LCD is properly seated
* Make sure you have a SD card properly inserted into your Raspberry Pi

[discrete]
=== My display is white

* Check the larger ribbon cable between the display and driver board is properly seated

[discrete]
=== Some windows are cut off at the bottom of the screen so I can't use them

If some windows are cut off at the side/bottom of the screen, this is unfortunately a side-effect of developers assuming a minimum screen resolution of 1024x768 pixels.

You can usually reveal hidden buttons and fields by:

* holding down the Windows / Raspberry key on your keyboard
* click and drag anywhere inside the window to move it around the screen

[NOTE]
====
If you are using X11, you can reveal hiddden buttons and fields by:

* right clicking on the top or bottom edge of the window
* picking "move"
* using the arrow keys to move the window around the screen
====

=== Tips and Tricks

==== How do I use multiple monitors?

If you're using the desktop environment with multiple displays, you may find that the 'taps' on the Touch Display's touchscreen get registered against the wrong display, and not with the display on the Touch Display. To resolve this, run the "Screen Configuration" program, right-click on the `DSI-1` rectangle, and then select `Touchscreen` > `generic ft5x06`, click `Apply` and close the Screen Configuration program. You may need to reboot for these changes to take effect.

See the documentation about xref:../computers/os.adoc#playing-audio-and-video[playing video] if you're using Raspberry Pi OS Lite and went to display the video on a specfic screen.

==== How do I enable right click?

WARNING: This isn't currently possible with Wayland.

[NOTE]
====
Under X11 you can emulate a right click by adding the following snippet to `/etc/X11/xorg.conf`
----
Section "InputClass"
   Identifier "calibration"
   Driver "evdev"
   MatchProduct "FT5406 memory based driver"

   Option "EmulateThirdButton" "1"
   Option "EmulateThirdButtonTimeout" "750"
   Option "EmulateThirdButtonMoveThreshold" "30"
EndSection
----
====

==== How do I get an on-screen keyboard?

WARNING: This isn't currently possible with Wayland.

[NOTE]
====
Under X11 you can install a virtual keyboard with `sudo apt install matchbox-keyboard`
====

