# This Makefile "makes" the build/jekyll directory, i.e. copies asciidoc and creates autogenerated files

include makefiles/shared.mk

OUTPUT_DIR = $(ASCIIDOC_BUILD_DIR)
MARKER_FILE = $(OUTPUT_DIR)/.done
NEXT_MAKEFILE = makefiles/html.mk

AUTO_NINJABUILD = $(BUILD_DIR)/auto_jekyll.ninja
ASCIIDOC_INCLUDES_DIR = $(BUILD_DIR)/adoc_includes

# The $(MARKER_FILE) is used to ensure that all the asciidoc files are copied before we try invoking jekyll
all: | $(MARKER_FILE)

clean:
	rm -rf $(OUTPUT_DIR)
	rm -f $(AUTO_NINJABUILD)
	$(MAKE) -f $(NEXT_MAKEFILE) invalidate

# Some of the source-files have changed, so things might need to be rebuilt
invalidate:
	rm -f $(AUTO_NINJABUILD) $(MARKER_FILE)

.PHONY: all clean invalidate update_offline_includes

$(OUTPUT_DIR):
	mkdir -p $@

$(OUTPUT_DIR)/%: | $(JEKYLL_ASSETS_DIR)/% $(OUTPUT_DIR)
	cp -r $(firstword $|) $@

JEKYLL_DIRS = $(OUTPUT_DIR)/_data $(OUTPUT_DIR)/_layouts $(OUTPUT_DIR)/_includes $(OUTPUT_DIR)/_plugins $(OUTPUT_DIR)/css $(OUTPUT_DIR)/scripts

DOWNLOADED_INCLUDES = $(OUTPUT_DIR)/_includes/header.html $(OUTPUT_DIR)/_includes/fonts.html

offline_includes/tmp: offline_includes
	mkdir -p $@

offline_includes/tmp/%.html: $(SCRIPTS_DIR)/fetch_header_and_fonts.py | offline_includes/tmp
	OFFLINE_MODE=0 $< https://esi.raspberrypi.org/en/components/$*/ $@

update_offline_includes: offline_includes/tmp/header.html offline_includes/tmp/fonts.html
	mv offline_includes/tmp/header.html offline_includes
	mv offline_includes/tmp/fonts.html offline_includes
	rmdir offline_includes/tmp

$(OUTPUT_DIR)/_includes/%.html: $(SCRIPTS_DIR)/fetch_header_and_fonts.py | $(OUTPUT_DIR)/_includes
	$< https://esi.raspberrypi.org/en/components/$*/ $@

$(AUTO_NINJABUILD): $(SCRIPTS_DIR)/create_jekyll_ninjabuild.py $(DOCUMENTATION_INDEX) | $(BUILD_DIR)
	$< $(DOCUMENTATION_INDEX) $(SITE_CONFIG) $(ASCIIDOC_DIR) $(OUTPUT_DIR) $(ASCIIDOC_INCLUDES_DIR) $@

$(OUTPUT_DIR)/_data/index.json: $(SCRIPTS_DIR)/create_output_index_json.py $(DOCUMENTATION_INDEX) | $(OUTPUT_DIR)/_data
	$< $(DOCUMENTATION_INDEX) $@

$(OUTPUT_DIR)/.htaccess: $(SCRIPTS_DIR)/create_htaccess.py $(HTACCESS_EXTRA) $(wildcard $(DOCUMENTATION_REDIRECTS_DIR)/*.csv) | $(OUTPUT_DIR)
	$< $(HTACCESS_EXTRA) $(DOCUMENTATION_REDIRECTS_DIR) $@

$(OUTPUT_DIR)/DO_NOT_EDIT.txt: | $(OUTPUT_DIR)
	echo "Do not edit any files in this directory. Everything will get overwritten when you run 'make'" > $@

$(OUTPUT_DIR)/images: | $(OUTPUT_DIR)
	mkdir -p $@

$(OUTPUT_DIR)/images/%: $(DOCUMENTATION_IMAGES_DIR)/% | $(OUTPUT_DIR)/images
	cp $< $@

$(MARKER_FILE): $(AUTO_NINJABUILD) $(JEKYLL_DIRS) $(DOWNLOADED_INCLUDES) $(OUTPUT_DIR)/_data/index.json $(OUTPUT_DIR)/.htaccess $(OUTPUT_DIR)/DO_NOT_EDIT.txt $(OUTPUT_DIR)/images/opensocial.png | $(OUTPUT_DIR)
	ninja -f $<
	touch $@
	$(MAKE) -f $(NEXT_MAKEFILE) invalidate
