=== Camera tuning and supporting third-party sensors

==== The camera tuning file

Most of the image processing applied to frames from the sensor is done by the hardware ISP. This processing is governed by a set of control algorithms, and these in turn must have a wide range of parameters supplied to them. These parameters are tuned specifically for each sensor and are collected together in a JSON file known as the camera tuning file.

This tuning file can be inspected and edited by users. Using the `--tuning-file` command line option, users can point the system at completely custom camera tuning files.

==== Third-party sensors

`libcamera` makes it possible to support third-party sensors (sensors other than Raspberry Pi's officially supported sensors) on the Raspberry Pi platform. To accomplish this, a working open source sensor driver must be provided, which the authors should be happy to submit to the Linux kernel. There are a couple of extra files which need to be added to `libcamera`, supplying device-specific information which is available from the kernel drivers, including the previously discussed camera tuning file.

Raspberry Pi also supplies a tuning tool which automates the generation of the tuning file from a few simple calibration images.

While these topics are rather beyond the scope of the documentation here, full information is available in the https://datasheets.raspberrypi.com/camera/raspberry-pi-camera-guide.pdf[Tuning guide for the Raspberry Pi cameras and libcamera].
