=== `libcamera` and `libcamera-apps` Packages

A number of `apt` packages are provided for convenience. In order to access them, we recommend keeping your OS up to date xref:../computers/os.adoc#using-apt[in the usual way].

==== Binary Packages

There are two `libcamera-apps` packages available, that contain the necessary executables:

* `libcamera-apps` contains the full applications with support for previews using X Windows. This package is pre-installed in the _Bullseye_ release of Raspberry Pi OS.

* `libcamera-apps-lite` omits X Windows support and only the DRM preview is available. This package is pre-installed in the _Bullseye_ release of Raspberry Pi OS Lite.

For _Bullseye_ users, official Raspberry Pi cameras should be detected automatically. Other users will need to xref:camera_software.adoc#if-you-do-need-to-alter-the-configuration[edit their `/boot/config.txt`] file if they have not done so previously.

==== Dependencies

These applications depend on a number of library packages which are named _library-name<n>_ where _<n>_ is a version number (actually the ABI, or Application Binary Interface, version), and which stands at zero at the time of writing. Thus we have the following:

* The package `libcamera0` contains the `libcamera` libraries.

* The package `libepoxy0` contains the `libepoxy` libraries.

These will be installed automatically when needed.

==== Dev Packages

`libcamera-apps` can be rebuilt on their own without installing and building `libcamera` and `libepoxy` from scratch. To enable this, the following packages should be installed:

* `libcamera-dev` contains the necessary `libcamera` header files and resources.

* `libepoxy-dev` contains the necessary `libepoxy` header files and resources. You will only need this if you want support for the X11/GLES preview window.

Subsequently `libcamera-apps` can be xref:camera_software.adoc#building-libcamera-apps-without-rebuilding-libcamera[checked out from GitHub and rebuilt].
