=== Using libcamera and Qt together

Qt is a popular application framework and GUI toolkit. There is the option in `rpicam-apps` to use it to implement a camera preview window.

However, Qt defines certain symbols as macros in the global namespace (such as `slot` and `emit`) and this causes errors when including libcamera files. The problem is common to all platforms trying to use both Qt and libcamera and not specific to Raspberry Pi. Nonetheless we suggest that developers experiencing difficulties try the following workarounds.

* libcamera include files, or files that include libcamera files (such as `rpicam-apps` files), should be listed before any Qt header files where possible.

* If you do need to mix your Qt application files with libcamera includes, replace `signals:` with `Q_SIGNALS:`, `slots:` with `Q_SLOTS:`, `emit` with `Q_EMIT` and `foreach` with `Q_FOREACH`.

* Before any libcamera include files, add
+
----
#undef signals
#undef slots
#undef emit
#undef foreach
----

* If you are using qmake, add `CONFIG += no_keywords` to the project file. If using cmake, add `SET(QT_NO_KEYWORDS ON)`.

We are not aware of any plans for the underlying library problems to be addressed.
