=== `rpicam-raw`

`rpicam-raw` behaves like a video-recording application, except that it records raw Bayer frames directly from the sensor. It does not show a preview window. For a two-second raw clip:

[,bash]
----
rpicam-raw -t 2000 -o test.raw
----

The raw frames are dumped with no formatting information at all, one directly after another. The application prints the pixel format and image dimensions to the terminal window so that the user can see how to interpret the pixel data.

By default, the raw frames are saved in a single (and potentially very large) file. As we saw previously, the `--segment` option can be used to direct each to a separate file.
[,bash]
----
rpicam-raw -t 2000 --segment 1 -o test%05d.raw
----

In good conditions (using a fast SSD), `rpicam-raw` can get close to writing 12MP HQ camera frames (18MB of data each) to disk at 10fps. It writes the raw frames with no formatting in order to achieve these speeds; it has no capability to save them as DNG files like `rpicam-still`. If you want to be sure not to drop frames, you can reduce the framerate slightly using the `--framerate` option.

[,bash]
----
rpicam-raw -t 5000 --width 4056 --height 3040 -o test.raw --framerate 8
----

For more information on the raw formats, including how to choose between packed and unpacked versions, as well as the differences between Pi 5 and earlier models, please refer to the `--mode` option in the xref:camera_software.adoc#camera-resolution-and-readout[camera resolution options section].
