=== Getting started

Recent versions of Raspberry Pi OS include the five basic `rpicam-apps`.
This means that you can run the following command on any Raspberry Pi with a camera connected to open a camera preview window for five seconds:

[source,console]
----
$ rpicam-hello
----

==== Configuration

Most use cases work automatically with no need to alter the camera configuration. However, some common use cases do require configuration tweaks, including:

* Third-party cameras (the manufacturer's instructions should explain necessary configuration changes, if any)

* Using a non-standard driver or overlay with an official Raspberry Pi camera

Raspberry Pi OS recognises the following overlays in `/boot/firmware/config.txt`.

|===
| Camera Module | In `/boot/firmware/config.txt`

| V1 camera (OV5647)
| `dtoverlay=ov5647`

| V2 camera (IMX219)
| `dtoverlay=imx219`

| HQ camera (IMX477)
| `dtoverlay=imx477`

| GS camera (IMX296)
| `dtoverlay=imx296`

| Camera Module 3 (IMX708)
| `dtoverlay=imx708`

| IMX290 and IMX327
| `dtoverlay=imx290,clock-frequency=74250000` or `dtoverlay=imx290,clock-frequency=37125000` (both modules share the imx290 kernel driver; refer to instructions from the module vendor for the correct frequency)

| IMX378
| `dtoverlay=imx378`

| OV9281
| `dtoverlay=ov9281`
|===

To use one of these overlays, you must disable automatic camera detection. To disable automatic detection, set `camera_auto_detect=0` in `/boot/firmware/config.txt`. If `config.txt` already contains a line assigning an `camera_auto_detect` value, change the value to `0`. Reboot your Raspberry Pi with `sudo reboot` to load your changes.

=== Troubleshooting

If your Camera Module doesn't work like you expect, try some of the following fixes:

* If you use a Raspberry Pi 3 or earlier and Raspberry Pi OS _Bullseye_ or earlier:
** To enable hardware-accelerated camera previews, enable *Glamor*. To enable Glamor, enter `sudo raspi-config` in a terminal, select `Advanced Options` > `Glamor` > `Yes`. Then reboot your Raspberry Pi with `sudo reboot`.
** If you see an error related to the display driver, add `dtoverlay=vc4-fkms-v3d` or `dtoverlay=vc4-kms-v3d` to `/boot/config.txt`. Then reboot your Raspberry Pi with `sudo reboot`.
* Check that the FFC (Fat Flexible Cable) is firmly seated, fully inserted, and that the contacts face the correct direction. The FFC should be evenly inserted, not angled.
* If you use a connector between the camera and your Raspberry Pi, check that the ports on the connector are firmly seated, fully inserted, and that the contacts face the correct direction.
* Check to make sure that the FFC (Flat Flexible Cable) is attached to the CSI (Camera Serial Interface), _not_ the DSI (Display Serial Interface). The connector fits into either port, but only the CSI port powers and controls the camera. Look for the `CSI` label printed on the board near the port.
* Run `sudo apt update` and `sudo apt full-upgrade` to ensure that you're running the latest software.
* Try a different power supply. The Camera Module adds about 200-250mA to the power requirements of your Raspberry Pi. If your power supply is low quality, your Raspberry Pi may not be able to power the Camera module.
* If you've checked all the above issues and your Camera Module still doesn't work like you expect, try posting on our forums for more help.
