=== `rpicam-jpeg`

`rpicam-jpeg` is a simple still image capture application. It deliberately avoids some of the additional features of `rpicam-still`, which attempts to emulate `raspistill` more fully. This means that the code is significantly easier to understand, while still providing many of the same features.

To capture a full resolution JPEG image use:

[,bash]
----
rpicam-jpeg -o test.jpg
----
This will display a preview for about five seconds, and then capture a full resolution JPEG image to the file `test.jpg`. 

The `-t <duration>` option can be used to alter the length of time the preview shows, and the `--width` and `--height` options will change the resolution of the captured still image. For example:

[,bash]
----
rpicam-jpeg -o test.jpg -t 2000 --width 640 --height 480
----
...will capture a VGA sized image.

==== Exposure control

All the `rpicam-apps` allow the user to run the camera with fixed shutter-speed and gain. 

Capture an image with an exposure of 20ms and a gain of 1.5×:

[,bash]
----
rpicam-jpeg -o test.jpg -t 2000 --shutter 20000 --gain 1.5
----
The gain will be applied as analogue gain within the sensor, up until it reaches the maximum analogue gain permitted by the kernel sensor driver, after which the remainder will be applied as digital gain.

Raspberry Pi's AEC/AGC algorithm allows applications to specify exposure compensation: the ability to make images darker or brighter by a given number of stops.

[,bash]
----
rpicam-jpeg --ev -0.5 -o darker.jpg
rpicam-jpeg --ev 0 -o normal.jpg
rpicam-jpeg --ev 0.5 -o brighter.jpg
----

===== Further remarks on digital gain

Digital gain is applied by the ISP, not by the sensor. The digital gain will always be very close to 1.0 unless:

* The total gain requested (either by the `--gain` option, or by the exposure profile in the camera tuning) exceeds that which can be applied as analogue gain within the sensor. Only the extra gain required will be applied as digital gain.

* One of the colour gains is less than 1 (note that colour gains are applied as digital gain too). In this case the advertised digital gain will settle to 1 / min(red_gain, blue_gain). This means that one of the colour channels - just not the green one - is having unity digital gain applied to it.

* The AEC/AGC is changing. When the AEC/AGC is moving the digital gain will typically vary to some extent to try and smooth out any fluctuations, but it will quickly settle back to its normal value.
