== Application Notes

=== Creating Timelapse Video

To create a time-lapse video, you simply configure the Raspberry Pi to take a picture at a regular interval, such as once a minute, then use an application to stitch the pictures together into a video. There are a couple of ways of doing this.

==== Using `libcamera-still` or `raspistill` Timelapse Mode

Both `libcamera-still` and `raspistill` have a built in time-lapse mode, using the `--timelapse` command line switch. The value that follows the switch is the time between shots in milliseconds:

----
libcamera-still -t 30000 --timelapse 2000 -o image%04d.jpg
----

or

----
raspistill -t 30000 --timelapse 2000 -o image%04d.jpg
----

[NOTE]
====
The `%04d` in the output filename: this indicates the point in the filename where you want a frame count number to appear. So, for example, the command above will produce a capture every two seconds (2000ms), over a total period of 30 seconds (30000ms), named image0001.jpg, image0002.jpg, and so on, through to image0015.jpg.

The `%04d` indicates a four-digit number, with leading zeros added to make up the required number of digits. So, for example, `%08d` would result in an eight-digit number. You can miss out the `0` if you don't want leading zeros.

If a timelapse value of 0 is entered, the application will take pictures as fast as possible. Note that there's an minimum enforced pause of approximately 30 milliseconds between captures to ensure that exposure calculations can be made.
====

==== Automating using `cron` Jobs

A good way to automate taking a picture at a regular interval is using `cron`. Open the cron table for editing:

----
crontab -e
----

This will either ask which editor you would like to use, or open in your default editor. Once you have the file open in an editor, add the following line to schedule taking a picture every minute (referring to the Bash script from the xref:camera.adoc#raspistill[raspistill page], though you can use `libcamera-still` in exactly the same way):

----
* * * * * /home/pi/camera.sh 2>&1
----

Save and exit and you should see the message:

----
crontab: installing new crontab
----

Make sure that you use e.g. `%04d` to ensure that each image is written to a new file: if you don't, then each new image will overwrite the previous file.

==== Stitching Images Together

Now you'll need to stitch the photos together into a video. You can do this on the Raspberry Pi using `ffmpeg` but the processing will be slow. You may prefer to transfer the image files to your desktop computer or laptop and produce the video there.

First you will need to install `ffmpeg` if it's not already installed.

----
sudo apt install ffmpeg
----

Now you can use the `ffmpeg` tool to convert your JPEG files into an mp4 video:

----
ffmpeg -r 10 -f image2 -pattern_type glob -i 'image*.jpg' -s 1280x720 -vcodec libx264 timelapse.mp4
----

On a Raspberry Pi 3, this can encode a little more than two frames per second. The performance of other Raspberry Pi models will vary. The parameters used are:

* `-r 10` Set frame rate (Hz value) to ten frames per second in the output video.
* `-f image2` Set ffmpeg to read from a list of image files specified by a pattern.
* `-pattern_type glob` When importing the image files, use wildcard patterns (globbing) to interpret the filename input by `-i`, in this case `image*.jpg`, where `*` would be the image number.
* `-i 'image*.jpg'` The input file specification (to match the files produced during the capture).
* `-s 1280x720` Scale to 720p. You can also use 1920x1080, or lower resolutions, depending on your requirements.
* `-vcodec libx264` Use the software x264 encoder.
* `timelapse.mp4` The name of the output video file.

`ffmpeg` has a comprehensive parameter set for varying encoding options and other settings. These can be listed using `ffmpeg --help`.
