== V4L2 Drivers

V4L2 drivers provide a standard Linux interface for accessing camera and codec features. They are loaded automatically when the system is started, though in some non-standard situations you may need to xref:camera_software.adoc#if-you-do-need-to-alter-the-configuration[load camera drivers explicitly].

=== Driver differences when using `libcamera` or the legacy stack

On systems using `libcamera`, `/dev/video0` and `/dev/video1` are V4L2 drivers for Unicam, the Raspberry Pi's CSI-2 receiver. The Raspberry Pi has two CSI-2 receivers, each managed by one of these device nodes.

On systems using the legacy stack, `/dev/video0` is a V4L2 driver that gives access to the full camera system using the proprietary Broadcom driver on the GPU. There is no `/dev/video1`. There are no Unicam drivers, though there is a legacy _MMAL Rawcam_ component.

The other device nodes are always the same, and are listed in the table below.

[cols="1,^3"]
|===
| /dev/videoX | Default Action

| video10
| Video decode.

| video11
| Video encode.

| video12
| Simple ISP. Can perform conversion and resizing between RGB/YUV formats, and also Bayer to RGB/YUV conversion.

| video13
| Input to fully programmable ISP.

| video14
| High resolution output from fully programmable ISP.

| video15
| Low result output from fully programmable ISP.

| video16
| Image statistics from fully programmable ISP.

| video19
| HEVC Decode
|===

=== Using the Driver

Please see the https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/v4l2.html[V4L2 documentation] for details on using this driver.
