// Included from both silicon.adoc and pico-series.adoc

== Documentation

Documentation for Pico-series and other Raspberry Pi microcontroller-based boards.

=== RP2350

https://pip.raspberrypi.com/documents/RP-008373-DS[RP2350 Datasheet]:: A microcontroller by Raspberry Pi

https://pip.raspberrypi.com/documents/RP-008280-DS[Hardware design with RP2350]:: Using RP2350 microcontrollers to build boards and products

=== RP2040

https://pip.raspberrypi.com/documents/RP-008371-DS[RP2040 Datasheet]:: A microcontroller by Raspberry Pi

https://pip.raspberrypi.com/documents/RP-008279-DS[Hardware design with RP2040]:: Using RP2040 microcontrollers to build boards and products

=== Raspberry Pi Pico 2

https://pip.raspberrypi.com/documents/RP-008299-DS[Raspberry Pi Pico 2 Datasheet]:: An RP2350-based microcontroller board

https://pip.raspberrypi.com/documents/RP-008373-DS[Getting started with Raspberry Pi Pico-series Microcontrollers]:: C/{cpp} development with Raspberry Pi Pico-series devices and other Raspberry Pi microcontroller-based boards

=== Raspberry Pi Pico

https://pip.raspberrypi.com/documents/RP-008307-DS[Raspberry Pi Pico Datasheet]:: An RP2040-based microcontroller board

https://pip.raspberrypi.com/documents/RP-008373-DS[Getting started with Raspberry Pi Pico-series Microcontrollers]:: C/{cpp} development with Raspberry Pi Pico-series devices and other Raspberry Pi microcontroller-based boards

=== Raspberry Pi Pico 2 W

https://pip.raspberrypi.com/documents/RP-008304-DS[Raspberry Pi Pico 2 W Datasheet]:: An RP2350-based microcontroller board with wireless

https://pip.raspberrypi.com/documents/RP-008257-DS[Connecting to the Internet with Raspberry Pi Pico W-series]:: Getting Raspberry Pi Pico W-series devices online with C/{cpp} or MicroPython

=== Raspberry Pi Pico W

https://pip.raspberrypi.com/documents/RP-008312-DS[Raspberry Pi Pico W Datasheet]:: An RP2040-based microcontroller board with wireless

https://pip.raspberrypi.com/documents/RP-008257-DS[Connecting to the Internet with Raspberry Pi Pico W-series]:: Getting Raspberry Pi Pico W-series devices online with C/{cpp} or MicroPython

=== Software Development

https://pip.raspberrypi.com/documents/RP-009085-KB[Raspberry Pi Pico C/{cpp} SDK]:: Libraries and tools for C/{cpp} development on Raspberry Pi microcontrollers

https://pip.raspberrypi.com/documents/RP-008355-DS[Raspberry Pi Pico Python SDK]:: A MicroPython environment for Raspberry Pi microcontrollers

The API level Doxygen documentation for the Raspberry Pi Pico C/{cpp} SDK is also available https://rpltd.co/pico-doxygen[as a micro-site].

