== Audio

Raspberry Pi OS has multiple audio output modes: HDMI 1, the headphone jack (if your device has one), and USB audio.

By default, Raspberry Pi OS outputs audio to HDMI 1. If no HDMI output is available, Raspberry Pi OS outputs audio to the headphone jack or a connected USB audio device.

=== Change audio output

Use the following methods to configure audio output in Raspberry Pi OS:

[[pro-audio-profile]]

[tabs]
======
Desktop volume control::
+
Right-click the volume icon on the system tray to open the **audio output selector**. This interface lets you choose an audio output device. Click an audio output device to switch audio output to that device.
+
You may see a device profile named **Pro Audio** when viewing an audio device in the audio output selector. This profile exposes the maximum number of channels across every audio device, allowing you greater control over the routing of signals. Unless you require fine-tuned control over audio output, use a different device profile.
+
For more information about the Pro Audio profile, visit https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/FAQ#what-is-the-pro-audio-profile[PipeWire's FAQ].

`raspi-config`::
+
To change your audio output using xref:configuration.adoc#raspi-config[`raspi-config`], run the following command:
+
[source,console]
----
$ sudo raspi-config
----
+
You should see a configuration screen. Complete the following steps to change your audio output:
+
. Select `System options` and press `Enter`.
+
. Select the `Audio` option and press `Enter`.
+
. Select your required mode and press `Enter` to select that mode.
+
. Press the right arrow key to exit the options list. Select `Finish` to exit the configuration tool.
======


