== `boot` folder contents

Raspberry Pi OS stores boot files on the first partition of the SD card, formatted with the FAT file system.

On startup, each Raspberry Pi loads various files from the boot partition in order to start up the various processors before the Linux kernel boots.

On boot, Linux mounts the boot partition as `/boot/firmware/`.

NOTE: Prior to _Bookworm_, Raspberry Pi OS stored the boot partition at `/boot/`. Since _Bookworm_, the boot partition is located at `/boot/firmware/`.

=== `bootcode.bin`

The bootloader, loaded by the SoC on boot. It performs some very basic setup, and then loads one of the `start*.elf` files.

The Raspberry Pi 4 and 5 do not use `bootcode.bin`. It has been replaced by boot code in the xref:raspberry-pi.adoc#raspberry-pi-boot-eeprom[onboard EEPROM].

=== `start*.elf`

Binary firmware blobs loaded onto the VideoCore GPU in the SoC, which then take over the boot process.

`start.elf`:: the basic firmware.
`start_x.elf`:: includes additional codecs.
`start_db.elf`:: used for debugging.
`start_cd.elf`:: a cut-down version of the firmware that removes support for hardware blocks such as codecs and 3D as well as debug logging support; it also imposes initial frame buffer limitations. The cut-down firmware is automatically used when `gpu_mem=16` is specified in `config.txt`.

`start4.elf`, `start4x.elf`, `start4db.elf` and `start4cd.elf` are equivalent firmware files specific to the Raspberry Pi 4-series (Model 4B, Pi 400, Compute Module 4 and Compute Module 4S).

For more information on how to use these files, see the xref:config_txt.adoc#boot-options[`config.txt` documentation].

The Raspberry Pi 5 does not use `elf` files. The firmware is self-contained within the bootloader EEPROM.

=== `fixup*.dat`

Linker files found in matched pairs with the `start*.elf` files listed in the previous section.

=== `cmdline.txt`

The <<kernel-command-line-cmdline-txt,kernel command line>> passed into the kernel at boot.

=== `config.txt`

Contains many configuration parameters for setting up the Raspberry Pi. For more information, see the xref:config_txt.adoc[`config.txt` documentation].

IMPORTANT: Raspberry Pi 5 requires a non-empty `config.txt` file in the boot partition.

=== `issue.txt`

Text-based housekeeping information containing the date and git commit ID of the distribution.

=== `initramfs*`

Contents of the initial ramdisk. This loads a temporary root file system into memory before the real root file system can be mounted.

Since _Bookworm_, Raspberry Pi OS includes an `initramfs` file by default. To enable the initial ramdisk, configure it in xref:config_txt.adoc[`config.txt`] with the xref:config_txt.adoc#auto_initramfs[`auto_initramfs`] keyword.

=== `ssh` or `ssh.txt`

When this file is present, enables SSH at boot. SSH is otherwise disabled by default. The contents do not matter. Even an empty file enables SSH.

=== Device Tree blob files (`*.dtb`)

Device tree blob files contain the hardware definitions of the various models of Raspberry Pi. These files set up the kernel at boot xref:configuration.adoc#part3.1[based on the detected Raspberry Pi model].

=== Kernel files (`*.img`)

Various xref:linux_kernel.adoc#kernel[kernel] image files that correspond to Raspberry Pi models:

|===
| Filename | Processor | Raspberry Pi model | Notes

| `kernel.img`
| BCM2835
| Pi Zero, Pi 1, CM1
|

| `kernel7.img`
| BCM2836, BCM2837
| Pi Zero 2 W, Pi 2, Pi 3, CM3, Pi 3+, CM3+
| Later revisions of Pi 2 use BCM2837

| `kernel7l.img`
| BCM2711
| Pi 4, CM4, CM4S, Pi 400
| Large Physical Address Extension (LPAE)

| `kernel8.img`
| BCM2837, BCM2711, BCM2712
| Pi Zero 2 W, Pi 2 (later revisions), Pi 3, CM3, Pi 3+, CM3+, Pi 4, CM4, CM4S, Pi 400, CM5, Pi 5, Pi 500, Pi 500+
| xref:config_txt.adoc#boot-options[64-bit kernel]. Earlier revisions of Raspberry Pi 2 (with BCM2836) do not support 64-bit kernels.

| `kernel_2712.img`
| BCM2712
| Pi 5, CM5, Pi 500, Pi 500+
| Pi 5-optimized xref:config_txt.adoc#boot-options[64-bit kernel].
|===

NOTE: `lscpu` reports a CPU architecture of `armv7l` for systems running a 32-bit kernel, and `aarch64` for systems running a 64-bit kernel. The `l` in the `armv7l` case refers to little-endian CPU architecture, not `LPAE` as is indicated by the `l` in the `kernel7l.img` filename.

=== `overlays` folder

Contains Device Tree overlays. These are used to configure various hardware devices, such as third-party sound boards. Entries in `config.txt` select these overlays. For more information, see xref:configuration.adoc#part2[Device Trees, overlays and parameters].
