== Rotating your Display

The options to rotate the display of your Raspberry Pi depend on whether you're booting to the desktop environment or booting to the CLI (text console).

=== Rotating the desktop environment

If you are running the Raspberry Pi desktop then rotation is most easily achieved by using the `Screen Configuration Utility` from the desktop `Preferences` menu. This will bring up a graphical representation of the display or displays connected to the Raspberry Pi. Right click on the display you wish to rotate and select the required option.

It is also possible to change these settings using the command line, although the method for doing this depends on whether you're running the Wayland or X11 backend. Type
[,bash]
----
ps ax | grep [w]ayfire
----
into a Terminal window, and if you get `/usr/bin/wayfire` displayed then you're running Wayland, and if you get no output you're running X11.

NOTE: In the current version of Raspberry Pi OS Bookworm, Raspberry Pi 4 and 400 default to using Wayland to display the desktop environment; whereas earlier models of Raspberry Pi default to using X11 to display the desktop environment.

==== Rotating the desktop environment using Wayland

Under Wayland you can rotate the display using the `wlr-randr` command. The following commands give give 0°, 90°, 180° and 270° rotations respectively.

[,bash]
----
wlr-randr --output HDMI-A-1 --transform normal
wlr-randr --output HDMI-A-1 --transform 90
wlr-randr --output HDMI-A-1 --transform 180
wlr-randr --output HDMI-A-1 --transform 270
----

Note that the `--output` entry specifies to which device the rotation applies. You can determine the device name by typing `kmsprint | grep Connector` on the command line which will display information for all attached devices.

NOTE: If running this command over SSH, you'll need to prefix `wlr-randr` with `WAYLAND_DISPLAY=wayland-1`, e.g. `WAYLAND_DISPLAY=wayland-1 wlr-randr --output HDMI-A-1 --transform 90`

You can also use one of the following `--transform` options to mirror the display at the same time as rotating it: `flipped`, `flipped-90`, `flipped-180`, `flipped-270`

==== Rotating the desktop environment using X11

Under X11 you can rotate the display using the `xrandr` command. The following commands give 0°, 90°, 180° and 270° rotations respectively.

[,bash]
----
xrandr --output HDMI-1 --rotate normal
xrandr --output HDMI-1 --rotate left
xrandr --output HDMI-1 --rotate inverted
xrandr --output HDMI-1 --rotate right
----

Note that the `--output` entry specifies to which device the rotation applies. You can determine the device name by typing `xrandr --listmonitors` on the command line which will display information for all attached devices.

NOTE: If running this command over SSH, you'll need to prefix `xrandr` with `DISPLAY=:0`, e.g. `DISPLAY=:0 wlr-randr --output HDMI-1 --rotate right`

You can also use the command line to mirror the display using the `--reflect` option. Reflection can be one of `normal`, `x`, `y` or `xy`. This causes the output contents to be reflected across the specified axes. For example:

[,bash]
----
xrandr --output HDMI-1 --reflect x
----

=== Rotating the text console

This is acheived by editing the KMS settings - see <<the-kernel-command-line,configuring the kernel command line>> for more details.

NOTE: If you have multiple screens connected, they must all be set to the same rotation value in console mode, or no rotation will be applied.

