== Configure display resolution and rotation

To configure your Raspberry Pi to use a non-default display mode, set the resolution or rotation manually.

=== Configure HDMI displays

With most HDMI monitors, Raspberry Pi OS uses the highest resolution and refresh rate supported by the monitor.

The Raspberry Pi Zero, Zero W and Zero 2 W have a mini HDMI port, so you need a mini-HDMI-to-full-size-HDMI lead or adapter.

Raspberry Pi 4, Raspberry Pi 5 and Raspberry Pi 400 have two micro HDMI ports, so you need a micro-HDMI-to-full-size-HDMI lead or adapter for each display you wish to attach. Connect the cables before turning on the Raspberry Pi.

Raspberry Pi 4 and 400 can drive up to two displays, with a resolution up to 1080p at a 60Hz refresh rate. These devices support two 4K displays at a 30Hz refresh rate. You can also drive a single display at 4K with a 60Hz refresh rate if you connect the display to the `HDMI0` port and set the `hdmi_enable_4kp60=1` flag in xref:../computers/config_txt.adoc#what-is-config-txt[`/boot/firmware/config.txt`].

Raspberry Pi 5 can drive up to two displays at 4K resolution at a 60hz refresh rate with no additional configuration.

The Screen Configuration tool (`arandr`) is a graphical tool for selecting display modes and setting up multiple displays. You can find this tool in the Desktop Preferences menu. Use the Layout menu option to select the screen, resolution, and orientation. If you use a multi-screen setup, drag around the displays to any position you want. Click the **Apply** button to save your settings changes.

=== Set desktop environment resolution and rotation

==== via the desktop

On the Raspberry Pi Desktop, open the *Preferences* menu and select the **Screen Configuration** utility. You should see a graphical representation of the displays connected to the Raspberry Pi. Right click on the display you wish to modify, and select an option. Click **Apply** to and close **Screen Configuration** to save your changes.

==== via CLI

Use the following command to open the **Screen Configuration** utility:

[source,console]
----
$ arandr
----

You should see a graphical representation of the displays connected to the Raspberry Pi. Right click on the display you wish to modify, and select an option. Click **Apply** to and close **Screen Configuration** to save your changes.

==== Set a custom display resolution in Wayland

If you run the Wayland desktop compositor, you can set a custom display resolution by editing the `.config/wayfire.ini` file in your home directory. Edit the existing `[output:<device>]` section, or add a new `[output:<device>]` section for your display device if one doesn't exist. For example, the following example shows a configuration for an HDMI device with a resolution of 1080p at 60Hz:

----
[output:HDMI-A-1]
mode = 1920x1080@60
----

The text that comes after `output:` should match the <<the-kernel-command-line,KMS display options>>.

For information about supported modes and the `mode` syntax, see the https://github.com/WayfireWM/wayfire-wiki/blob/master/Configuration.md#output-configuration[Wayfire documentation].

Add the same configuration to `/usr/share/greeter.ini` to configure a resolution for the login screen.

==== Set a custom display rotation in Wayland

If you run the Wayland desktop compositor, you can set a custom display rotation by editing the `.config/wayfire.ini` file in your home directory.

To rotate your display, add a `transform` line:

----
[output:HDMI-A-1]
mode = 1920x1080@60
transform = 270
----

Wayland supports the following `transform` options:

* `normal`
* `90`
* `180`
* `270`

Add the same configuration to `/usr/share/greeter.ini` to configure a rotation for the login screen.

=== Configure console resolution and rotation

To change the resolution and rotation of your Raspberry Pi in console mode, use the KMS settings. For more information, see <<the-kernel-command-line,configuring the kernel command line>>.

NOTE: When using console mode with multiple displays, all connected displays share the same rotation settings.
