== Displays

To configure your Raspberry Pi to use a non-default display mode, set the resolution or rotation manually.

=== Support for HDMI monitors

With most HDMI monitors, Raspberry Pi OS uses the highest resolution and refresh rate supported by the monitor.

The Raspberry Pi Zero, Zero W and Zero 2 W have a mini HDMI port, so you need a mini-HDMI-to-full-size-HDMI lead or adapter.

Flagship models since Raspberry Pi 4B and Keyboard models have two micro HDMI ports, so you need a micro-HDMI-to-full-size-HDMI lead or adapter for each display you wish to attach. Connect the cables before turning on the Raspberry Pi.

Flagship models since Raspberry Pi 4B, Compute Modules since CM4 (except for CM4S), and Keyboard models can drive up to two displays.

Raspberry Pi 4, 400, and Compute Module 4 devices support resolutions up to 1080p at a 60 Hz refresh rate, or two 4K displays at a 30 Hz refresh rate. You can also use a single display at 4K with a 60 Hz refresh rate if you connect the display to the `HDMI0` port and set the `hdmi_enable_4kp60=1` flag in xref:../computers/config_txt.adoc#what-is-config-txt[`/boot/firmware/config.txt`].

Raspberry Pi 5, 500, 500+, and Compute Module 5 devices support up to two displays at 4K resolution at a 60 Hz refresh rate with no additional configuration.

=== Set resolution and rotation

Raspberry Pi OS editions that include the desktop enable you to adjust your display resolution and screen orientation directly through the desktop environment using the *Control Centre*.

IMPORTANT: Raspberry Pi OS Bookworm and earlier used `raindrop` or `arandr` to configure display behaviours. The latest version of Raspberry Pi OS doesn't support these tools.

==== Using the desktop

In the Raspberry Pi OS desktop, use the *Control Centre* to set your display preferences. These settings persist across a reboot.

. Open the main application menu by selecting the Raspberry Pi icon.
. Go to *Preferences > Control Centre*.
. In *Control Centre*, go to the *Screens* tab.
. Select the screen you want to configure by one of these methods:
** In the panel in the tab, right-click the outline of the screen you want to configure.
** From the *Screens* list, select the screen you want to configure, for example, *HDMI-A-1*.
. From the submenu, you can configure the following properties:
** Resolution
** Frequency
** Orientation
** Scaling
+
The panel in the tab shows a preview of the changes you're about to apply.
. To apply the changes to your desktop, select *Apply*.
+
Raspberry Pi OS displays your changes for 10 seconds and shows a dialog that asks you to confirm the changes are correct.
. To confirm your changes, select *OK*. If you don't confirm your changes, the display reverts to the previous settings.

=== Console resolution and rotation

This section applies to Raspberry Pi OS Lite or systems without a desktop environment.

Use the terminal only to check display information or when running in console mode.

To change resolution and rotation in console mode, configure Kernel Mode Setting (KMS). For details, see <<kernel-command-line-cmdline-txt,configuring the kernel command line>>.

NOTE: When using console mode with multiple displays, all connected displays share the same rotation settings.