== HDMI configuration

In the vast majority of cases, plug your Raspberry Pi into a HDMI-equipped monitor using a standard HDMI cable to automatically use the best resolution that monitor can support. The Raspberry Pi Zero, Zero W and Zero 2 W use a mini HDMI port, so you need a mini-HDMI-to-full-size-HDMI lead or adapter. On Raspberry Pi 4, Raspberry Pi 5 and Raspberry Pi 400 there are two micro HDMI ports, so you need a micro-HDMI-to-full-size-HDMI lead or adapter for each display you wish to attach. Connect the cables before turning on the Raspberry Pi.

Raspberry Pi 4 and 400 can drive up to two displays, with a resolution up to 1080p at a 60Hz refresh rate. At 4K resolution, if you connect two displays then you are limited to a 30Hz refresh rate. You can also drive a single display at 4K with a 60Hz refresh rate: this requires that the display is attached to the HDMI port adjacent to the USB-C power input (labelled HDMI0). To enable 4Kp60 output on the Raspberry Pi 4 and 400, set the `hdmi_enable_4kp60=1` flag in `/boot/firmware/config.txt`.

Raspberry Pi 5 can drive up to two displays at 4K resolution at a 60hz refresh rate with no additional configuration.

The Screen Configuration tool (`arandr`) is a graphical tool for selecting display modes and setting up multiple displays. You can find this tool in the Desktop Preferences menu. Use the Layout menu option to select the screen, resolution, and orientation. If you use a multi-screen setup, drag around the displays to any position you want. Click the Apply button to apply the settings.

