== Keyboard, system, and localisation
This section covers how to:

* <<shortcuts>>. View, edit, add, and delete key combinations that perform specified actions on your Raspberry Pi from the desktop.
* <<browser>>. Choose between Chromium or Firefox from the desktop or from the interactive `raspi-config` TUI; the default browser if you don't choose one during installation is Chromium.
* Configure localisation settings from the desktop or from the interactive `raspi-config` TUI, including how to:
** <<locale>>, which are the system-wide language and regional settings (country and character set).
** <<timezone>>, which is determined by the geographic area and city used to set the local time.
** <<keyboard>> by specifying the physical model, language arrangement, and key variants of your keyboard.
* Configure advanced system settings using the interactive `raspi-config` TUI, including how to:
** <<expand-filesystem>>, which might be useful if you've cloned your OS to a larger storage device and you're using an OS that doesn't auto-expand the filesystem to make use of the space.
** <<logging>>, which is used to set a storage location for logs.
** <<beta>>, which you can turn on if you're an opt-in tester user of Raspberry Pi OS.
** <<wayland>>. We don't recommend switching to X11 because we are no longer developing for it.

If you're looking for instructions for how to set the WLAN country on your Raspberry Pi, see xref:../computers/configuration.adoc#wlan-country[Enable wireless networking instead]. The instructions for setting WLAN country is in the *Wireless connection* section because it's a prerequisite for connecting to a wireless network.

[[shortcuts]]
=== Manage keyboard shortcuts
A keyboard shortcut is a defined combination of key presses that initiate an action on your computer.

You can only configure a shortcut to initiate one action, but a single action can be initiated by multiple shortcuts. For example, you might have two shortcuts, *Alt+F4* and *Ctrl+W*, that both close a window. If you attempt to assign another action to either of these shortcuts, or if you attempt to create the same shortcut twice, the new shortcut action overwrites the old one.

[[configure-shortcut]]
==== Shortcut configuration
Configuring a shortcut involves assigning a key combination to a system action. You can configure a shortcut using a *Preset* (a predefined action) or an *Action* (a user-defined action). For instructions, see <<edit-shortcut>> or <<add-shortcut>>.

===== Preset

A preset is an action that's predefined by Raspberry Pi, such as *Open Terminal* or *Show Shutdown Options*. When you choose a preset for your shortcut, the appropriate command is auto-filled in the *Command* text box. For example, the predefined command for *Open Terminal* is `lab-sensible-terminal`.

===== Action

An action is more flexible; it allows you to define custom system actions that aren't already defined by Raspberry Pi, such as *NextWindow* and *HideCursor*.

Some actions require additional input, which you're prompted to provide after choosing the action. If an action requires no additional input, no parameter options or text boxes are displayed. If an action requires additional input, a dropdown menu with predefined parameter options or a free-text entry box appears, depending on the action selected:

* *Fixed parameter list.* Actions such as *Maximize* or *SnapToEdge* require that you choose an option from a list of parameters. For example, choosing *Maximise* as an action for your shortcut reveals a *Direction* list with options for *both*, *horizontal*, or *vertical*.
* *Free-text entry.* Actions such as *Execute* or *ShowMenu* display a text box for custom input. For example, choosing *Execute* as an action for your shortcut reveals a *Command* text box where you enter a command that you would otherwise enter into the Terminal, such as *vlc* to open VLC Media Player.

For a list of actions, follow the instructions in <<view-shortcuts>>, and then select *Help* in the bottom-right corner of the *Shortcuts* tab. This opens a list of `labwc` actions that can be assigned to menus, keyboard shortcuts, and mouse bindings. Every action available in the *Actions* menu when you create or edit a shortcut is documented in this `labwc` actions list.

[[view-shortcuts]]
==== View existing keyboard shortcuts
To view existing keyboard shortcuts:

. Select the Raspberry Pi icon in the top-left corner of the system tray and then go to *Preferences > Control Centre*.
. Open the *Shortcuts* tab in the left-side menu.

This opens a table of existing keyboard shortcuts, with two columns:

* The *Key* column on the left displays the key combination that initiates an action. Each key in the combination is separated with a hyphen, for example, *Alt-Shift-Tab*.
* The *Function* column on the right displays the action that the corresponding key combination initiates, for example, *Previous Window*.

Select *Close* in the bottom-right corner of the *Control Centre* when you're done.

[[edit-shortcut]]
==== Edit a keyboard shortcut
The following instructions provide steps for changing the behaviour of an existing keyboard shortcut, including:

* Whether the shortcut is activated before or after the key combination is released. The default is to initiate the shortcut's action as soon as your Raspberry Pi detects the key combination.
* The action initiated by the keyboard shortcut, which can be a preset or an action, described in <<configure-shortcut>>.

If you want to change the keyboard shortcut itself, you must instead <<delete-shortcut, delete the existing shortcut>> and then <<add-shortcut, add the new shortcut with the intended action>>.

To edit the behaviour of an existing keyboard shortcut:

. Select the Raspberry Pi icon in the top-left corner of the system tray and then go to *Preferences > Control Centre*.
. Open the *Shortcuts* tab in the left-side menu.
. Select the keyboard shortcut that you want to edit.
. Select *Edit* at the bottom of the window. This opens an *Edit Shortcut* window.
. Choose whether you want the shortcut to take effect before or after you release any of the keys in the key combination.
** If you want the shortcut to take effect after you've released any the keys in the key combination, select *Activate on Release*.
** If you want the shortcut to take effect as soon as the full key combination is pressed, leave *Activate on Release* unselected.
. Choose either a *Preset* or an *Action*. If you choose an action, provide any required additional input when prompted. For more information about presets and actions, see <<configure-shortcut>>.
. Select *OK* in the bottom-right corner of the *Edit Shortcut* window when you're done.
. Select *Close* in the bottom-right corner of the *Control Centre*.

[[add-shortcut]]
==== Add a keyboard shortcut
To add a new keyboard shortcut:

. Select the Raspberry Pi icon in the top-left corner of the system tray and then go to *Preferences > Control Centre*.
. Open the *Shortcuts* tab in the left-side menu.
. Check that the shortcut you want to add isn't already in the table. If you create the same shortcut with a different action, the new shortcut action overwrites the old shortcut action.
. Select *New* at the bottom of the window. This opens an *Edit Shortcut* window.
. Enter the key combination that you want to use as your shortcut and then release them.
. Choose whether you want the shortcut to take effect before or after you release any of the keys in the key combination.
** If you want the shortcut to take effect after you've released any the keys in the key combination, select *Activate on Release*.
** If you want the shortcut to take effect as soon as the full key combination is pressed, leave *Activate on Release* unselected.
. Choose either a *Preset* or an *Action*. If you choose an action, provide any required additional input when prompted. For more information about presets and actions, see <<configure-shortcut>>.
. Select *OK* in the bottom-right corner of the *Edit Shortcut* window when you're done.
. Select *Close* in the bottom-right corner of the *Control Centre*.

[[delete-shortcut]]
==== Delete a keyboard shortcut
To delete an existing keyboard shortcut:

. Select the Raspberry Pi icon in the top-left corner of the system tray and then go to *Preferences > Control Centre*.
. Open the *Shortcuts* tab in the left-side menu.
. Select the keyboard shortcut that you want to delete.
. Select *Delete* at the bottom of the window. This opens a confirmation window.
. Select *OK* in the bottom-right corner of the confirmation window.
. Select *Close* in the bottom-right corner of the *Control Centre*.

[[browser]]
=== Change the default browser
You can change the default browser on your Raspberry Pi through the desktop and using the interactive `raspi-config` TUI. You can choose between *Chromium* and *Firefox*.

[tabs]
======
Desktop::
. Select the Raspberry Pi icon in the top-left corner of the system tray and then go to *Preferences > Control Centre*.
. Open the *System* tab in the left-side menu.
. Choose between *Chromium* and *Firefox*.
. Select *Close* in the bottom-right corner of the *Control Centre*.
raspi-config::
. Open the Terminal and run `sudo raspi-config`.
. Use the keyboard to navigate to and select `1 System Options > S9 Browser`.
. Choose between `Chromium` and `Firefox`.
. Select `<OK>` and then `<OK>` again.
. Select `<Finish>` when you're done.
======

[[locale]]
=== Configure locale settings
Locales are a framework to switch between multiple languages and regions. They allow your Raspberry Pi to display your preferred language, date formats, currency symbols, and character sets. *UTF-8* locales are selected by default for new installations. *C*, *C.UTF-8*, and *POSIX* locales are also available, and you can also generate others to suit your needs.

When you configure your locale settings, you're configuring a system-wide default locale, which changes the language for all users of your Raspberry Pi.

Configuring locale from the desktop involves setting the following separately:

* Language, for example, *en* for English.
* Region (country), for example, *GB* for Great Britain.
* Character set (the character encoding standard for modern web and OS), for example, *UTF-8* for Unicode support.

Configuring locale using the `raspi-config` TUI involves setting the language, region, and character set with one string. For example, *en_GB.UTF-8* sets the locale to British English with UTF-8 character encoding.

[tabs]
======
Desktop::
. Select the Raspberry Pi icon in the top-left corner of the system tray and then go to *Preferences > Control Centre*.
. Open the *Localisation* tab in the left-side menu.
. Select *Set Locale* next to *Locale*.
. Choose your language from the *Language* dropdown menu, for example, *en (English)*.
. Choose your country from the *Country* dropdown menu, for example, *GB (United Kingdom)*.
. Choose one of the available character sets from the *Character Set* dropdown menu, for example, *UTF-8*.
. Select *OK* in the bottom-right corner of the *Locale* window.
. Select *Close* in the bottom-right corner of the *Control Centre*.
. Reboot your Raspberry Pi for the changes to take effect.
raspi-config::
. Open the Terminal and run `sudo raspi-config`.
. Use the keyboard to navigate to and select `5 Localisation > L1 Locale`.
. Select `<OK>` to continue.
. Select the locales that you want to install onto your Raspberry Pi (you can select more than one).
.. Navigate down the list to highlight the appropriate combination of language, country, and character set to install. For example, `en_GB.UTF-8 UTF-8` means the English language as used in Great Britain using the UTF-8 character set.
.. Use the *Space* key on your keyboard to select the highlighted combination of language, country, and character set to install.
.. Your selections are indicated by an asterisk inside square brackets to the left of the locale name in the list.
. Use the *Tab* key on your keyboard to exit the list and select `<OK>`.
. Select the default locale for the system environment, for example, `None`, `C.UTF-8`, or `en_GB.UTF-8`.
. Select `<OK>` and then `<Finish>` when you're done.
. Reboot your Raspberry Pi for the changes to take effect.
======

[[timezone]]
=== Configure time zone
Configuring your time zone involves first selecting a geographic region (for example, *Europe*) and then selecting the city that corresponds with your time zone based on where that city is located (for example, *London*). Selecting the correct time zone handles daylight saving time transitions automatically.

[tabs]
======
Desktop::
. Select the Raspberry Pi icon in the top-left corner of the system tray and then go to *Preferences > Control Centre*.
. Open the *Localisation* tab in the left-side menu.
. Select *Set Timezone* next to *Timezone*.
. Choose the appropriate geographic area from the *Area* dropdown menu. For example, if you live in the UK, select *Europe*.
. Choose the appropriate city that corresponds to your time zone. For example, if you live in the UK, select *London*.
. Select *OK* in the bottom-right corner of the *Timezone* window.
. Select *Close* in the bottom-right corner of the *Control Centre*.
raspi-config::
. Open the Terminal and run `sudo raspi-config`.
. Use the keyboard to navigate to and select `5 Localisation > L2 Timezone`.
. Select `<OK>` to continue.
. Navigate down the list to highlight the appropriate geographic area. For example, if you live in the UK, highlight `Europe`.
. Use the *Tab* key on your keyboard to exit the list and select `<OK>`.
. Navigate down the list to highlight the appropriate city that corresponds to your time zone. For example, if you live in the UK, highlight `London`.
. Use the *Tab* key on your keyboard to exit the list and select `<OK>`.
. Select `<Finish>` when you're done.
======

[[keyboard]]
=== Configure your keyboard

You can customise and configure your keyboard by changing any of the following settings:

* *Model.* The physical hardware design and number of keys on your device. For example, choose *Generic 105-key PC* if you have a standard full-sized keyboard with numeric keypad.
* *Layout.* The primary language and symbol arrangement assigned to the keys on your keyboard. For example, choose *English (UK)* for a layout where the *"* and *@* symbols are swapped compared to a US keyboard.
    ** You can also choose an *Alternate Layout*, available only through the desktop Control Centre. This is an alternative keyboard layout that you can switch to using a toggle key that you specify. For example, you can choose *English (US)* as your alternative layout.
    ** If you choose an alternative layout, set a *Toggle Key* to switch between the *Layout* and any *Alternate Layout* you've set. This configuration is only available through the desktop Control Centre, and involves specifying a key or key combination such as *Ctrl + Alt*.
    ** Optionally, set an *Indicator* (a keyboard LED) for when an *Alternate Layout* is active, available only through the desktop Control Centre. Typically, this is either *Caps*, *Num*, or *Scroll*.
* *Variant.* Available only through the desktop Control Centre.
    ** Choose specific modification of a layout for specialised hardware or regional preferences. For example, choose *English (UK, Macintosh)* for Apple keyboards where the *Alt* and *Cmd* keys are remapped. If you don't have a specific modification, the variant is the same as the layout.
    ** You can also choose an *Alternative Variant*, which is a specific modification of a layout for specialised hardware or regional preferences. For example, choose *Cherokee* for Cherokee English.
* *AltGr*. Available only through `sudo raspi-config` in the Terminal. A modifier key used to input some characters that are unusual for the language of the keyboard layout, such as foreign currency symbols and accented letters.

Because the desktop *Control Centre* and `sudo raspi-config` each have their own configuration settings, you might have to follow both procedures to complete your keyboard customisation.

[tabs]
======
Desktop::
. Select the Raspberry Pi icon in the top-left corner of the system tray and then go to *Preferences > Control Centre*.
. Open the *Localisation* tab in the left-side menu.
. Select *Set Keyboard* next to *Keyboard*.
. From the *Model* dropdown menu, choose the appropriate keyboard model.
. From the *Layout* dropdown menu, choose the appropriate keyboard layout.
. From the *Variant* dropdown menu, choose the appropriate keyboard variant.
. Optionally, select *Add alternate keyboard*. This reveals four more dropdown menus.
.. From the *Alternate Layout* dropdown menu, choose the layout of your alternate keyboard.
.. From the *Alternate Variant* dropdown menu, choose the variant of your alternate keyboard.
.. From the *Toggle Key* menu, choose which key or combination of keys allows you to switch between keyboard configurations, for example, *Left Alt + Caps*.
.. If you have a keyboard with indicator lights, from the *Indicator* dropdown menu, choose which LED on your keyboard lights up when the alternate keyboard is active: *None*, *Caps*, *Num*, or *Scroll*.
+
NOTE: Don't set *Num* as the indicator LED on the Raspberry Pi standalone USB keyboard or the Raspberry Pi 400. Doing so results in the keyboard generating letters instead of numbers on the right-side of the keyboard.
+
. Select *OK* in the bottom-right corner of the *Keyboard* window.
. Select *Close* in the bottom-right corner of the *Control Centre*.
. Reboot your Raspberry Pi for the changes to take effect.
raspi-config::
. Open the Terminal and run `sudo raspi-config`.
. Use the keyboard to navigate to and select `5 Localisation > L3 Keyboard`.
. Navigate down the list to highlight the appropriate *Keyboard model*.
. Use the *Tab* key on your keyboard to exit the list and select `<OK>`.
. Navigate down the list to highlight the appropriate *Keyboard layout*.
. Use the *Tab* key on your keyboard to exit the list and select `<OK>`.
. Choose a key to function as the *AltGr* key on your keyboard.
. Select `<OK>` to continue.
. Choose a compose key. This prompts your Raspberry Pi to interpret the next collection of keystrokes as a combination that creates a character not found on the keyboard. The compose key doesn't work in Unicode mode. If you're not in Unicode mode, regardless of what you choose at this point, you can always use *Control+Period* as the compose key.
. Select `<OK>` to continue.
. If you're using Wayland, select the default option, `<No>`, to continue. If you're using X, select `<Yes>` if you want to ensure that *Control+Alt+Backspace* ends the X server.
======

[[expand-filesystem]]
=== Expand the file system
Expanding your file system is an advanced option, typically only needed if you're moving to a larger boot media and you're not using Raspberry Pi OS. Expanding the OS partition allows your Raspberry Pi to use the full capacity of the new boot media.

In most cases, Raspberry Pi OS performs the expansion automatically on first boot.

WARNING: There is no confirmation step. When you choose to expand your file system, partition expansion starts immediately.

To expand the file system using the interactive `raspi-config` TUI:

. Open the Terminal and run `sudo raspi-config`.
. Use the keyboard to navigate to and select `6 Advanced Options > A1 Expand Filesystem`.
. `raspi-config` automatically resizes the root partition and then displays a confirmation that the file system will be expanded on the next reboot.
. Select `<OK>` and then `<Finish>` when you're done.
. Reboot your Raspberry Pi for the change to take effect.

[[logging]]
=== Configure logging
Logging is an advanced option, typically only needed if you need to change how system log data is stored or managed, for example, to reduce disk writes, retain logs across reboots, or disable logging for performance reasons.

To configure logging using the interactive `raspi-config` TUI:

. Open the Terminal and run `sudo raspi-config`.
. Use the keyboard to navigate to and select `6 Advanced Options > A12 Logging`.
. Choose between one of the following options:
** `1 Default`, which uses the system's default logging configuration.
** `2 Volatile`, which stores logs in RAM only, typically under `/run/log/journal`. Logs are temporary and cleared on reboot.
** `3 Persistent`, which stores logs on disk, typically under `/var/log/journal`, meaning logs survive reboots if you want to use them for troubleshooting over time. This mode also supports separate journal files for each user (log splitting).
** `4 Auto`, which automatically determines the appropriate logging behaviour based on system configuration and available storage. Persistent logging is used if `/var/log/journal` exists; volatile logging is used if `/var/log/journal` doesn't exist.
** `5 None`, which turns off system logging.
. Select `<OK>` and then `<OK>` again.
. Select `<Finish>` when you're done.

[[beta]]
=== Enable or disable beta access
Beta access allows you to use newer, pre-release software packages and bootloader updates that are still being tested. This option is intended for advanced users who want to try the latest features and help identify issues.

NOTE: This is different from using `rpi-update`, which provides untested firmware updates and should only be used when specifically advised. Beta access is a safer, opt-in way to test newer software from a dedicated repository.

To enable or disable beta access using the interactive raspi-config TUI:

. Open the Terminal and run `sudo raspi-config`.
. Use the keyboard to navigate to and select `6 Advanced Options > A6 Beta Access`.
. Choose between one of the following options:
** `B1 Beta Software`, which enables the beta repository and allows installation of newer, pre-release packages and the latest bootloader updates.
** `B2 Release Software`, which uses the standard, stable software repository recommended for most users.
. Select `<OK>` and then `<OK>` again.
. In a new Terminal, use `sudo apt update` to update your package list to apply the change.

[[wayland]]
=== Switch between Wayland and X11
From Raspberry Pi OS Bookworm onwards, all Raspberry Pi models run Wayland using `labwc` by default.

WARNING: We don't recommend switching from Wayland to X because we aren't actively developing X11.

To switch between Wayland and X11 using the interactive `raspi-config` TUI:

. Open the Terminal and run `sudo raspi-config`.
. Use the keyboard to navigate to and select `6 Advanced Options > A7 Wayland`.
. Choose between one of the following options:
** `W1 X11` (not recommended).
** `W2 Labwc` (Wayland, which is recommended).
. Select `<OK>` and then `<OK>` again.
. Select `<Finish>` when you're done.
