== Operational security

This section summarises common ways to improve the security of your Raspberry Pi. If you're looking for password instructions, see xref:../computers/configuration.adoc#users[User access and management].

=== Update Raspberry Pi OS
To get the latest security features, we recommend that you keep your software up to date. For more information, see  xref:os.adoc#update-software[Update your current Raspberry Pi software] in the *Raspberry Pi OS* page.

Only the most recent major release of Raspberry Pi OS contains all the latest security fixes. We therefore recommend that you also upgrade to the most recent major release when it becomes available (for example, from Bookworm to Trixie). This is different from _updating_ your Raspberry Pi OS , which installs the latest packages and security fixes within your current release without changing to a new major version. For instructions on upgrading your OS, see xref:../computers/os.adoc#upgrade[Upgrade to a new major version].

=== Automatically update your SSH server

If you use SSH to connect to your Raspberry Pi, it can be worthwhile to add a `cron` job that specifically updates the SSH server. The following command, perhaps run as a daily `cron` job, ensures you have the latest SSH security fixes promptly, independent of your normal update process.

[source,console]
----
$ apt install openssh-server
----

=== Improve SSH security

SSH is a common way to remotely access a Raspberry Pi. By default, SSH requires a username and password. To make SSH even more secure, use xref:remote-access.adoc#configure-ssh-without-a-password[key-based authentication].

==== Enable and disable SSH users

You can also *allow* or *deny* specific users by altering the `sshd` configuration.

[source,console]
----
$ sudo nano /etc/ssh/sshd_config
----

Add, edit, or append to the end of the file the following line, which contains the usernames you wish to allow to log in:

[source,bash]
----
AllowUsers alice bob
----

You can also use `DenyUsers` to specifically stop some usernames from logging in:

[source,bash]
----
DenyUsers jane john
----

After the change, restart the `sshd` service with the following command to put your changes into effect:

[source,console]
----
$ sudo systemctl restart ssh
----

=== Use a firewall
A firewall is a network security system that monitors and controls incoming and outgoing network traffic based on a defined set of security rules. This section introduces *Uncomplicated Firewall (UFW)*, a firewall tool that offers a simplified command-line interface for controlling network traffic through https://www.netfilter.org/projects/iptables/index.html[`iptables`]. There are also some graphical user interface (GUI) frontends available for UFW, such as GUFW, but `ufw` commands are typically run on the command line. This section provides an overview of, and basic instructions for, the UFW command-line interface.

==== Uncomplicated Firewall (UFW)
Network traffic is organised by port numbers, which are numerical labels used to direct data to specific applications. Firewalls control traffic by opening and closing particular ports to allow or block certain types of communication.

On Linux systems, network traffic is filtered through the kernel's firewall subsystem, called *netfilter*. Netfilter implements packet filtering; it blocks or allows data packets to pass through your system based on things like their source IP address, destination IP address, port number, protocol, and direction.

System administrators can interact with netfilter through `iptables`, which is the main command-line tool for defining packet filtering rules. However, `iptables` can be complex. https://www.linux.com/learn/introduction-uncomplicated-firewall-ufw[UFW (Uncomplicated Firewall)], the default firewall tool used by Ubuntu, simplifies firewall configuration and management. It acts as a wrapper for `iptables`, allowing system administrators to set firewall rules without dealing with the complexity of raw `iptables` commands.

==== UFW commands
UFW is a command-line program used to define firewall access rules. The typical syntax for ufw commands is: `sudo ufw [--dry-run] <command> [rule]`.

* All `ufw` commands require superuser privileges, and so must be preceded with `sudo`.
* Optionally, you can add `--dry-run` to simulate the `ufw` command without making actual changes.
* The `<command>` is the main action that you want to perform, such as `allow`.
* Depending on the command, you can optionally specify a `rule` to apply to the command, such as `allow 22`.

For example, `sudo ufw --dry-run allow 22` shows you the would-be outcome of allowing traffic on port 22, including the entire set of rules if the change were made.

==== Install and enable UFW
To use UFW, you must first install it onto your Raspberry Pi device. After installation, UFW is present but disabled, meaning that it doesn't block any traffic yet. This allows you to configure default access rules without locking yourself out. This is especially important if you're connected to your Raspberry Pi device over SSH (or any other remote method); to avoid being locked out, you must allow remote access before enabling UFW.

If you're connected over SSH, the recommended flow of actions is as follows:

[cols="1,6,5", options="header"]
|===
|Step |Description |Command

|1
|Update your package list.
|`sudo apt-get update`

|2
|Install UFW. Before UFW is enabled, the output says that UFW is inactive.
|`sudo apt install ufw`

|3
|Verify the installation by checking the status. For information about this command, see <<rule-management>>.
|`sudo ufw status`

|4
|Optionally (but recommended), configure default policies, such as denying all incoming traffic. Defaults apply globally.
|`sudo ufw default deny incoming`

|5
|To maintain remote access, allow SSH (before enabling UFW), either by specifying the service name (ssh) or the default port (22/tcp).
|`sudo ufw allow ssh` +
OR +
`sudo ufw allow 22/tcp`

|6
|Optionally, if you’re running a web server, allow HTTP and HTTPS traffic, either by specifying the service names (http and https) or their default ports (80/tcp and 443/tcp, respectively).
|`sudo ufw allow http` +
`sudo ufw allow https` +
OR +
`sudo ufw allow 80/tcp` +
`sudo ufw allow 443/tcp`

|7
|Enable UFW to activate the firewall and configure it to start up on boot.
|`sudo ufw enable`

|8
|Verify the status of the firewall and review the configured rules. For information about this command, see <<rule-management>>.
|`sudo ufw status verbose`
|===

You can disable UFW at any time, which stops it from starting up on boot. Use the following command to disable the UFW firewall:

[source,console]
----
$ sudo ufw disable
----

==== Use allow and deny rules

This section lists the basic commands for allowing and denying traffic through specified service names, ports, and services. The general `ufw` syntax for `allow` and `deny` commands are as follows:

* Allow access to a particular port or service: `sudo ufw allow [rule]`
* Deny access to a particular port or service: `sudo ufw deny [rule]`

The following table provides specific examples.

[cols="2,3", options="header"]
|===
|Command |Description

|`sudo ufw allow 22`
|Allows access to port *22* through the firewall. This opens the port for all protocols (TCP and UDP).

|`sudo ufw allow 22/tcp`
|Allows *TCP only* on port *22*.

|`sudo ufw allow ssh`
|Allows the *SSH* service without specifying the port (SSH is usually port `22/tcp`).

|`sudo ufw deny 22`
|Denies access to port *22* through the firewall. This closes the port for all protocols (TCP and UDP).

|`sudo ufw deny 22/tcp`
|Denies *TCP only* on port *22*.

|`sudo ufw deny ssh`
|Denies the *SSH* service without specifying the port (SSH is usually port `22/tcp`).
|===

==== Advanced UFW rules
UFW can do more than basic allow and deny rules. It can also:

* <<allow-block-ip-addresses>> from a specific port.
* <<traffic-direction>> (incoming and outgoing).
* <<rate-limit>> to help protect against brute-force or DDoS attacks.
* <<specify-network-interfaces>> to apply rules specifically to wired or wireless networks.

For more information about these options, run the following command: `man ufw`. This displays the UFW manual page in your terminal, which includes documentation on UFW syntax, options, rule formatting, and examples.

[[allow-block-ip-addresses]]
===== Allow or block a specific IP address
You can allow or deny access from a specific IP address to a specific port. This is useful if you want to block suspicious hosts or allow trusted hosts only. For example, the following command denies access to port 30 from IP address 192.168.2.1

[source,console]
----
$ sudo ufw deny from 192.168.2.1 to any port 30
----

[[traffic-direction]]
===== Specify traffic direction
To control how your system sends or receives network traffic, perhaps to block threats to your system (incoming) or protect system resources (outgoing), you can prevent traffic from coming in one or both directions. Specifically, you can add `out` (for outgoing traffic) or `in` (for incoming traffic) to one of the following commands:

* `allow`, which allows the traffic to flow in the specified direction.
* `deny`, which silently drops the traffic flowing in the specified direction.
* `reject`, which actively refuses the traffic flowing in the specified direction.

For example, the following command prevents all outgoing traffic on the SMTP port (usually port 25/TCP):

[source,console]
----
$ sudo ufw reject out smtp
----

[[rate-limit]]
===== Rate limit connection attempts
To protect against brute-force and DDoS attacks, the `limit` command temporarily blocks any IP address that attempts to make too many connections in a short period of time (approximately 6 or more times within 30 seconds). For example, the following command watches how often an IP address attempts to open a new connection to SSH (usually port `22/tcp`) and applies the rate limit.

[source,console]
----
$ sudo ufw limit ssh/tcp
----

[[specify-network-interfaces]]
===== Specify network interfaces
You can set firewall rules to apply only to a specific network connection (`eth0` for wired networks or `wlan0` for Wi-Fi). For example, the following command allows incoming TCP traffic on port 80 only on the `eth0` network interface:

[source,console]
----
$ sudo ufw allow in on eth0 to any port 80 proto tcp
----

[[rule-management]]
==== Rule management
UFW processes rules in order, and so the order of rules matters. The following table lists useful commands to help you inspect your current firewall configuration and remove rules when necessary.

[cols="2,3", options="header"]
|===
|Command |Description

|`sudo ufw status`
|Displays whether UFW is active and lists all current settings for the firewall (which ports and services are allowed and denied).

|`sudo ufw status verbose`
|Displays additional details, such as default policies and logging settings.

|`sudo ufw show added`
|Displays only user-added rules (excluding internal and system rules). This is useful if you want to review changes or compare configurations across systems.

|`sudo ufw status numbered`
|Displays rules with their assigned index number. This is useful if you want to delete a specific rule.

|`sudo ufw delete <number>`
|Deletes the rule that you specify based on its assigned index number. UFW then renumbers the remaining entries. You can rerun `sudo ufw status numbered` to confirm the rule was removed.
|===


=== Block suspicious activity with `fail2ban`

When using a Raspberry Pi as a server, you must create deliberate holes in your firewall to allow server traffic. http://www.fail2ban.org[Fail2ban] can help secure your server. Fail2ban examines log files and checks for suspicious activity, like multiple brute-force login attempts. It saves you having to manually check log files for intrusion attempts and then update the firewall (via `iptables`) to prevent them.

To install `fail2ban`, run the following command:

[source,console]
----
$ sudo apt install fail2ban
----

On installation, Fail2ban creates `/etc/fail2ban/jail.conf`. To enable Fail2ban, copy `jail.conf` to `jail.local`:

[source,console]
----
$ sudo cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
----

Inside this configuration file are a set of default options, together with options for checking specific services for abnormalities. To examine the rules used for `ssh`, open `jail.local` in an editor:

[source,console]
----
$ sudo nano /etc/fail2ban/jail.local
----

Create the `[ssh]` section if it does not already exist and add the following lines to the section:

[source,ini]
----
[ssh]
enabled  = true
port     = ssh
filter   = sshd
backend  = systemd
maxretry = 6
----

This enables Fail2ban checks for suspicious `ssh` activity, including system log checks, and allows six retries before blocking activity.

The `[default]` section in this same file defines the default banning action, `iptables-multiport`, which runs the `/etc/fail2ban/action.d/iptables-multiport.conf` file when the detection threshold is reached:

[source,ini]
----
# Default banning action (e.g. iptables, iptables-new,
# iptables-multiport, shorewall, etc) It is used to define
# action_* variables. Can be overridden globally or per
# section within jail.local file
banaction = iptables-multiport
----

Multiport bans all access on all ports. The `action.d` folder contains a number of alternative action configuration files you can use to customise your server's response to suspicious activity.

For instance, to permanently ban an IP address after three failed attempts, change the `maxretry` value in the `[ssh]` section to `3` and set the `bantime` to a negative number:

[source,ini]
----
[ssh]
enabled  = true
port     = ssh
filter   = sshd
backend  = systemd
maxretry = 3
bantime  = -1
----
