== Secure your Raspberry Pi

The security of your Raspberry Pi is important. Gaps in security leave your Raspberry Pi open to hackers who can then use it without your permission.

If you expose your Raspberry Pi directly to the internet, either with a direct connection or by letting certain protocols, such as SSH, through your router firewall, you should take steps to ensure the security of your device.

This documentation describes some common ways to improve the security of your Raspberry Pi.

=== Change a user's password

You can change the password for the current user account via the `raspi-config` application on from the command line:

[source,console]
----
$ sudo raspi-config
----

Select option 2, and follow the instructions to change the password.

Alternatively, use the `passwd` application:

[source,console]
----
$ passwd
----

=== Add a user

To add a new user, enter the following command, replacing the `<username>` placeholder with the username for the new user:

[source,console]
----
$ sudo adduser <username>
----

When prompted, enter a password for the new user.

You can find the home directory for the new user at `/home/<username>/`.

To grant the new user necessary permissions, like `sudo`, run the following command to add the user to the associated user groups, replacing the `<username>` placeholder with the username for the new user:

[source,console]
----
$ sudo usermod -a -G adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi <username>
----

To check that the permissions were successfully granted, run the following command, replacing the `<username>` placeholder with the username for the new user:

[source,console]
----
$ sudo su - <username>
----

If the above command runs successfully, permissions were successfully configured for the user.

=== Delete a user

To delete a user, run the following command, replacing the `<username>` placeholder with the username of the user you would like to delete:

[source,console]
----
$ sudo deluser -remove-home <username>
----

This command deletes the user as well as their home directory. If you'd like to preserve the user's home directory, run the command without the `-remove-home` option.

== Change the default user

To change the user that automatically logs into your Raspberry Pi on boot, run the following command:

[source,console]
----
$ sudo raspi-config
----

Select option 1, S5 `Boot / Auto login`. Then, say yes to reboot.

=== Require a password for `sudo` commands

Placing `sudo` in front of a command runs it as a superuser. By default, that does not need a password. However, you can make your Raspberry Pi more secure by requiring a password for all commands run with `sudo`.

To force `sudo` to require a password, edit the `nopasswd` sudoers file for your user account, replacing the `<username>` placeholder in the file name with your username:

[source,console]
----
$ sudo visudo /etc/sudoers.d/010_<username>-nopasswd
----

Change the `<username>` entry to the following, replacing `<username>` with your username:

[source,console]
----
<username> ALL=(ALL) PASSWD: ALL
----

Save the file. Your new preference should take effect immediately.

=== UpdateRaspberry Pi OS

Only the latest OS distribution contains all the latest security fixes. Always keep your device xref:os.adoc#updating-and-upgrading-raspberry-pi-os[updated] to the latest version of Raspberry Pi OS.

If you use SSH to connect to your Raspberry Pi, it can be worthwhile to add a `cron` job that specifically updates the SSH server. The following command, perhaps as a daily cron job, ensures you have the latest SSH security fixes promptly, independent of your normal update process.

[source,console]
----
$ apt install openssh-server
----

=== Improving SSH Security

SSH is a common way of accessing a Raspberry Pi remotely. By default, logging in with SSH requires a username/password pair. But you can make this even more secure with key-based authentication.

==== Improving username/password security

Always ensure you have a very robust password. If your Raspberry Pi is exposed to the internet, the password needs to be very secure. This will help to avoid dictionary attacks or the like.

You can also *allow* or *deny* specific users by altering the `sshd` configuration.

[source,console]
----
$ sudo nano /etc/ssh/sshd_config
----

Add, edit, or append to the end of the file the following line, which contains the usernames you wish to allow to log in:

[source,bash]
----
AllowUsers alice bob
----

You can also use `DenyUsers` to specifically stop some usernames from logging in:

[source,bash]
----
DenyUsers jane john
----

After the change you will need to restart the `sshd` service using `sudo systemctl restart ssh` or reboot so the changes take effect.

==== Using key-based authentication.

Key pairs are two cryptographically secure keys. One is private, and one is public. They can be used to authenticate a client to an SSH server (in this case the Raspberry Pi).

The client generates two keys, which are cryptographically linked to each other. The private key should never be released, but the public key can be freely shared. The SSH server takes a copy of the public key, and, when a link is requested, uses this key to send the client a challenge message, which the client will encrypt using the private key. If the server can use the public key to decrypt this message back to the original challenge message, then the identity of the client can be confirmed.

Generating a key pair in Linux is done using the `ssh-keygen` command on the *client*; the keys are stored by default in the `.ssh` folder in the user's home directory. The private key will be called `id_rsa` and the associated public key will be called `id_rsa.pub`. The key will be 2048 bits long: breaking the encryption on a key of that length would take an extremely long time, so it is very secure. You can make longer keys if the situation demands it. Note that you should only do the generation process once: if repeated, it will overwrite any previous generated keys. Anything relying on those old keys will need to be updated to the new keys.

You will be prompted for a passphrase during key generation: this is an extra level of security. For the moment, leave this blank.

The public key now needs to be moved on to the server: see xref:remote-access.adoc#copy-your-public-key-to-your-raspberry-pi[Copy your public key to your Raspberry Pi].

Finally, we need to disable password logins, so that all authentication is done by the key pairs.

[source,console]
----
$ sudo nano /etc/ssh/sshd_config
----

There are three lines that need to be changed to `no`, if they are not set that way already:

[,bash]
----
ChallengeResponseAuthentication no
PasswordAuthentication no
UsePAM no
----

Save the file and either restart the ssh system with `sudo service ssh reload` or reboot.

=== Install a Firewall

There are many firewall solutions available for Linux. Most use the underlying http://www.netfilter.org/projects/iptables/index.html[iptables] project to provide packet filtering. This project sits over the Linux netfiltering system. `iptables` is installed by default on Raspberry Pi OS, but is not set up. Setting it up can be a complicated task, and one project that provides a simpler interface than `iptables` is https://www.linux.com/learn/introduction-uncomplicated-firewall-ufw[ufw], which stands for 'Uncomplicated Fire Wall'. This is the default firewall tool in Ubuntu, and can be  installed on your Raspberry Pi:

[source,console]
----
$ sudo apt install ufw
----

`ufw` is a fairly straightforward command line tool, although there are some GUIs available for it. This document will describe a few of the basic command line options. Note that `ufw` needs to be run with superuser privileges, so all commands are preceded with `sudo`. It is also possible to use the option `--dry-run` any `ufw` commands, which indicates the results of the command without actually making any changes.

To enable the firewall, which will also ensure it starts up on boot, use:

[,bash]
----
sudo ufw enable
----

To disable the firewall, and disable start up on boot, use:

[,bash]
----
sudo ufw disable
----

Allow a particular port to have access (we have used port 22 in our example):

[,bash]
----
sudo ufw allow 22
----

Denying access on a port is also very simple (again, we have used port 22 as an example):

[,bash]
----
sudo ufw deny 22
----

You can also specify which service you are allowing or denying on a port. In this example, we are denying tcp on port 22:

[,bash]
----
sudo ufw deny 22/tcp
----

You can specify the service even if you do not know which port it uses. This example allows the ssh service access through the firewall:

[,bash]
----
sudo ufw allow ssh
----

The status command lists all current settings for the firewall:

[,bash]
----
sudo ufw status
----

The rules can be quite complicated, allowing specific IP addresses to be blocked, specifying in which direction traffic is allowed, or limiting the number of attempts to connect, for example to help defeat a Denial of Service (DoS) attack. You can also specify the device rules are to be applied to (e.g. eth0, wlan0). Please refer to the `ufw` man page (`man ufw`) for full details, but here are some examples of more sophisticated commands.

Limit login attempts on ssh port using tcp: this denies connection if an IP address has attempted to connect six or more times in the last 30 seconds:

[,bash]
----
sudo ufw limit ssh/tcp
----

Deny access to port 30 from IP address 192.168.2.1

[,bash]
----
sudo ufw deny from 192.168.2.1 port 30
----

=== Installing `fail2ban`

If you are using your Raspberry Pi as some sort of server, for example an `ssh` or a webserver, your firewall will have deliberate 'holes' in it to let the server traffic through. In these cases, http://www.fail2ban.org[Fail2ban] can be useful. Fail2ban, written in Python, is a scanner that examines the log files produced by the Raspberry Pi, and checks them for suspicious activity. It catches things like multiple brute-force attempts to log in, and can inform any installed firewall to stop further login attempts from suspicious IP addresses. It saves you having to manually check log files for intrusion attempts and then update the firewall (via `iptables`) to prevent them.

Install `fail2ban` using the following command:

[source,console]
----
$ sudo apt install fail2ban
----

On installation, Fail2ban creates a folder `/etc/fail2ban` in which there is a configuration file called `jail.conf`. This needs to be copied to `jail.local` to enable it. Inside this configuration file are a set of default options, together with options for checking specific services for abnormalities. Do the following to examine/change the rules that are used for `ssh`:

[source,console]
----
$ sudo cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
$ sudo nano /etc/fail2ban/jail.local
----

Add the following section to the `jail.local` file. On some versions of fail2ban this section may already exist, so update this pre-existing section if it is there.

[source,bash]
----
[ssh]
enabled  = true
port     = ssh
filter   = sshd
backend  = systemd
maxretry = 6
----

As you can see, this section is named ssh, is enabled, examines the ssh port, filters using the `sshd` parameters, parses the system log for malicious activity, and allows six retries before the detection threshold is reached. Checking the default section, we can see that the default banning action is:

[source,bash]
----
# Default banning action (e.g. iptables, iptables-new,
# iptables-multiport, shorewall, etc) It is used to define
# action_* variables. Can be overridden globally or per
# section within jail.local file
banaction = iptables-multiport
----

`iptables-multiport` means that the Fail2ban system will run the `/etc/fail2ban/action.d/iptables-multiport.conf` file when the detection threshold is reached. There are a number of different action configuration files that can be used. Multiport bans all access on all ports.

If you want to permanently ban an IP address after three failed attempts, you can change the maxretry value in the `[ssh]` section, and set the bantime to a negative number:

[source,bash]
----
[ssh]
enabled  = true
port     = ssh
filter   = sshd
backend  = systemd
maxretry = 3
bantime = -1
----
