name: Build and deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
      url:
        type: string
      deploy:
        type: boolean
        default: false

jobs:
  build:
    runs-on: [self-hosted, web]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
          submodules: recursive
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: 3.14
      - name: Install Python dependencies
        run: |
          pip3 install --upgrade pip setuptools wheel
          pip3 install -r ./requirements.txt
      - uses: ruby/setup-ruby@984c0c890880bbf811283d6f09c4607c62d210a4
        with:
          ruby-version: 3.2
          bundler-cache: true
      - name: Install Ninja
        run: pip3 install ninja==1.10.2.4
      - name: Install arm-none-eabi-gcc GNU Arm Embedded Toolchain
        if: ${{ inputs.deploy }}
        uses: carlosperate/arm-none-eabi-gcc-action@98c40e51546516419841748d3210c290df0d2c6c
      - name: Install Doxygen
        if: ${{ inputs.deploy }}
        run: |
          wget https://www.doxygen.nl/files/doxygen-1.10.0.linux.bin.tar.gz
          if echo 'dcfc9aa4cc05aef1f0407817612ad9e9201d9bf2ce67cecf95a024bba7d39747  doxygen-1.10.0.linux.bin.tar.gz' | sha256sum --check --status
          then
            tar xf doxygen-1.10.0.linux.bin.tar.gz -C "$HOME"
            echo "$HOME/doxygen-1.10.0/bin" >> $GITHUB_PATH
          fi
      - name: Build Doxygen documentation
        if: ${{ inputs.deploy }}
        run: make build_doxygen_adoc
      - name: Build documentation
        run: make -j 2
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: ${{ inputs.deploy }}
        with:
          name: documentation
          path: documentation/html/
          if-no-files-found: error
          retention-days: 1
          include-hidden-files: true

  deploy:
    needs: build
    if: ${{ inputs.deploy }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
          sparse-checkout: .github/actions
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: documentation
          path: documentation/html
      - name: Deploy to Mythic Beasts
        uses: ./.github/actions/deploy-action
        with:
          private_ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
          bastion_host: ${{ secrets.DEPLOY_BASTION_HOST }}
          primary_host: ${{ secrets.DEPLOY_PRIMARY_HOST }}
          secondary_host: ${{ secrets.DEPLOY_SECONDARY_HOST }}
          source: documentation/html/
          destination: documentation
